= EntityEditModel
:dir-source: ../../../../../demos/manual/src/main/java
:dir-tutorials: ../tutorials
:url-javadoc: link:../api

The {url-javadoc}/org/jminor/framework/model/EntityEditModel.html[EntityEditModel] interface defines the CRUD business logic used by the {url-javadoc}/org/jminor/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] class when entities are being edited. The EntityEditModel works with a single entity instance, called the active entity, which can be set via the {url-javadoc}/org/jminor/framework/model/EntityEditModel.html#setEntity-org.jminor.framework.domain.Entity-[setEntity(Entity entity)] method and retrieved via {url-javadoc}/org/jminor/framework/model/EntityEditModel.html#getEntityCopy--[getEntityCopy()]. The EntityEditModel interface exposes a number of methods for manipulating as well as querying the property values of the active entity.

[source,java,indent=0]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/AddressModel.java[lines=9..-1]
----

[source,java,indent=0]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/CustomerEditModel.java[lines=10..-1]
----

[source,java,indent=0]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/AddressEditModel.java[lines=10..-1]
----

[source,java,indent=0]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/Misc.java[tags=editModel]
----