= JMinor EmpDept Tutorial

:javadoc-root: https://heima.hafro.is/~darri/jminor_wiki_data/project/docs/api
:source-dir: ../../demos/empdept/src/main/java
:test-source-dir: ../../demos/empdept/src/test/java

== Domain model

We start by creating a class named EmpDept in a package of our choosing, extending Entities. This first section contains a few optional fields, which are included here for demonstration purposes, **bundle** and the i18n constants.
[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/domain/EmpDept.java[lines=16..32]
----

Next we define the constants required for the department [[documentation:manual#entity|entity]], which is based on the SCOTT.DEPT table. One constant defines the entity itself and will be referred to as the *entityId* (here prefixed with T_), the other three represent the columns in the table and will be referred to as *propertyIds*. The entityId in this example contains the actual table name (scott.dept), but the table name can be specified if that is preferred. The propertyIds contain the actual column names from the table.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/domain/EmpDept.java[lines=33..40]
----

Next we define the constants required for the employee entity, which is based on the EMP table. Here there are two additional propertyIDs with _FK suffixes, we'll use these later when we specify the foreign key properties for the employee entity.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/domain/EmpDept.java[lines=41..62]
----

In this section we add a constructor, calling the two methods which define the domain entities

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/domain/EmpDept.java[lines=63..68]
----

Next we add the method defining the department entity. *EntityDefinition* instances are provided by the {javadoc-root}/org/jminor/framework/domain/Entities.html[Entities] class, via the *define* method which comes in two flavours, one which assumes the *entityID* contains the underlying table name and one which does not, and therefore requires an additional *tableName* parameter. We use the latter below. Note that we fetch caption strings for the properties from the i18n bundle via *getString()*. In a single language model we would simply use "Caption" instead, see [[documentation:tutorials:chinook#domain_model|Chinook domain model]]. For an overview of the *Property* class see [[documentation:manual#property|JMinor manual:Property]]. The *EntityDefinition* class provides chained setters for setting entity attributes, such as the primary key value source. Here we set *idSource* to *IdSource.NONE* since the department number is chosen manually, the so-called *stringProvider* which is responsible for providing *toString()* implementations for entities, the *smallDataset* attribute which hints that it is OK to automatically base ComboBoxes on the entity and we also set the *caption*. In this case we simply have the department string provider return the department name.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/domain/EmpDept.java[lines=69..83]
----

Next we define the employee entity. Here we set the *keyGenerator* to *Entities.incrementKeyGenerator(T_EMPLOYEE, EMPLOYEE_ID)* which, as the name suggests, simply increments the maximum column value by one (__N.B. this is a very simplistic implementation which is absolutely not transaction safe__). Here we also introduce the [[documentation:manual#foreignkeyproperty|ForeignKeyProperty]], the *orderByClause*, as well as a *BackgroundColorProvider* which is responsible for providing a custom color for a entity instance.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/domain/EmpDept.java[lines=84..117]
----

At last there is the *getString()* method for retrieving i18n strings from the resource bundle.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/domain/EmpDept.java[lines=118..122]
----

== Domain model unit test

Implementing the domain model unit test is a trivial thing, we extend {javadoc-root}/org/jminor/framework/tools/testing/EntityTestUnit.html[EntityTestUnit] and create a public test method for each entity we want tested and within that method call *testEntity(entityId)*. The *EntityTestUnit* relies on information from the domain model to construct random entity instances and run insert, update, select and delete tests. The tests are run within their own transactions which are then rolled back. We can provide our own entity instances if we'd like by overriding *initializeTestEntity(entityID)* handling the cases we'd like and delegating the rest to the superclass implementation. The same can be done for referenced entities, that is, entities that are referenced via foreign keys and are required in order to be able to insert records. We override *getTestUser()*, the default implementation simply prompts for login credentials.

[source,java]
----
include::{test-source-dir}/org/jminor/framework/demos/empdept/domain/EmpDeptTest.java[lines=1..43]
----

Here are the parameters required for running the EmpDept test on the default H2 embedded database, assuming the database resides in the working directory.

-Djminor.db.type=h2

-Djminor.db.embedded=true

-Djminor.db.host=h2db/h2

For further information on parameters required for running JMinor applications see [[documentation:technical:client#configuration|client configuration]] and [[documentation:technical:server#configuration|server configuration]].

== Application model layer

In many cases we can use the default model implementations, but here we will customize the employee edit model by extending {javadoc-root}/org/jminor/framework/model/DefaultEntityEditModel.html[DefaultEntityEditModel].

We must provide a constructor taking a single *EntityConnectionProvider* parameter. We also call the *bindEvents* method we define later on.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/EmployeeEditModel.java[lines=17..23]
----

Now, at some point we are going to be editing the manager property of an employee which means we'll need a value list of managers. We override *createForeignKeyComboBoxModel* in order to provide a specialized combo box model for the manager property.

NOTE: The foreign key propertyID is used when referring to the manager property, very rarely do we have to worry about the underlying reference property//.

After handling the manager case we simply delegate to the super class implementation, which by default creates an unfiltered {javadoc-root}/org/jminor/framework/model/EntityComboBoxModel.html[EntityComboBoxModel], showing all the underlying entities.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/EmployeeEditModel.java[lines=24..42]
----

Finally we bind a couple events, for further information see [[documentation:manual#event_binding|JMinor manual:Event binding]].

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/EmployeeEditModel.java[lines=43..64]
----

== Application UI layer

If we want to do any editing we must provide a *EntityEditPanel* implementation for the entity, we start by creating a *DepartmentEditPanel*.

A class extending *EntityEditPanel* must provide a constructor taking a single *SwingEntityEditModel* parameter.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/ui/DepartmentEditPanel.java[lines=14..19]
----

We override the *intializeUI* method to construct the actual UI, used for editing the department entity. The {javadoc-root}/org/jminor/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] class provides methods for creating all the basic controls required, named *create...*, such as *createTextField(propertyID)* or *createForeignKeyComboBox(foreignKeyPropertyID)*.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/ui/DepartmentEditPanel.java[lines=20..48]
----

We extend *EntityTablePanel* for the department entity in order to provide a report print action.

A class extending *EntityTablePanel* must provide a constructor taking a single *EntityTableModel* parameter.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/ui/DepartmentTablePanel.java[lines=20..25]
----

We create a method for viewing a report, which is called via an action we'll initialize in the next step. For further information about report viewing and printing see [[documentation:manual#reporting_with_jasperreports|JMinor manual:Reporting with JasperReports]].

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/ui/DepartmentTablePanel.java[lines=26..39]
----

Next we override *getPrintControls()* to add our report action to the popup print control set.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/ui/DepartmentTablePanel.java[lines=40..48]
----

For editing employee entities we create the *EmployeeEditPanel* class.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/ui/EmployeeEditPanel.java[lines=16..21]
----

All we have to do is override *initializeUI*.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/beans/ui/EmployeeEditPanel.java[lines=22..52]
----

== Main application panel

We create a main application panel by extending {javadoc-root}/org/jminor/framework/client/ui/EntityApplicationPanel.html[EntityApplicationPanel]. Overriding *setupEntityPanelProviders()* we configure two *EntityPanelProvider* objects, //employeePanelProvider// and //departmentPanelProvider//. We'll define the *EmployeePanelProvider* class later.

We override *setupEntityPanelProviders* and call *addEntityPanelProvider()* designating the department panel as the main application panel.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=33..55]
----

Next we add a method for importing a JSON text file, which we'll call via an action initialized in the next section.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=57..62]
----

We override *getToolsControlSet()* to add our import action to the Tools menu.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=64..70]
----

We implement *initializeApplicationModel()* by returning an instance of the *EmpDeptApplicationModel* class, which we'll create later.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=72..75]
----

We create a *main()* method for configuring and running the application.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=77..83]
----

We then create the *EmpDeptApplicationModel* class by extending *SwingEntityApplicationModel*.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=85..90]
----

We then create a *EmployeeModelProvider* by extending *SwingEntityModelProvider*, in order to configure the table model after initialization.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=92..102]
----

We create a *EmployeePanelProvider* by extending *EntityPanelProvider*, in order to configure the table panel after initialization.
See [[documentation:technical:client#configuration|client configuration]] for what is required for running the client.

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/client/ui/EmpDeptAppPanel.java[lines=104..113]
----

== Application load test

[source,java]
----
include::{source-dir}/org/jminor/framework/demos/empdept/testing/EmpDeptLoadTest.java[]
----
