= EntityEditPanel
:dir-source: ../../demos/manual/src/main/java
:url-javadoc: https://heima.hafro.is/~darri/jminor_site/docs/api

The {url-javadoc}/org/jminor/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] contains the controls (text fields, combo boxes and such) for editing an entity instance.

When extending an EntityEditPanel you must implement the *initializeUI()* method, which initializes the edit panel UI. The EntityEditPanel class exposes methods for creating input components and binding them with the underlying {url-javadoc}/org/jminor/swing/framework/model/EntityEditModel.html[EntityEditModel] instance.

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/ui/CustomerEditPanel.java[lines=12..-1]
----

== Input controls

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createBooleanComboBox-java.lang.String-[createBooleanComboBox(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createCheckBox-java.lang.String-[createCheckBox(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyComboBox-java.lang.String-[createForeignKeyComboBox(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyField-java.lang.String-[createForeignKeyField(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyLookupField-java.lang.String-[createForeignKeyLookupField(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createPropertyComboBox-java.lang.String-[createPropertyComboBox(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createTemporalInputPanel-java.lang.String-[createTemporalInputPanel(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createTextArea-java.lang.String-[createTextArea(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createTextField-java.lang.String-[createTextField(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createTextInputPanel-java.lang.String-[createTextInputPanel(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createNullableCheckBox-java.lang.String-[createNullableCheckBox(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createValueListComboBox-java.lang.String-[createValueListComboBox(propertyId)]

== Panels & labels

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createLabel-java.lang.String-[createLabel(propertyId)]

{url-javadoc}/org/jminor/swing/framework/ui/EntityEditComponentPanel.html#createPropertyPanel-java.lang.String-[createPropertyPanel(propertyId)]

== Custom actions
The action mechanism used throughout the JMinor framework is based on the {url-javadoc}/org/jminor/swing/common/ui/control/Control.html[Control] class and its subclasses and the {url-javadoc}/org/jminor/swing/common/ui/control/ControlSet.html[ControlSet] class which, as the name suggests, represents a set of controls. There are two static utility classes for creating and presenting controls, {url-javadoc}/org/jminor/swing/common/ui/control/Controls.html[Controls] and {url-javadoc}/org/jminor/swing/common/ui/control/ControlProvider.html[ControlProvider] respectively.