= EntityModel
:dir-source: ../../demos/manual/src/main/java
:dir-tutorials: ../tutorials
:url-javadoc: https://heima.hafro.is/~darri/jminor_site/{jminor-version}/api

The {url-javadoc}/org/jminor/framework/model/EntityModel.html[EntityModel] class links together and coordinates between a {url-javadoc}/org/jminor/framework/model/EntityEditModel.html[EntityEditModel] and a {url-javadoc}/org/jminor/framework/model/EntityTableModel.html[EntityTableModel], where the *EntityEditModel* handles CRUD operations and the *EntityTableModel* provides a table representation of the underlying entities.

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/AddressModel.java[lines=9..-1]
----

== Edit model

Each {url-javadoc}/org/jminor/framework/model/EntityModel.html[EntityModel] contains a single {url-javadoc}/org/jminor/framework/model/EntityEditModel.html[EntityEditModel] instance. This edit model can be created automatically by the *EntityModel* or supplied via a constructor argument in case of a specialized implementation.

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/CustomerEditModel.java[lines=10..-1]
----

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/AddressEditModel.java[lines=10..-1]
----

[source,java,indent=0]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/Misc.java[lines=20..53]
----

== Table model

Each {url-javadoc}/org/jminor/framework/model/EntityModel.html[EntityModel] can contain a single {url-javadoc}/org/jminor/framework/model/EntityTableModel.html[EntityTableModel] instance. This table model can be created automatically by the *EntityModel* or supplied via a constructor argument in case of a specialized implementation.

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/CustomerTableModel.java[lines=10..-1]
----

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/AddressTableModel.java[lines=10..-1]
----

== Detail models

Detail models can be added to a model, this relies on a foreign key reference between the entities involved.

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/StoreAppModel.java[lines=10..-1]
----

== Event binding

The EntityModel, EntityEditModel and EntityTableModel classes expose a number of *addListener* methods.

The following example prints, to the standard output, all changes made to a given property as well as a message indicating that a refresh has started.

[source,java,indent=0]
----
include::{dir-source}/org/jminor/framework/demos/manual/store/model/CustomerModel.java[lines=18..27]
----

== Examples
* <<{dir-tutorials}/empdept.adoc#_application_model_layer, EmpDept entity models>>