= Manual
:toc: right
:dir-tutorials: ../tutorials

== The basics

=== Common classes

Two common classes used throughout the framework are the {url-javadoc}/org/jminor/common/Event.html[Event] and {url-javadoc}/org/jminor/common/State.html[State] classes and their respective observers {url-javadoc}/org/jminor/common/EventObserver.html[EventObserver] and {url-javadoc}/org/jminor/common/StateObserver.html[StateObserver] and listeners {url-javadoc}/org/jminor/common/EventListener.html[EventListener] and {url-javadoc}/org/jminor/common/EventInfoListener.html[EventInfoListener].

=== Event ===

The {url-javadoc}/org/jminor/common/Event.html[Event] class is a simple event implementation used throughout the framework to signal object state changes or to indicate that an action is about to start or has ended. Classes typically publish their events via public *addListener* methods. Events are triggered by calling the *fire()* method, with or without a *data* parameter.

Events are instantiated via the {url-javadoc}/org/jminor/common/Events.html[Events] factory class.

To listen to Events you use the {url-javadoc}/org/jminor/common/EventListener.html[EventListener] or {url-javadoc}/org/jminor/common/EventDataListener.html[EventDataListener] interfaces.

[source,java]
----
Event<String> event = Events.event(); # <1>

event.addDataListener(data -> System.out.println("Event happened: " + data)); # <2>

event.fire();//writes out "Event happened: null";
event.fire("data");//writes out "Event happened: data";
----
<1> Initialize the Event
<2> Add a listener

=== State ===

The {url-javadoc}/org/jminor/common/State.html[State] class encapsulates a boolean state (active/inactive) and provides a {url-javadoc}/org/jminor/common/StateObserver.html[StateObserver]:

States are instantiated via the {url-javadoc}/org/jminor/common/States.html[States] factory class.

[source,java]
----
State state = States.state(false); # <1>

state.addListener(() -> System.out.println("State changed")); # <2>

state.set(true);//prints out "State changed";
----
<1> Initialize the State with initial value 'false'
<2> Add a listener

Any *Action* object can be linked to a *State* object via the *UiUtil.linkToEnabledState* method, where the action's *enabled* status is synchronized with the state.


[source,java]
----
State state = States.state();

Action action = new AbstractAction("action") {
  public void actionPerformed(ActionEvent e) {}
};

UiUtil.linkToEnabledState(state, action);

//action.isEnabled() now returns false, since State objects are by default inactive.

state.set(true);

//action.isEnabled() now returns true.
----

== Domain Model

The domain model is based around two interfaces, {url-javadoc}/org/jminor/framework/domain/Entity.html[org.jminor.framework.domain.Entity], which represents a row in a table, and {url-javadoc}/org/jminor/framework/domain/Property.html[org.jminor.framework.domain.Property], which represents columns. The
{url-javadoc}/org/jminor/framework/domain/Domain.html[org.jminor.framework.domain.Domain] class serves as a container for the domain model definition and as a factory for Entity and Entity.Key objects.

=== Entity

An Entity object represents a row in a table and maps each column value to its respective property. Each type of Entity is identified by a *entityId*,
a string constant which must be unique within the domain. The simplest way to define a unique *entityId* is to use the underlying table name.

Defining the *entityId* as a static string constant in the domain class is recommended.

NOTE: The *entityId* constant does not have to be the table name, you can use whatever identifying string you want and specify the table name separately.

[source,java]
----
/*
 * The Store class defines the domain model for the Store application
 */
public class Store extends Domain {
  //the full name of the table, will serve as the entityId for the Entity based on this table
  public static final String T_ADDRESS = "store.address";

  //the full name of the table, will serve as the entityId for the Entity based on this table
  public static final String T_CUSTOMER = "store.customer";
}
----

=== Property

Each column in a table is defined by the {url-javadoc}/org/jminor/framework/domain/Property.html[Property] class or one of its subclasses. The {url-javadoc}/org/jminor/framework/domain/Properties.html[Properties] class provides factory methods for constructing Property objects.
The following attributes can be set by using chained method calls:
__hidden, updatable, readOnly, nullable, defaultValue, maxLength, preferredWidth, description, mnemonic, columnHasDefaultValue, format__
[source,java]
----
Properties.columnProperty(PROPERTY_ID, Types.INTEGER, "Caption")
              .setNullable(false).setDescription("This is a non-nullable property")
----

==== Supported data types

JMinor supports the following column data types:

* Integer (java.sql.Types.INTEGER)
* Double (java.sql.Types.DOUBLE)
* Long (java.sql.Types.BIGINT)
* BigDecimal (java.sql.Types.DECIMAL)
* LocalDateTime (java.sql.Types.TIMESTAMP)
* LocalDate (java.sql.Types.DATE)
* LocalTime (java.sql.Types.TIME)
* String (java.sql.Types.VARCHAR)
* Boolean (java.sql.Types.BOOLEAN)
* Character (java.sql.Types.CHAR)
* Blob (java.sql.Types.BLOB)

==== Property id constants

For each column you define a string constant, you can use the actual underlying column name, i.e. 'first_name' or any other string. This constant is used when defining the property based on that column and serves as the property identifier. This __propertyId__ is assumed to be the actual column name when constructing SQL queries unless the column name has been set via __setColumnName()__.

[source,java]
----
/*
 * The Store class defines the domain model for the Store application
 */
public class Store extends Domain {
  //the full name of the table, will serve as the entityId for the Entity based on this table
  public static final String T_ADDRESS = "store.address";

  //Property constant identifying the column ID in the ADDRESS table
  public static final String ADDRESS_ID = "id";
  //Property constant identifying the column STREET in the ADDRESS table
  public static final String ADDRESS_STREET = "street";
  //Property constant identifying the column CITY in the ADDRESS table
  public static final String ADDRESS_CITY = "city";

  //the full name of the table, will serve as the entityId for the Entity based on this table
  public static final String T_CUSTOMER = "store.customer";

  //Property constant identifying the column ID in the CUSTOMER table
  public static final String CUSTOMER_ID = "id";
  //Property constant identifying the column FIRST_NAME in the CUSTOMER table
  public static final String CUSTOMER_FIRST_NAME = "first_name";
  //Property constant identifying the column LAST_NAME in the CUSTOMER table
  public static final String CUSTOMER_LAST_NAME = "last_name";
  //Property constant identifying the foreign key referencing the ADDRESS entity,
  //the value is somewhat arbitrary since it does not map to a column
  public static final String CUSTOMER_ADDRESS_FK = "address_fk";
  //Property constant identifying the column referencing the STORE.ADDRESS table
  public static final String CUSTOMER_ADDRESS_ID = "address_id";
  //Property constant identifying the column IS_ACTIVE in the CUSTOMER table
  public static final String CUSTOMER_IS_ACTIVE = "is_active";
  //Property constant identifying the denormalized column CITY in the CUSTOMER table
  public static final String CUSTOMER_CITY = "city";
  //Property constant identifying a derived property CUSTOMER entity
  public static final String CUSTOMER_DERIVED = "derived";
}
----

==== Property

{url-javadoc}/org/jminor/framework/domain/Property.html[Property] and its subclasses are used to represent entity properties, these can be transient or based on table columns.

[source,java]
----
Properties.transientProperty(CUSTOMER_TOKEN, Types.VARCHAR, "Token")
----

==== ColumnProperty

{url-javadoc}/org/jminor/framework/domain/Property.ColumnProperty.html[ColumnProperty] is used to represent properties that are based on table columns.

[source,java]
----
Properties.columnProperty(CUSTOMER_LAST_NAME, Types.VARCHAR, "Last name")
----

==== Primary key

Entities must have at least one primary key column property.

The only requirement is that the primary key properties represent a unique column combination for the underlying table, it does not have to correspond to an actual table primary key, although that is of course preferable. The framework does not enforce uniqueness for these properties, so a unique or primary key on the corresponding table columns is strongly recommended.
[source,java]
----
Properties.primaryKeyProperty(CUSTOMER_ID)//by default Types.INTEGER and primaryKeyIndex 0
----
If the primary key is comprised of more than one column you must set the primary key index.
[source,java]
----
Properties.columnProperty(ID_1, Types.INTEGER).setPrimaryKeyIndex(0),
Properties.columnProperty(ID_2, Types.INTEGER).setPrimaryKeyIndex(1),
----

==== ForeignKeyProperty

{url-javadoc}/org/jminor/framework/domain/Property.ForeignKeyProperty.html[ForeignKeyProperty] is a wrapper property used to indicate a foreign key relation. These foreign keys refer to the primary key of the referenced entity and must be constructed accordingly in case of non-trivial primary keys.
[source,java]
----
//referring to an entity with a single column primary key
Properties.foreignKeyProperty(CUSTOMER_ADDRESS_FK, "Address", T_ADDRESS,
        Properties.columnProperty(CUSTOMER_ADDRESS_ID))

//referring to an entity with a dual column primary key
Properties.foreignKeyProperty(MASTER_FK, "Master", T_MASTER,
        new Property.ColumnProperty[] {
                Properties.columnProperty(MASTER_ID_1),
                Properties.columnProperty(MASTER_ID_2)
        });
----

In this example CUSTOMER_ADDRESS_FK is the ID of the foreign key property and can be used to retrieve the actual entity being referred to.
[source,java]
----
Entity address = customer.getForeignKey(CUSTOMER_ADDRESS_FK);
----
CUSTOMER_ADDRESS_ID is the actual column used as foreign key and retrieving that will simply return the reference id value.
[source,java]
----
Integer addressId = customer.getInteger(CUSTOMER_ADDRESS_ID);
----
By default one level of foreign key values is eagerly fetched during selects, this can be overridden via __setFetchDepth()__. Note that the example below does not really make sense since the ADDRESS entity doesn't have any foreign keys, but if id did the entities referred to via these keys would be eagerly loaded.
[source,java]
----
//referring to an entity with a single column primary key
Properties.foreignKeyProperty(CUSTOMER_ADDRESS_FK, "Address", T_ADDRESS,
        Properties.columnProperty(CUSTOMER_ADDRESS_ID)).setFetchDepth(2)
----

==== Boolean Properties

For databases supporting *Types.BOOLEAN* you simply use *Properties.columnProperty*.
[source,java]
----
Properties.columnProperty(CUSTOMER_IS_ACTIVE, Types.BOOLEAN, "Is active")
----
For databases lacking native boolean support we use the *Properties.booleanProperty* method, specifying the actual true/false values.
[source,java]
----
Properties.booleanProperty(CUSTOMER_IS_ACTIVE, Types.INTEGER, "Is active", 1, 0)
----
For boolean columns using unconventional types you can specify the true and false values.
[source,java]
----
Properties.booleanProperty(CUSTOMER_IS_ACTIVE, Types.VARCHAR, "Is active", "true", "false")
----
[source,java]
----
Properties.booleanProperty(CUSTOMER_IS_ACTIVE, Types.CHAR, "Is active", 'T', 'F')
----
Note that boolean properties always use the boolean Java type, the framework handles translating to and from the actual column values.
[source,java]
----
entity.put(CUSTOMER_IS_ACTIVE, true);

boolean isActive = entity.getBoolean(CUSTOMER_IS_ACTIVE);
----

==== DenormalizedProperty

{url-javadoc}/org/jminor/framework/domain/Property.DenormalizedProperty.html[DenormalizedProperty] is used for columns that should automatically get their value from a column in a referenced table. This property automatically gets the value from the column in the referenced table when the corresponding reference property value is set.
[source,java]
----
Properties.denormalizedProperty(CUSTOMER_CITY, CUSTOMER_ADDRESS_FK,
        getProperty(T_ADDRESS, ADDRESS_CITY), "City")
----

NOTE: The property is not kept in sync if the denormalized property is updated in the referenced entity.

[source,java]
----
Domain domain = getDomain();
Entity address = domain.entity(T_ADDRESS);
address.put(ADDRESS_CITY, "Syracuse");

Entity customer = domain.entity(T_CUSTOMER);
customer.put(CUSTOMER_ADDRESS_FK, address);

customer.get(CUSTOMER_CITY);//returns "Syracuse"

//NB
address.put(ADDRESS_CITY, "Canastota");
customer.get(CUSTOMER_CITY, still returns "Syracuse"

customer.put(CUSTOMER_ADDRESS_FK, address);//set the referenced value again
customer.get(CUSTOMER_CITY);//now this returns "Canastota"
----

==== SubqueryProperty

{url-javadoc}/org/jminor/framework/domain/Property.SubqueryProperty.html[SubqueryProperty] is used to represent properties which get their value from a subquery returning a single value. Note that in the example below __reference_id__ must be available when the query is run, that is, the entity must include that column as a property.
[source,java]
----
Properties.subqueryProperty(SUBQUERY_PROPERTY_ID, Types.VARCHAR, "Caption",
        "select field from schema.table where id = reference_id"))
----

==== TransientProperty

{url-javadoc}/org/jminor/framework/domain/Property.TransientProperty.html[TransientProperty] is used to represent a property which is not based on an underlying column, these properties all have a default value of null and can be set and retrieved just like normal properties.

==== DerivedProperty

{url-javadoc}/org/jminor/framework/domain/Property.DerivedProperty.html[DerivedProperty] is used to represent a transient property which value is derived from one or more properties in the same entity. The value of a derived property is provided via a {url-javadoc}/org/jminor/framework/domain/Property.DerivedProperty.Provider.html[DerivedProperty.Provider] implementation as shown below.
[source,java]
----
Properties.derivedProperty(SUM_ID, Types.INTEGER, "Sum",
         new Property.DerivedProperty.Provider() {
           public Object getValue(Map<String, Object> linkedValues) {
             //linkedValues contains the values of the linked properties
             Integer linkedOne = (Integer) linkedValues.get(SOURCE_PROPERTY_ID_1);
             Integer linkedTwo = (Integer) linkedValues.get(SOURCE_PROPERTY_ID_2);

             return linkedOne + linkedTwo;
           }
         }, SOURCE_PROPERTY_ID_1, SOURCE_PROPERTY_ID_2),
----

==== Examples
* <<{dir-tutorials}/chinook.adoc#domain-model, Chinook domain model>>

== Domain

The *Domain* class serves as a factory class for Entity objects as well as a central repository of entity meta-information (the domain model), each entity type must be defined, by calling {url-javadoc}/org/jminor/framework/domain/Domain.html#define-java.lang.String-org.jminor.framework.domain.Property...-[Domain.define] for each entity. The framework assumes the *entityId* is the table name, unless the *tableName* parameter is specified.

[source,java]
----
//public class Store continued

  public Store() {
    //Defining the entity that represents the table STORE.ADDRESS,
    //with a property for each column in the table, identified by their respective constants
    define(T_ADDRESS,
        Properties.primaryKeyProperty(ADDRESS_ID),
        Properties.columnProperty(ADDRESS_STREET, Types.VARCHAR, "Street"),
        Properties.columnProperty(ADDRESS_CITY, Types.VARCHAR, "City"))
        .setStringProvider(new StringProvider(ADDRESS_STREET).addText(" - ").addValue(ADDRESS_CITY)
    );

    //Defining the entity that represents the table STORE.CUSTOMER,
    //with a property for each column in the table, identified by their respective constants
    define(T_CUSTOMER,
        Properties.primaryKeyProperty(CUSTOMER_ID),
        Properties.columnProperty(CUSTOMER_FIRST_NAME, Types.VARCHAR, "First name").setDescription("The first name of the customer"),
        Properties.columnProperty(CUSTOMER_LAST_NAME, Types.VARCHAR, "Last name").setDescription("The last name of the customer"),
        Properties.foreignKeyProperty(CUSTOMER_ADDRESS_FK, "Address", T_ADDRESS,
            Properties.columnProperty(CUSTOMER_ADDRESS_ID)).setNullable(false),
        Properties.booleanProperty(CUSTOMER_IS_ACTIVE, Types.VARCHAR, "Is active", "true", "false").setDefaultValue(true),
        Properties.denormalizedProperty(CUSTOMER_CITY, T_ADDRESS,
            getProperty(T_ADDRESS, ADDRESS_CITY), "City"),
        Properties.transientProperty(CUSTOMER_TRANSIENT, Types.VARCHAR, "Transient"))
        .setStringProvider(new StringProvider(CUSTOMER_LAST_NAME).addText(", ").addValue(CUSTOMER_FIRST_NAME)
    );
  }
}
----

=== Entity.KeyProvider

The framework provides implementations for most common primary key generation strategies, sequence (with or without trigger) and auto-increment columns.

==== Auto-increment

This assumes the underlying primary key column is either an auto-increment column or is populated from a sequence using a trigger during insert.
For auto-increment columns the **valueSource** parameter should be the table name and for a sequence/trigger it should be the sequence name.

[source,java]
----
//Auto increment column in the 'store.customer' table
define(Store.T_CUSTOMER
    Properties.primaryKeyProperty(Store.CUSTOMER_ID)
    ...
).setKeyGenerator(automaticKeyGenerator("store.customer"));

//Trigger and sequence named 'store.customer_seq'
define(Store.T_CUSTOMER
    Properties.primaryKeyProperty(Store.CUSTOMER_ID)
    ...
).setKeyGenerator(automaticKeyGenerator("store.customer_seq"));
----

==== Sequence

When sequences are used without triggers the framework can fetch the value from a sequence before insert.

[source,java]
----
//Sequence named 'store.customer_seq' without a trigger
define(Store.T_CUSTOMER
    Properties.primaryKeyProperty(Store.CUSTOMER_ID)
    ...
).setKeyGenerator(sequenceKeyGenerator("store.customer_seq"));
----

==== Queried

The framework can select new primary key values from a query.

[source,java]
----
//Using a query returning the new value
define(Store.T_CUSTOMER
    Properties.primaryKeyProperty(Store.CUSTOMER_ID)
    ...
).setKeyGenerator(queriedKeyGenerator(
    "select new_id
     from store.id_values
     where table_name = 'store.customer'"));
----

==== Increment

The framework can automatically increment the primary key value by selecting the maximum value and add one, this is very simplistic, not transaction safe and is not recommended for use anywhere but the simplest demos.

[source,java]
----
define(Store.T_CUSTOMER
    Properties.primaryKeyProperty(Store.CUSTOMER_ID)
    ...
).setKeyGenerator(incrementKeyGenerator("store.customer_seq"));
----

==== Custom

You can provide a custom key generator strategy by implementing a {url-javadoc}/org/jminor/framework/domain/Entity.KeyGenerator.html[KeyGenerator].

=== Domain.StringProvider

The {url-javadoc}/org/jminor/framework/domain/Domain.StringProvider.html[Domain.StringProvider] class is for providing __toString()__ implementations for entities. This value is f. ex. used when entties are displayed in a ComboBox or as a foreign key values in table views.

[source,java]
----
define(Store.T_CUSTOMER
...
).setStringProvider(
    new StringProvider(Store.CUSTOMER_LAST_NAME)
        .addText(", ")
        .addValue(Store.CUSTOMER_FIRST_NAME)));
----

For more complex toString() implementations you can implement a custom {url-javadoc}/org/jminor/framework/domain/Entity.ToString.html[Entity.ToString].

[source,java]
----
define(Store.T_CUSTOMER
...
).setStringProvider(customer -> {
    StringBuilder builder =
       new StringBuilder(customer.getString(CUSTOMER_LASTNAME))
    .append(", ").append(customer.getString(CUSTOMER_LASTNAME));

    if (!customer.isValueNull(CUSTOMER_EMAIL)) {
        builder.append(" <")
        .append(customer.getString(CUSTOMER_EMAIL))
        .append(">");
    }

    return builder.toString();
});
----

=== Validation

Custom validation of Entities is done by implementing a {url-javadoc}/org/jminor/framework/domain/Domain.Validator.html[Domain.Validator].

The default *Entity.Validator* implementation provides basic range and null validation and can be extended to provide further validations. Note that validation is performed quite often so it should not perform expensive operations. Validation requiring database access f.ex. belongs in the application model or ui.

[source,java]
----
define("entityID",
...
).setValidator(new Domain.Validator() {
      @Override
    public void validate(Entity entity, Property property)
        throws ValidationException {
        super.validate(entity, property);

        Object value = entity.get(property);

        if (!isValid(value)) {
          throw new ValidationException(property.getPropertyId(),
              value, value + " is invalid");
        }
    }
});
----

{url-javadoc}/org/jminor/framework/domain/Entity.BackgroundColorProvider.html[Entity.BackgroundColorProvider]

Provides the background color for entity property cells when displayed in a table.

[source,java]
----
define("entityId",
...
).setBackgroundColorProvider(new Entity.BackgroundColorProvider() {
    public Object getBackgroundColor(Entity entity, Property property) {
        if (property.is("colorPropertyId") && entity.getString("colorPropertyId").equals("CYAN")) {
          return Color.CYAN;
        }

        return null;
    }
});
----

==== Examples

* <<{dir-tutorials}/empdept.adoc#domain-model, EmpDept domain model>>

=== Entities in action

Using the Entity class is rather straight forward.

[source,java]
----
//initialize the domain model by instantiating the domain model class
Store store = new Store();

//Initialize a database connection provider using the domain model, user credentials scott/tiger and application identifier TestApp
EntityConnectionProvider connectionProvider = EntityConnectionProviders.createConnectionProvider(
             store, new User("scott", "tiger".toCharArray()), "TestApp");

EntityConnection connection = connectionProvider.getConnection();

//Initialize a new entity representing the table STORE.ADDRESS
Entity address = store.entity(Store.T_ADDRESS);

//Set the value of the column ID to 42
address.put(Store.ADDRESS_ID, 42);
//Set the value of the column STREET to "Elm Street"
address.put(Store.ADDRESS_STREET, "Elm Street");
//Set the value of the column CITY to "Seattle"
address.put(Store.ADDRESS_CITY, "Seattle");

//Insert the address entity
connection.insert(Collections.singletonList(address));

//Initialize a new entity representing the table STORE.CUSTOMER
Entity customer = store.entity(Store.T_CUSTOMER);

//Set the value of the column ID to 42
customer.put(Store.CUSTOMER_ID, 42);
//Set the value of the column FIRST_NAME to John
customer.put(Store.CUSTOMER_FIRST_NAME, "John");
//Set the value of the column LAST_NAME to Doe
customer.put(Store.CUSTOMER_LAST_NAME, "Doe");
//Set the reference value ADDRESS
customer.put(Store.CUSTOMER_ADDRESS_FK, address);
//Set the value of the column IS_ACTIVE to true
customer.put(Store.CUSTOMER_IS_ACTIVE, true);

//Insert the entity representing the customer John Doe,
//receiving the primary key of the new record in a list as a return value
List<Entity.Key> key = connection.insert(Collections.singletonList(customer));

//Retrieve the ID value
Integer id = customer.getInteger(Store.CUSTOMER_ID);
//Retrieve the first name value
String firstName = customer.getString(Store.CUSTOMER_FIRST_NAME);

//Select the entity from the database by primary key
Entity customerByKey = connection.selectSingle(key.get(0));

//Select entities representing the table STORE.CUSTOMER by first name
List<Entity> entitiesByFirstName = connection.selectMany(Store.T_CUSTOMER, Store.CUSTOMER_FIRST_NAME, "Björn");
----

=== EntityGenerator

Using the EntityGenerator tool you can quickly generate a domain class containing the property Id constants for a given database schema as well as basic entity definitions.

The required command line arguments are: schema_name domain_class_package_name username password
Additionally you can add a comma seperated list of tables to include.

[source,bash]
----
java -Djminor.db.type=h2 -Djminor.db.embedded=true -Djminor.db.host=h2db/h2 -cp dist/jminor.jar:lib/h2-1.1.114.jar:lib/log4j-1.2.15.jar:lib/jcalendar-1.3.2.jar org.jminor.swing.framework.tools.ui.EntityGenerator PETSTORE org.petstore.domain.Petstore scott tiger
----

==== Examples

* <<{dir-tutorials}/empdept.adoc#domain-model, EmpDept domain model>>
* <<{dir-tutorials}/chinook.adoc#domain-model, Chinook domain model>>
* <<{dir-tutorials}/petstore.adoc#domain-model, Petstore domain model>>

== Domain Model Unit Testing

=== Introduction

To unit test the CRUD operations on the domain model extend {url-javadoc}/org/jminor/framework/domain/test/EntityTestUnit.html[EntityTestUnit].

The unit tests are run within a single transaction which is rolled back after the test finishes, so these tests are pretty much guaranteed to leave no junk data behind.

=== EntityTestUnit

The following methods all have default implementations which are based on randomly created property values, based on the constraints set in the domain model, override if the default ones are not working.

* {url-javadoc}/org/jminor/framework/domain/testing/EntityTestUnit.html#initializeReferenceEntity-java.lang.String-[initializeReferenceEntity] should initialize return an instance of the given entity type to use for a foreign key reference required for inserting the entity being tested.
* {url-javadoc}/org/jminor/framework/domain/testing/EntityTestUnit.html#initializeTestEntity-java.lang.String-[initializeTestEntity] should return a entity to use as basis for the unit test, that is, the entity that should be inserted, selected, updated and finally deleted.
* {url-javadoc}/org/jminor/framework/domain/testing/EntityTestUnit.html#modifyEntity-org.jminor.framework.domain.Entity-[modifyEntity] should simply leave the entity in a modified state so that it can be used for update test, since the db layer throws an exception if an unmodified entity is updated. If *modifyEntity* returns an unmodified entity, the update test is skipped.

To run the full CRUD test for a domain entity you need to call the __testEntity(String entityId)__ method with the id of the given entity as parameter. You can either create a single __testDomain()__ method and call the __testEntity__ method in turn for each entityId or create a single __testEntityName__ for each domain entity, as we do in the example below.

[source,java]
----
public class TestStore extends EntityTestUnit {

  public TestStore() {
    super(new Store());
  }

  @Test //a unit test method for the address entity
  public void address() throws Exception {
    //The testEntity method performs basic insert/select/update/delete tests for the given entity
    testEntity(Store.T_ADDRESS);
  }

  @Test //a unit test method for the customer entity
  public void customer() throws Exception {
    testEntity(Store.T_CUSTOMER);
  }

  @Override
  protected void initializeReferenceEntity(String entityId) throws Exception {
    //see if the currently running test requires an ADDRESS entity
    if (entityIDs.contains(Store.T_ADDRESS)) {
      Entity address = new Entity(Store.ADDRESS);
      address.put(Store.ADDRESS_ID, 21);
      address.put(Store.ADDRESS_STREET, "One Way");
      address.put(Store.ADDRESS_CITY, "Sin City");

      return address;
    }

    return super.initializeReferenceEntity(entityID);
  }

  @Override
  protected Entity initializeTestEntity(String entityID) {
    if (entityID.equals(Store.T_ADDRESS)) {
      //Initialize a entity representing the table STORE.ADDRESS,
      //which can be used for the testing
      Entity address = new Entity(Store.T_ADDRESS);
      address.put(Store.ADDRESS_ID, 42);
      address.put(Store.ADDRESS_STREET, "Street");
      address.put(Store.ADDRESS_CITY, "City");

      return address;
    }
    else if (entityID.equals(Store.T_CUSTOMER)) {
      //Initialize a entity representing the table STORE.CUSTOMER,
      //which can be used for the testing
      Entity customer = new Entity(Store.T_CUSTOMER);
      customer.put(Store.CUSTOMER_ID, 42);
      customer.put(Store.CUSTOMER_FIRST_NAME, "Robert");
      customer.put(Store.CUSTOMER_LAST_NAME, "Ford");
      //the getReferenceEntity() method returns the entity initialized in initializeReferenceEntities()
      customer.put(Store.CUSTOMER_ADDRESS_FK, getReferenceEntity(Store.T_ADDRESS));
      customer.put(Store.CUSTOMER_IS_ACTIVE, true);

      return customer;
    }

    return null;
  }

  @Override
  protected void modifyEntity(Entity testEntity) {
    if (testEntity.is(Store.T_ADDRESS)) {
      testEntity.put(Store.ADDRESS_STREET, "New Street");
      testEntity.put(Store.ADDRESS_CITY, "New City");
    }
    else if (testEntity.is(Store.T_CUSTOMER)) {
      //It is sufficient to change the value of a single property, but the more the merrier
      testEntity.put(Store.CUSTOMER_FIRST_NAME, "Jesse");
      testEntity.put(Store.CUSTOMER_LAST_NAME, "James");
      testEntity.put(Store.CUSTOMER_IS_ACTIVE, false);
    }
  }
}
----

==== Examples ====

* <<{dir-tutorials}/empdept.adoc#domain-model-unit-test, EmpDept domain model test>>
* <<{dir-tutorials}/chinook.adoc#domain-model-unit-test, Chinook domain model test>>
* <<{dir-tutorials}/petstore.adoc#domain-model-unit-test, Petstore domain model test>>

== EntityModel

=== Introduction

The {url-javadoc}/org/jminor/framework/model/EntityEditModel.html[EntityEditModel] interface defines the CRUD business logic used by the {url-javadoc}/org/jminor/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] class when entities are being edited, and must be defined for each entity requiring a CRUD user interface. The EntityEditModel works with a single entity instance, called the active entity, which can be set via the {url-javadoc}/org/jminor/framework/model/EntityEditModel.html#setEntity-org.jminor.framework.domain.Entity-[setEntity(Entity entity)] method and retrieved via {url-javadoc}/org/jminor/framework/model/EntityEditModel.html#getEntityCopy--[getEntityCopy()]. The EntityEditModel interface exposes a number of methods for manipulating as well as querying the property values of the active entity, via the {url-javadoc}/org/jminor/common/model/valuemap/ValueMapEditModel.html[ValueMapEditModel] interface which it extends

[source,java]
----
public class CustomerEditModel extends SwingEntityEditModel {
  public CustomerEditModel(EntityConnectionProvider connectionProvider) {
    super(Store.T_CUSTOMER, connectionProvider);
  }
}
----
[source,java]
----
public class AddressEditModel extends SwingEntityEditModel {
  public AddressModel(EntityConnectionProvider connectionProvider) {
    super(Store.T_ADDRESS, connectionProvider);
    addDetailModel(new CustomerModel(connectionProvider));
  }
}
----
[source,java]
----
//Initialize a database provider object using the credentials scott/tiger and application identifier TestApp
EntityConnectionProvider connectionProvider = EntityConnectionProviders.connectionProvider().setDomainClassName(Store.class.getName()).setUser(new User("scott", "tiger".toCharArray()).setClientTypeId("TestApp");

CustomerEditModel customerModel = new CustomerEditModel(connectionProvider);

customerModel.put(Store.CUSTOMER_ID, 42);
customerModel.put(Store.CUSTOMER_FIRST_NAME, "Björn");
customerModel.put(Store.CUSTOMER_LAST_NAME, "Sigurðsson");
customerModel.put(Store.CUSTOMER_IS_ACTIVE, true);

//inserts the active entity
List<Entity.Key> primaryKeys = customerModel.insert();

//select the customer we just inserted
Entity customer = connectionProvider.getConnection().selectSingle(primaryKeys.get(0));

//set the customer as the entity to edit in the edit model
customerModel.setEntity(customer);

//modify some property values
customerModel.put(Store.CUSTOMER_FIRST_NAME, "John");
customerModel.put(Store.CUSTOMER_LAST_NAME, "Doe");

//updates the active entity
customerModel.update();

//deletes the active entity
customerModel.delete();
----

=== Detail models

Directly adding a detail models is a trivial matter, the framework handles everything as long as the master/detail relationship is defined in the domain model.

[source,java]
----
addDetailModel(new CustomerModel(connectionProvider);
----

=== Table model

Each {url-javadoc}/org/jminor/framework/model/EntityModel.html[EntityModel] can contain a single {url-javadoc}/org/jminor/framework/model/EntityTableModel.html[EntityTableModel] instance. This table model can be created automatically by the //EntityModel// or supplied via a constructor argument in case of a specialized implementation.

[source,java]
----
static class CustomerTableModel extends SwingEntityTableModel {
  public CustomerTableModel(EntityConnectionProvider connectionProvider) {
    super(Store.T_CUSTOMER, connectionProvider);
  }
}

static class CustomerModel extends SwingEntityModel {
  public CustomerModel(EntityConnectionProvider connectionProvider) {
    super(new CustomerTableModel(connectionProvider));
  }
}
----

=== Edit model

Each {url-javadoc}/org/jminor/framework/model/EntityModel.html[EntityModel] contains a single {url-javadoc}/org/jminor/framework/model/EntityEditModel.html[EntityEditModel] instance. This edit model can be created automatically by the __EntityModel__ or supplied via a constructor argument in case of a specialized implementation.

[source,java]
----
static class CustomerEditModel extends SwingEntityEditModel {
  public CustomerEditModel(EntityConnectionProvider connectionProvider) {
    super(Store.T_CUSTOMER, connectionProvider);
  }
}

static class CustomerModel extends SwingEntityModel {
  public CustomerModel(EntityConnectionProvider connectionProvider) {
    super(new CustomerEditModel(connectionProvider));
  }
}
----

=== Event binding

The EntityModel, EntityEditModel and EntityTableModel classes expose a number of *addListener* methods.

The following example prints, to the standard output, all changes made to a given property as well as a message indicating that a refresh has started.
[source,java]
----
protected void bindEvents() {
  getTableModel().addRefreshStartedListener(new EventListener() {
    public void eventOccurred() {
      System.out.println("Refresh is about to start");
    }
  });
  getEditModel().addValueListener(EmpDept.EMPLOYEE_DEPARTMENT_FK, new ValueChangeListener() {
    protected void valueChanged(ValueChangeEvent event) {
      System.out.println("Property " + e.getKey() + " changed from " + e.getOldValue() + " to " + e.getNewValue());
    }
  });
}
----

=== Examples
* <<{dir-tutorials}/empdept.adoc#application-model-layer, EmpDept entity models>>

== EntityApplicationModel

=== Introduction

The EntityApplicationModel class serves as the base for the application. Its main purpose is to hold references to the root EntityModel instances used by the application.

When implementing this class you must provide a constructor taking a single EntityConnectionProvider instance as argument, as seen below.

[source,java]
----
public class StoreApplicationModel extends SwingEntityApplicationModel {

  public StoreApplicationModel(EntityConnectionProvider connectionProvider) {
    super(connectionProvider);
    addEntityModel(new CustomerModel(connectionProvider));
  }
}
----

== Application load testing

=== Introduction

The application load testing harness is used to see how your application, server and database handle multiple concurrent users. This is done by extending the abstract class {url-javadoc}/org/jminor/swing/framework/tools/EntityLoadTestModel.html[EntityLoadTestModel].

[source,java]
----
public class StoreLoadTest extends EntityLoadTestModel<StoreAppModel> {

  private static final Store STORE = new Store();

  public StoreLoadTest() {
    super(new User("scott", "tiger".toCharArray()));
  }

  @Override
  protected void performWork(StoreAppModel application) {
    try {
      EntityModel customerModel = application.getMainApplicationModels().iterator().next();
      customerModel.getTableModel().clearSelection();
      customerModel.refresh();
    }
    catch (Exception e) {
      e.printStackTrace();
    }
  }

  @Override
  protected StoreAppModel initializeApplication() {
    return new StoreAppModel(new RemoteEntityConnectionProvider(STORE, getUser(), UUID.randomUUID(), getClass().getSimpleName()));
  }

  public static void main(String[] args) {
    new LoadTestPanel(new StoreLoadTest()).showFrame();
  }
}
----

=== Examples

* <<{dir-tutorials}/empdept.adoc#application-load-test, EmpDept application load test>>
* <<{dir-tutorials}/chinook.adoc#application-load-test, Chinook application load test>>
* <<{dir-tutorials}/petstore.adoc#application-load-test, Petstore application load test>>

== EntityPanel

=== Introduction

The {url-javadoc}/org/jminor/swing/framework/ui/EntityPanel.html[EntityPanel] is the base UI class for working with entity instances. It usually consists of an {url-javadoc}/org/jminor/swing/framework/ui/EntityTablePanel.html[EntityTablePanel], an {url-javadoc}/org/jminor/swing/framework/ui/EntityEditPanel.html[EntityEditPanel], which contains the controls (text fields, combo boxes and such) for editing an entity instance and a set of detail panels representing the entities having a master/detail relationship with the underlying entity.

==== EntityEditPanel

When instantiating an EntityPanel you can supply an EntityEditPanel instance as a parameter. When implementing an EntityEditPanel you must implement the __initializeUI()__ method, in which you should initialize the edit panel UI. The EntityEditPanel class exposes methods for creating input components and binding them with the underlying EntityEditModel instance.
[source,java]
----
public class CustomerEditPanel extends EntityEditPanel {

  public CustomerEditPanel(SwingEntityEditModel editModel) {
    super(editModel);
  }

  @Override
  protected void initializeUI() {
    //the firstName field should receive the focus whenever the panel is initialized
    setInitialFocusProperty(Store.CUSTOMER_FIRST_NAME);

    setLayout(new GridLayout(4,1));
    createTextField(Store.CUSTOMER_FIRST_NAME);
    createTextField(Store.CUSTOMER_LAST_NAME);
    createForeignKeyComboBox(Store.CUSTOMER_ADDRESS_FK);
    createCheckBox(Store.CUSTOMER_IS_ACTIVE, null, false);

    //the createControlPanel method creates a panel containing the
    //component associated with the property as well as a JLabel with the
    //property caption as defined in the domain model
    addPropertyPanel(Store.CUSTOMER_FIRST_NAME);
    addPropertyPanel(Store.CUSTOMER_LAST_NAME);
    addPropertyPanel(Store.CUSTOMER_ADDRESS_FK);
    addPropertyPanel(Store.CUSTOMER_IS_ACTIVE);
  }
}
----

=== Detail panels

Adding a detail panel is done with a single method call, but note that the underlying EntityModel must contain the correct detail model for the detail panel, in this case a *CustomerModel* instance, see <<Detail models, detail models>>.
[source,java]
----
public TestPanel extends EntityPanel {
  public TestPanel(EntityModel model) {
    super("caption", model);
    addDetailPanel(new CustomerPanel(model.getDetailModel(CustomerModel.class)));
  }
}
----

=== Custom actions
The action mechanism used throughout the JMinor framework is based on the {url-javadoc}/org/jminor/swing/common/ui/control/Control.html[Control] class and its subclasses and the {url-javadoc}/org/jminor/swing/common/ui/control/ControlSet.html[ControlSet] class which, as the name suggests, represents a set of controls. There are two static utility classes for creating and presenting controls, {url-javadoc}/org/jminor/swing/common/ui/control/Controls.html[Controls] and {url-javadoc}/org/jminor/swing/common/ui/control/ControlProvider.html[ControlProvider] respectively.

=== Controls

Provides methods for initializing MethodControl objects as well as ToggleBeanValueLink objects.

[source,java]
----
public class MethodControlTest {

  public void printString() {
    System.out.println("printing a string");
  }

  public static void main(String[] args) {
    MethodControlTest testObj = new MethodControlTest();
    MethodControl control = Controls.methodControl(testObj, "printString", "Print string");
    //calls testObj.printString()
    control.actionPerformed(new ActionEvent(testObj, 0, "actionPerformed"));
  }
}
----

=== ControlProvider ===

The ControlProvider class provides static factory methods for creating UI components based on Control objects.

[source,java]
----
public class MethodControlTest {

  public void printString() {
    System.out.println("printing a string");
  }

  public static void main(String[] args) {
    MethodControlTest testObj = new MethodControlTest();
    MethodControl control = Controlsy.methodControl(testObj, "printString", "Print string");
    JButton printButton = ControlProvider.createButton(control);

    //calls testObj.printString()
    printButton.doClick();
  }
}
----

=== Adding a print action ===

The most common place to add a custom control is the table popup menu, f.ex. an action for printing reports. The table popup menu is based on the ControlSet returned by the //getTablePopupControlSet()// method in the EntityPanel class which in turn uses the ControlSet returned by the //getPrintControls()// method in the same class for constructing the print popup submenu. So, to add a custom print action you override the //getPrintControls()// method and return a ControlSet containing the action.
[source,java]
----
@Override
public ControlSet getPrintControls() {
  ControlSet printControls = new ControlSet("Print");
  //creates a MethodControl which calls the viewReport method in this class on activation
  printControls.add(Controls.methodControl(this, "viewReport", "Report"));
  //add the default print table control as well
  printControls.add(getControl(PRINT));

  return printControls;
}
----

== EntityApplicationPanel

=== Examples

* <<{dir-tutorials}/empdept.adoc#main-application-panel, EmpDept application panel>>
* <<{dir-tutorials}/chinook.adoc#main-application-panel, Chinook application panel>>
* <<{dir-tutorials}/petstore.adoc#main-application-panel, Petstore application panel>>

== Reporting with JasperReports

=== Introduction

JMinor uses a plugin oriented approach to report viewing, and provides an implementation for JasperReports and NextReports.

With the JMinor JasperReports plugin you can either design your report based on a SQL query in which case you use the JasperReportsWrapper class, which facilitates the report being filled using the active database connection or you can design your report around the JRDataSource implementation provided by the {url-javadoc}/org/jminor/framework/plugins/jasperreports/model/JasperReportsEntityDataSource.html[JasperReportsEntityDataSource] class, which is constructed around an iterator.

The EntityPanel class provides straight forward methods for viewing reports using methods provided by the EntityModel class for filling them. Both these classes rely on static utility classes for doing the actual work so you are not bound by the EntityPanel and EntityModel classes for viewing reports, they simply provide the easiest way of doing so.

=== JDBC Reports

Using a report based on a SQL query, {url-javadoc}/org/jminor/framework/plugins/jasperreports/model/JasperReportsWrapper.html[JasperReportsWrapper] and {url-javadoc}/org/jminor/framework/plugins/jasperreports/ui/JasperReportsUIWrapper.html[JasperReportsUIWrapper] is the simplest way of viewing a report using JMinor, just add a method similar to the one below to a EntityPanel subclass. You can then create an action calling that method and put it in for example the table popup menu as described in the <<Adding a print action, adding a print action>> section.

[source,java]
----
public void viewCustomerReport() throws Exception {
  List<Entity> selectedCustomers = getModel().getTableModel().getSelectedItems();
  if (selectedCustomers.getSize() == 0)
    return;

  String reportPath = System.getProperty(Configuration.REPORT_PATH) + "/customer_report.jasper";
  Collection<Object> customerIds = Entities.getValues(selectedCustomers, Store.CUSTOMER_ID);
  Map<String, Object> reportParameters = new HashMap<String, Object>();
  reportParameters.put("CUSTOMER_IDS", customerIds);

  viewJdbcReport(new JasperReportsWrapper(reportPath, reportParameters), new JasperReportsUIWrapper(),  "Customer Report");
}
----

=== JRDataSource Reports

The JRDataSource implementation provided by the JasperReportsEntityDataSource simply iterates through the iterator received via the constructor and retrieves the field values from the underlying entities. For this to work you must design the report using field names that correspond to the property IDs, so using the Store domain example from above the fields in a report showing the available items would have to be named 'name', 'is_active', 'category_code' etc. If you need to use a field that does not correspond to a property in the underlying entity, f.ex. when combining two fields into one you must override the __getFieldValue()__ method and handle that special case there.

[source,java]
----
@Override
public Object getFieldValue(JRField jrField) {
  if (jrField.getName().equals("name_category_code") {
    Entity currentRecord = getCurrentEntity();

    return currentRecord.getString(Store.ITEM_NAME) + " - "
             + currentRecord.getAsString(Store.ITEM_CATEGORY_CODE);
  }

  return super.getFieldValue(jrField);
}
----

The way you view the report is just like in the jdbc report example above except you use the __viewReport()__ method instead of __viewJdbcReport()__.

=== Examples

* <<{dir-tutorials}/empdept.adoc#application-ui-layer, EmpDept UI layer>>