create schema store;

create table store.category (
 id integer generated by default as identity,
 name varchar(25) not null,
 insert_time timestamp not null default now(),
 insert_user varchar(20) not null default user(),
 primary key (id)
);

create table store.item (
 id integer generated by default as identity,
 category_id integer not null,
 name varchar(25) not null,
 price decimal(8,2),
 insert_time timestamp not null default now(),
 insert_user varchar(20) not null default user(),
 primary key (id),
 foreign key (category_id) references store.category(id)
);

create user if not exists scott password 'tiger';
alter user scott admin true;

create schema empty;