= Common Reactive
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

[#_reactive_classes]
== Reactive classes

Three common classes used throughout the framework are {url-javadoc}{common-reactive}/is/codion/common/reactive/event/Event.html[Event], {url-javadoc}{common-reactive}/is/codion/common/reactive/state/State.html[State] and {url-javadoc}{common-reactive}/is/codion/common/reactive/value/Value.html[Value] and their respective observers {url-javadoc}{common-reactive}/is/codion/common/reactive/observer/Observer.html[Observer] and {url-javadoc}{common-reactive}/is/codion/common/reactive/state/ObservableState.html[ObservableState].

NOTE: Not all available methods are included in the diagrams below, see javadocs for details.

[#_event]
=== Event

[plantuml,event-diagram,svg,align=center]
-------------------------------------------
skinparam genericDisplay old

interface Event<T> {
    +void run()
    +void accept(T data)
    +Observer<T> observer()
    +void addListener(Runnable listener)
    +void addConsumer(Consumer<? super T> consumer)
}

interface Observer<T> {
    +void addListener(Runnable listener)
    +void addConsumer(Consumer<? super T> consumer)
}

interface Runnable {}

interface Consumer<T> {}

Runnable <-- Event
Consumer <-- Event
Observer *-- Event
-------------------------------------------

The {url-javadoc}{common-reactive}/is/codion/common/reactive/event/Event.html[Event] class is a synchronous event implementation used throughout the framework.
Classes typically expose observers for their events via public accessors.
Events are triggered by calling the *run* method in case no data is associated with the event or *accept* in case data should be propogated to consumers.

The associated {url-javadoc}{common-reactive}/is/codion/common/reactive/observer/Observer.html[Observer] instance can not trigger the event and can be safely passed around.

Event listeners must implement either https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runnable.html[Runnable] or https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/function/Consumer.html[Consumer], depending on whether they are interested in the data associated with the event.

NOTE: Both listeners and consumer are notified each time the event is triggered, regardless of whether *run* or *accept* is used, listeners and consumers are notified in the order they were added.

Events are instantiated via factory methods in the {url-javadoc}{common-reactive}/is/codion/common/reactive/event/Event.html[Event] class.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=event]
----

[#_observer]
=== Observer

The *Observer* class provides a way to add conditional listeners via {url-javadoc}{common-reactive}/is/codion/common/reactive/observer/Observer.html#when(java.lang.Object)[Observer.when()].

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=observer]
----

[#_value]
=== Value

[plantuml,value-diagram,svg,align=center]
-------------------------------------------
skinparam genericDisplay old

interface Value<T> {
    +void set(T)
    +void link(Value<T> value)
    +Observable<T> observable()
    +void addListener(Runnable listener)
    +void addConsumer(Consumer<? super T> consumer)
}

interface Observable<T> {
    +T get()
    +void addListener(Runnable listener)
    +void addConsumer(Consumer<? super T> consumer)
}

interface Observer<T> {
    +void addListener(Runnable listener)
    +void addConsumer(Consumer<? super T> consumer)
}

Observable <-- Value
Observer <-- Observable
-------------------------------------------

A {url-javadoc}{common-reactive}/is/codion/common/reactive/value/Value.html[Value] wraps a value and provides a change observer.

Values are instantiated via factory methods in the {url-javadoc}{common-reactive}/is/codion/common/reactive/value/Value.html[Value] class.

Values can be linked so that changes in one are reflected in the other.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=value]
----

Values can be non-nullable if a _nullValue_ is specified when the value is initialized.
Null is then translated to the _nullValue_ when set.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=nullValue]
----

[#_valuecollection]
==== ValueCollection

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=valueCollection]
----

[#_state]
=== State

[plantuml,state-diagram,svg,align=center]
-------------------------------------------
skinparam genericDisplay old

interface State {
    +void set(Boolean value)
    +void toggle()
    +ObservableState observable()
    +Value<Boolean> value()
}

interface ObservableState {
    +boolean is()
    +ObservableState not()
}

State -|> ObservableState
-------------------------------------------

The {url-javadoc}{common-reactive}/is/codion/common/reactive/state/State.html[State] class encapsulates a boolean state and provides read only access and a change observer via {url-javadoc}{common-reactive}/is/codion/common/reactive/state/ObservableState.html[ObservableState].
A *State* implements *Value<Boolean>* and is non-nullable with null translating to false.

States are instantiated via factory methods in the {url-javadoc}{common-reactive}/is/codion/common/reactive/state/State.html[State] class.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=state]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=observers]
----

Any *Action* or *JComponent* enabled status can be linked to a *State* instance via the *Utilities.enabled()* method.

[#_state_composition]
==== State composition
[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=stateComposition]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=action]
----

Controls can also be linked to a *State* instance.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/EventStateValue.java[tags=control]
----

NOTE: When a State or Event is linked to a Swing component, for example its enabled state, all state changes must happen on the Event Dispatch Thread.