= Common Core
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

== Core classes

Three common classes used throughout the framework are the {url-javadoc}{common-core}/is/codion/common/event/Event.html[Event], {url-javadoc}{common-core}/is/codion/common/state/State.html[State] and {url-javadoc}{common-core}/is/codion/common/value/Value.html[Value] classes, their respective observers {url-javadoc}{common-core}/is/codion/common/event/EventObserver.html[EventObserver] and {url-javadoc}{common-core}/is/codion/common/state/StateObserver.html[StateObserver] and listeners {url-javadoc}{common-core}/is/codion/common/event/EventListener.html[EventListener] and {url-javadoc}{common-core}/is/codion/common/event/EventDataListener.html[EventDataListener].

=== Event

The {url-javadoc}{common-core}/is/codion/common/event/Event.html[Event] class is a simple synchronous event implementation used throughout the framework. Classes typically publish their events via public *addListener* methods. Events are triggered by calling the *onEvent()* method, with or without a *data* parameter.

Events are instantiated via factory methods in the {url-javadoc}{common-core}/is/codion/common/event/Event.html[Event] class.

To listen to Events you use the {url-javadoc}{common-core}/is/codion/common/event/EventListener.html[EventListener] or {url-javadoc}{common-core}/is/codion/common/event/EventDataListener.html[EventDataListener] interfaces.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/EventStateValue.java[tags=event]
----

=== State

The {url-javadoc}{common-core}/is/codion/common/state/State.html[State] class encapsulates a boolean state and provides read only access and a change observer via {url-javadoc}{common-core}/is/codion/common/state/StateObserver.html[StateObserver].

States are instantiated via factory methods in the {url-javadoc}{common-core}/is/codion/common/state/State.html[State] class.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/EventStateValue.java[tags=state]
----

Any *Action* object can be linked to a *State* object via the *Components.linkToEnabledState* method, where the action's *enabled* status is updated according to the state.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/EventStateValue.java[tags=action]
----

=== Value

The {url-javadoc}{common-core}/is/codion/common/value/Value.html[Value] interface is a value wrapper with a change listener.

Values are instantiated via factory methods in the {url-javadoc}{common-core}/is/codion/common/value/Value.html[Value] class.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/EventStateValue.java[tags=value]
----