[#_progressworker]
= ProgressWorker
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

{url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.html[ProgressWorker] provides a fluent API for constructing background task workers for a variety of task types.

NOTE: ProgressWorker instances can **not** be reused. Tasks, on the other hand, can be made stateful and reusable if required.

== {url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.Task.html[Task]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=taskWorker]
----

== {url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.TaskHandler.html[TaskHandler]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=taskHandler]
----

== {url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.ResultTask.html[ResultTask]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=resultTaskWorker]
----

== {url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.ResultTaskHandler.html[ResultTaskHandler]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=resultTaskHandler]
----

== {url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.ProgressTask.html[ProgressTask]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=progressTaskWorker]
----

== {url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.ProgressTaskHandler.html[ProgressTaskHandler]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=progressTaskHandler]
----

== {url-javadoc}{common-model}/is/codion/common/model/worker/ProgressWorker.ProgressResultTask.html[ProgressResultTask]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=progressResultWorker]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/model/ProgressWorkerDemo.java[tags=progressResultTask1;progressResultTask2]
----