= Common Database
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

The core JDBC related classes.

== Common classes

Two common classes used throughout the framework are the {url-javadoc}{common-db}/is/codion/common/db/database/Database.html[Database] and {url-javadoc}{common-db}/is/codion/common/db/connection/DatabaseConnection.html[DatabaseConnection] classes.

=== Database

The {url-javadoc}{common-db}/is/codion/common/db/database/Database.html[Database] class represents a DBMS instance and provides connections to that instance.

There are multiple ways to aquire a Database instance.

* By specifying a JDBC url via a system property.
[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/db/Demo.java[tags=systemProperty]
----

* By setting the JDBC url configuration value directly.
[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/db/Demo.java[tags=configuration]
----

* By instantiating a DatabaseFactory directly.
[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/db/Demo.java[tags=url]
----

* By instantiating a DBMS specific DatabaseFactory directly.
[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/db/Demo.java[tags=factory]
----

A Database instance provides *java.sql.Connection* instances via the *createConnection* method.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/db/Demo.java[tags=connection]
----

=== DatabaseConnection

The {url-javadoc}{common-db}/is/codion/common/db/connection/DatabaseConnection.html[DatabaseConnection] class represents a connection to a database instance and is a wrapper around an actual *java.sql.Connection* instance.

A *DatabaseConnection* instance is created via the *databaseConnection* factory methods.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/common/db/Demo.java[tags=databaseConnection]
----