= EntityConnectionProvider
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:url-javadoc: link:../api

An {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnectionProvider.html[EntityConnectionProvider] is a factory and lifecycle manager for EntityConnection instances — ensuring reliable access to the database regardless of protocol (JDBC, RMI, HTTP).

In most cases *EntityConnections* are retrieved from a {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnectionProvider.html[EntityConnectionProvider], which is responsible for establishing a connection to the underlying database.
The *EntityConnectionProvider* class is central to the framework and is a common constructor parameter in classes requiring database access.

Each call to *connection()* returns the current active connection. If the existing connection is invalid (e.g., due to network failure or server restart), a new one is transparently established. If the *EntityConnectionProvider* is unable to connect to the underlying database or server, *connection()* throws an exception.

IMPORTANT: Do NOT cache the *EntityConnection* instance. The instance returned by *connection()* should only be kept for a short time, such as a local variable or method parameter since it can become invalid and thereby unusable. Always use *connection()* to make sure you have a healthy *EntityConnection*.

== LocalEntityConnectionProvider

{url-javadoc}{framework-db-local}/is/codion/framework/db/local/LocalEntityConnectionProvider.html[LocalEntityConnectionProvider]

Provides a connection based on a local JDBC connection.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/EntityConnectionProviderDemo.java[tags=local]
----

== RemoteEntityConnectionProvider

{url-javadoc}{framework-db-rmi}/is/codion/framework/db/rmi/RemoteEntityConnectionProvider.html[RemoteEntityConnectionProvider]

Provides a connection based on a remote RMI connection.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/EntityConnectionProviderDemo.java[tags=remote]
----

== HttpEntityConnectionProvider

{url-javadoc}{framework-db-http}/is/codion/framework/db/http/HttpEntityConnectionProvider.html[HttpEntityConnectionProvider]

Provides a connection based on a remote HTTP connection.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/EntityConnectionProviderDemo.java[tags=http]
----
