= Conditions
:dir-tutorials: ../tutorials
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:url-javadoc: link:../api

The {url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Conditions.html[Conditions] class is a factory for conditions, used when querying entities.

The <<{dir-tutorials}/chinook.adoc#_domain, Chinook domain model>> is used in the examples below.

== Condition

{url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Condition.html[Condition] represents a where clause for an entity type.

== Condition.Combination

{url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Condition.Combination.html[Condition.Combination] represents a combination of Conditions, which are either AND'ed or OR'ed together. These can be nested and combined with other condition combinations.

== SelectCondition

{url-javadoc}{framework-db-core}/is/codion/framework/db/condition/SelectCondition.html[SelectCondition] represents a where clause for an entity type specifically for selecting.

== UpdateCondition

{url-javadoc}{framework-db-core}/is/codion/framework/db/condition/UpdateCondition.html[UpdateCondition] represents a where clause and values for updating one or more entities.