= EntityEditModel
:dir-source: ../../../../../demos/manual/src/main/java
:dir-tutorials: ../tutorials
:url-javadoc: link:../api

The {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] interface defines the CRUD business logic used by the {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] class when entities are being edited. The EntityEditModel works with a single entity instance, called the active entity, which can be set via the {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html#setEntity{opar}is.codion.framework.domain.entity.Entity{cpar}[setEntity(Entity entity)] method and retrieved via {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html#getEntityCopy{opar}{cpar}[getEntityCopy()]. The EntityEditModel interface exposes a number of methods for manipulating as well as querying the property values of the active entity.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerEditModel.java[tags=customerEditModel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/Misc.java[tags=editModel]
----