= Conditions
:dir-tutorials: ../tutorials
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:url-javadoc: link:../api

The <<{dir-tutorials}/chinook/chinook.adoc#_domain_model, Chinook domain model>> is used in the examples below.

== Criteria

*{url-javadoc}{framework-db-core}/is/codion/framework/db/criteria/Criteria.html[Criteria]*::
Represents an element of a where condition and contains factory methods for creating *Criteria* instances.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/CriteriaDemo.java[tags=criteria]
----

*{url-javadoc}{framework-db-core}/is/codion/framework/db/criteria/Criteria.Combination.html[Criteria.Combination]*::
Extends *Critiera* and represents a combination of *Criteria* instances, which are combined using either *AND* or *OR*. These can be nested and combined with other criteria combinations.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/CriteriaDemo.java[tags=combination]
----

== Select

*{url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Select.html[Select]*::
Represents a where clause as well as extended configuration specifically for selecting, such as *orderBy*, *limit*, *offset* and *fetchDepth*. {url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Select.html#where[Select.where] returns a {url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Select.Builder.html[Select.Builder] instance for further configuration.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/CriteriaDemo.java[tags=select]
----

== Update

*{url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Update.html[Update]*::
Represents a where clause as well as the columns values for updating one or more entities. {url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Update.html#where[Update.where] returns a {url-javadoc}{framework-db-core}/is/codion/framework/db/condition/Update.Builder.html[Update.Builder] instance for specifying the columns to update and their respective values.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/CriteriaDemo.java[tags=update]
----