[#_entitymodel]
= EntityModel
:dir-source: ../../../../../demos/manual/src/main/java
:dir-tutorials: ../tutorials
:url-javadoc: link:../api

The application model layer consists of the {url-javadoc}{framework-model}/is/codion/framework/model/EntityModel.html[EntityModel] class and its associates; the {url-javadoc}{framework-model}/is/codion/framework/model/EntityTableModel.html[EntityTableModel], which provides a table representation of entities and the {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] which provides the CRUD operations.

An *EntityEntityModel* always contains an *EntityEditModel* instance and usually contains a *EntityTableModel* as well.

[plantuml, entity-model-diagram, svg, align=center]
-------------------------------------------
interface EntityModel {
    +EntityEditModel editModel()
    +EntityTableModel tableModel()
}

interface EntityTableModel {
    +EntityEditModel editModel()
}

interface EntityEditModel {}

EntityModel --o EntityTableModel
EntityTableModel --o EntityEditModel
-------------------------------------------

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/AddressModel.java[tags=addressModel]
----

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerModel.java[tags=customerModel]
----

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerAddressModel.java[tags=customerAddressModel]
----

== EntityTableModel

Every *EntityTableModel* contains a *EntityEditModel* instance. A default edit model implementation is created automatically by the *EntityTableModel* if one is not supplied via a constructor argument.

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerTableModel.java[tags=customerTableModel]
----

== EntityEditModel

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerEditModel.java[tags=customerEditModel]
----

[#_detail_models]
== Detail models

An *EntityModel* can contain one or more detail models, usually based on foreign key relationships.

[plantuml, entity-detail-model-diagram, svg, align=center]
-------------------------------------------
interface EntityModel {
    +Collection<EntityModel> detailModels()
}

EntityModel --o EntityModel
-------------------------------------------

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/StoreApplicationModel.java[tags=storeAppModel]
----

[#_event_binding]
== Event binding

The model layer classes expose a number of <<manual.adoc#_core_classes, *Event* and *State* observers>> as well as *addListener* methods.

* <<{dir-tutorials}/empdept/empdept.adoc#_model, EmpDept entity models>>

The example below prints, to the standard output, all changes made to a given attribute value as well as a message indicating that a table refresh has started.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerModel.java[tags=customerModel]
----

== Examples
* <<{dir-tutorials}/empdept/empdept.adoc#_model, EmpDept entity models>>