[#_reporting_with_jasperreports]
= Reporting with JasperReports
:dir-source: ../../../../../demos/manual/src/main/java
:dir-tutorials: ../tutorials
:url-javadoc: link:../api

Codion uses a plugin oriented approach to report viewing and provides an implementation for https://github.com/TIBCOSoftware/jasperreports[JasperReports].

With the Codion JasperReports plugin you can either design your report based on an SQL query in which case you use the JRReport class, which facilitates the report being filled using the active database connection, or you can design your report around the JRDataSource implementation provided by the {url-javadoc}{plugin-jasperreports}/is/codion/plugin/jasperreports/JasperReportsDataSource.html[JasperReportsDataSource] class, which is constructed around an iterator.

== JDBC Reports

Using a report based on an SQL query is the simplest way of viewing a report using Codion, just add a method similar to the one below to a *EntityTablePanel* subclass. You can then create an action calling that method and put it in for example the table popup menu as described in the <<framework-entity-table-panel.adoc#_adding_a_print_action, adding a print action>> section.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/ui/CustomerTablePanel.java[tags=customerTablePanel]
----

== JRDataSource Reports

The JRDataSource implementation provided by the JasperReportsDataSource simply iterates through the iterator received via the constructor and retrieves the field values from the underlying entities. The easiest way to make this work is to design the report using field names that correspond to the attribute names, so using the Store domain example from above the fields in a report showing the available items would have to be named 'name', 'active', 'category_code' etc.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/Misc.java[tags=jasperReportDataSource]
----

== Examples

* <<{dir-tutorials}/empdept/empdept.adoc#_ui, EmpDept UI layer>>
* <<{dir-tutorials}/chinook/chinook.adoc#_ui, Chinook UI layer>>
* <<{dir-tutorials}/world/world.adoc#_ui, World UI layer>>