[#_entitymodel]
= EntityModel
:dir-source: ../../../../../demos/manual/src/main/java
:dir-tutorials: ../tutorials
:url-javadoc: link:../api

The {url-javadoc}{framework-model}/is/codion/framework/model/EntityModel.html[EntityModel] class links together and coordinates between a {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] and a {url-javadoc}{framework-model}/is/codion/framework/model/EntityTableModel.html[EntityTableModel], where the *EntityEditModel* handles CRUD operations and the *EntityTableModel* provides a table representation of the underlying entities.

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/AddressModel.java[tags=addressModel]
----

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerModel.java[tags=customerModel]
----

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerAddressModel.java[tags=customerAddressModel]
----

== Edit model

Each {url-javadoc}{framework-model}/is/codion/framework/model/EntityModel.html[EntityModel] contains a single {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] instance. This edit model can be created automatically by the *EntityModel* or supplied via a constructor argument in case of a custom implementation.

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerEditModel.java[tags=customerEditModel]
----

== Table model

Each {url-javadoc}{framework-model}/is/codion/framework/model/EntityModel.html[EntityModel] can contain a single {url-javadoc}{framework-model}/is/codion/framework/model/EntityTableModel.html[EntityTableModel] instance. This table model can be created automatically by the *EntityModel* or supplied via a constructor argument in case of a specialized implementation.

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerTableModel.java[tags=customerTableModel]
----

[#_detail_models]
== Detail models

Detail models can be added to a model, this relies on a foreign key reference between the entities involved.

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/StoreApplicationModel.java[tags=storeAppModel]
----

[#_event_binding]
== Event binding

The EntityModel, EntityEditModel and EntityTableModel classes expose a number of *addListener* methods.

The following example prints, to the standard output, all changes made to a given property as well as a message indicating that a refresh has started.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/model/CustomerModel.java[tags=bindEvents]
----

== Examples
* <<{dir-tutorials}/empdept.adoc#_model, EmpDept entity models>>