= Domain Model
:dir-tutorials: ../tutorials
:dir-source: ../../../../../demos/manual/src/main/java
:dir-petstore-source: ../../../../../demos/petstore/src/main/java
:dir-world-source: ../../../../../demos/world/src/main/java
:url-javadoc: link:../api

The domain model is based around five classes; {url-javadoc}/is/codion/framework/domain/entity/Entity.html[Entity], which represents a row in a table, {url-javadoc}/is/codion/framework/domain/entity/EntityIdentity.html[EntityIdentity], which identifies an entity type, {url-javadoc}/is/codion/framework/domain/entity/EntityDefinition.html[EntityDefinition] which contains the meta-data for each entity type (properties, data types and such), {url-javadoc}/is/codion/framework/domain/property/Attribute.html[Attribute], which represents column types and {url-javadoc}/is/codion/framework/domain/property/Property.html[Property], which represents columns. Domain models must extend the
{url-javadoc}/is/codion/framework/domain/Domain.html[Domain] class, which in turn provides a {url-javadoc}/is/codion/framework/domain/entity/Entities.html[Entities] instance via {url-javadoc}/is/codion/framework/domain/Domain.html#getEntities[getEntities()], which serves as a container for the domain entity definitions and as a factory for *Entity* and *Entity.Key* instances.

== Entities

The *Entity* class is a map like structure, which maps column values to the attribute representing each column. Each table is represented by a entity type, identified by a *entityId*, a EntityIdentity constant unique within the domain.

NOTE: Typically, the *entityId* name contains the underlying table name, but you can use whatever identifying string you want and specify the table name via a *tableName* parameter when defining the entity.

== Attributes

Each column in a table is associated with a {url-javadoc}/is/codion/framework/domain/property/Attribute.html[Attribute] constant, which has a name and denotes the value type. The {url-javadoc}/is/codion/framework/domain/property/Attributes.html[Attributes] class provides factory methods for constructing Attribute objects and is usually statically imported, as will be assumed in the following examples.

NOTE: Typically, the *attribute* name is the underlying column name, but as with the *entityId* you can use whatever value you want and specify the column name via the *columnName()* method when instantiating the associated Property.

=== Supported data types

The following data types are supported:

* Integer (java.sql.Types.INTEGER)
* Double (java.sql.Types.DOUBLE)
* Long (java.sql.Types.BIGINT)
* BigDecimal (java.sql.Types.DECIMAL)
* LocalDateTime (java.sql.Types.TIMESTAMP)
* LocalDate (java.sql.Types.DATE)
* LocalTime (java.sql.Types.TIME)
* String (java.sql.Types.VARCHAR)
* Boolean (java.sql.Types.BOOLEAN)
* Character (java.sql.Types.CHAR)
* Blob (java.sql.Types.BLOB)

== Properties

Each column is represented by the {url-javadoc}/is/codion/framework/domain/property/Property.html[Property] class or one of its subclasses. The {url-javadoc}/is/codion/framework/domain/property/Properties.html[Properties] class provides factory methods for constructing Property objects and is usually statically imported, as will be assumed in the following examples. Each Property is based on an Attribute, unique within the Entity.

=== Example

String constants for the Entities and Attribute constants for the properties in the World demo, here the *entityIds* have a *T_* prefix (for *Type* or *Table*) whereas the *attributes* are prefixed by their respective table names.

[source,java]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=entityIdsAndAttributes]
----

=== Property

{url-javadoc}/is/codion/framework/domain/property/Property.html[Property] and its subclasses are used to represent entity properties, these can be transient or based on table columns.

=== Primary key

It is recommended that entities have a primary key defined, that is, one or more column properties representing a unique column combination.

The only requirement is that the primary key properties represent a unique column combination for the underlying table, it does not have to correspond to an actual table primary key, although that is of course preferable. The framework does not enforce uniqueness for these properties, so a unique or primary key on the corresponding table columns is strongly recommended.

If no primary key properties are specified the entity is somewhat restricted, it can not be referenced via a foreign key and equals() does not work (since it is based on the primary key). You can still use the *Entity.valuesEqual()* method to check if all values are equal in two entities.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=primaryKey]
----

In case of composite primary keys you create a ColumnProperty and specify the primary key index. Note that in the example below the column with primary key index 0 is a foreign key column and wrapped in a foreignKeyProperty(), which are discussed a bit later.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=compositePrimaryKey]
----

=== ColumnProperty

{url-javadoc}/is/codion/framework/domain/property/ColumnProperty.html[ColumnProperty] is used to represent properties that are based on table columns.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=columnProperty]
----

=== BlobProperty

{url-javadoc}/is/codion/framework/domain/property/BlobProperty.html[BlobProperty] is a specific ColumnProperty for the Types.BLOB type which provides lazy loading for BLOB values. Using a standard ColumnProperty with a Types.BLOB works fine, but for lazy loading you have to use BlobProperty.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=blobProperty]
----

[#_foreignkeyproperty]
=== ForeignKeyProperty

{url-javadoc}/is/codion/framework/domain/property/ForeignKeyProperty.html[ForeignKeyProperty] is a wrapper property used to represent a foreign key relation. These foreign keys refer to the primary key of the referenced entity and must be constructed accordingly in case of composite primary keys.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=foreignKeyPropertyCapital]
----

Referring to an entity with composite primary key.

NOTE: The order of the properties must be the same as the order of the respective primary key properties in the referenced entity.

[source,java]
----
foreignKeyProperty(MASTER_FK, "Master", T_MASTER,
        asList(
                columnProperty(MASTER_ID_1),
                columnProperty(MASTER_ID_2)
        ));
----

The above assumes the below master definition.

[source,java]
----
define(T_MASTER,
    columnProperty(ID_1).primaryKeyIndex(0),
    columnProperty(ID_2).primaryKeyIndex(1)
    ...
);
----

=== Boolean Properties

For databases supporting *Types.BOOLEAN* you simply use *Properties.columnProperty*.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=booleanProperty]
----

For databases lacking native boolean support we use the *Properties.booleanProperty* method, specifying the underlying true/false values.

[source,java]
----
booleanProperty(CUSTOMER_IS_ACTIVE, Types.INTEGER, "Is active", 1, 0)
----

For boolean columns using unconventional types you can specify the true and false values.

[source,java]
----
booleanProperty(CUSTOMER_IS_ACTIVE, Types.VARCHAR, "Is active", "true", "false")
----

[source,java]
----
booleanProperty(CUSTOMER_IS_ACTIVE, Types.CHAR, "Is active", 'T', 'F')
----

Note that boolean properties always use the boolean Java type, the framework handles translating to and from the actual column values.
[source,java]
----
entity.put(CUSTOMER_IS_ACTIVE, true);

boolean isActive = entity.get(CUSTOMER_IS_ACTIVE);
----

=== DenormalizedViewProperty

An entity can include a property value from a entity referenced via foreign key, by defining a denormalized view property.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=denormalizedViewProperty]
----

=== DenormalizedProperty

{url-javadoc}/is/codion/framework/domain/property/DenormalizedProperty.html[DenormalizedProperty] is used for columns that should automatically get their value from a column in a referenced table. This property automatically gets the value from the attribute in the referenced table when the corresponding reference property value is set.

[source,java]
----
denormalizedProperty(CUSTOMER_CITY, CUSTOMER_ADDRESS_FK, ADDRESS_CITY, "City")
----

NOTE: The property is not kept in sync if the value of the denormalized property is modified in the referenced entity.

[source,java]
----
Entities entities = getEntities();

Entity address = entities.entity(T_ADDRESS);
address.put(ADDRESS_CITY, "Syracuse");

Entity customer = entities.entity(T_CUSTOMER);
customer.put(CUSTOMER_ADDRESS_FK, address);

customer.get(CUSTOMER_CITY);//returns "Syracuse"

//NB
address.put(ADDRESS_CITY, "Canastota");
customer.get(CUSTOMER_CITY, still returns "Syracuse"

customer.put(CUSTOMER_ADDRESS_FK, address);//set the referenced value again
customer.get(CUSTOMER_CITY);//now this returns "Canastota"
----

=== SubqueryProperty

{url-javadoc}/is/codion/framework/domain/property/SubqueryProperty.html[SubqueryProperty] is used to represent a property which gets its value from a subquery returning a single value. Note that in the example below *country.code* must be available when the query is run, that is, the entity must include that column as a property.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=subqueryProperty]
----

=== TransientProperty

{url-javadoc}/is/codion/framework/domain/property/TransientProperty.html[TransientProperty] is used to represent a property which is not based on an underlying column, these properties all have a default value of null and can be set and retrieved just like normal properties.

=== DerivedProperty

{url-javadoc}/is/codion/framework/domain/property/DerivedProperty.html[DerivedProperty] is used to represent a transient property which value is derived from one or more properties in the same entity. The value of a derived property is provided via a {url-javadoc}/is/codion/framework/domain/property/DerivedProperty.Provider.html[DerivedProperty.Provider] implementation as shown below.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=derivedProperty]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=derivedPropertyProvider]
----

== Domain

Each entity type is defined by calling {url-javadoc}/is/codion/framework/domain/Domain.html#define-is.codion.framework.domain.entity.EntityIdentity-is.codion.framework.domain.property.Property.Builder...-[Domain.define]. The framework assumes the *entityId* name contains the table name, unless the *tableName* parameter is specified.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=defineCity]
----

=== Examples
* <<{dir-tutorials}/world.adoc#_domain, World domain model>>
* <<{dir-tutorials}/empdept.adoc#_domain, EmpDept domain model>>
* <<{dir-tutorials}/chinook.adoc#_domain, Chinook domain model>>
* <<{dir-tutorials}/petstore.adoc#_domain, Petstore domain model>>

[#_keygenerator]
== KeyGenerator

The framework provides implementations for most commonly used primary key generation strategies, sequence (with or without trigger) and auto-increment columns. The {url-javadoc}/is/codion/framework/domain/entity/KeyGenerators.html[KeyGenerators] class serves as a factory for {url-javadoc}/is/codion/framework/domain/entity/KeyGenerator.html[KeyGenerator] implementations. Static imports are assumed in the below examples.

=== Auto-increment

This assumes the underlying primary key column is either an auto-increment column or is populated from a sequence using a trigger during insert.
For auto-increment columns the **valueSource** parameter should be the table name and for a sequence/trigger it should be the sequence name.

[source,java]
----
//Auto increment column in the 'store.customer' table
.keyGenerator(automatic("store.customer"));

//Trigger and sequence named 'store.customer_seq'
.keyGenerator(automatic("store.customer_seq"));
----

=== Sequence

When sequences are used without triggers the framework can fetch the value from a sequence before insert.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=sequence]
----

=== Queried

The framework can select new primary key values from a query.

[source,java]
----
//Using a query returning the new value
.keyGenerator(queried(
    "select new_id
     from store.id_values
     where table_name = 'store.customer'"));
----

=== Increment

The framework can automatically increment the primary key value by selecting the maximum value and add one, this is very simplistic, not transaction safe and is not recommended for use anywhere but the simplest demos.

[source,java]
----
.keyGenerator(increment(T_EMPLOYEE, EMPLOYEE_ID))
----

=== Custom

You can provide a custom key generator strategy by implementing a {url-javadoc}/is/codion/framework/domain/entity/KeyGenerator.html[KeyGenerator].

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/Store.java[tags=keyGenerator]
----

== StringProvider

The {url-javadoc}/is/codion/framework/domain/entity/StringProvider.html[StringProvider] class is for providing *toString()* implementations for entities. This value is used wherever entities are displayed, for example in a ComboBox or as foreign key values in table views.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/Store.java[tags=address]
----

For more complex toString() implementations you can implement a custom *Function<Entity, String>*.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/Store.java[tags=toString]
----

== ColorProvider

{url-javadoc}/is/codion/framework/domain/entity/ColorProvider.html[ColorProvider] is used to provide colors for entity properties, used as background color in table cells for example.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=colorProvider]
----

== Validation

Custom validation of Entities is performed by implementing a {url-javadoc}/is/codion/framework/domain/entity/EntityValidator.html[EntityValidator].

The *DefaultEntityValidator* implementation provides basic range and null validation and can be extended to provide further validations. Note that validation is performed quite often so it should not perform expensive operations. Validation requiring database access for example belongs in the application model or ui.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/World.java[tags=validator]
----

== Examples

* <<{dir-tutorials}/empdept.adoc#_domain, EmpDept domain model>>
* <<{dir-tutorials}/chinook.adoc#_domain, Chinook domain model>>
* <<{dir-tutorials}/petstore.adoc#_domain, Petstore domain model>>

== Entities in action

Using the Entity class is rather straight forward.

[source,java,indent=0]
----
include::{dir-petstore-source}/is/codion/framework/demos/petstore/manual/EntitiesInAction.java[tags=entitiesInAction]
----

== Unit Testing

=== Introduction

To unit test the CRUD operations on the domain model extend {url-javadoc}/is/codion/framework/domain/entity/test/EntityTestUnit.html[EntityTestUnit].

The unit tests are run within a single transaction which is rolled back after the test finishes, so these tests are pretty much guaranteed to leave no junk data behind.

=== EntityTestUnit

The following methods all have default implementations which are based on randomly created property values, based on the constraints set in the domain model, override if the default ones are not working.

* {url-javadoc}/is/codion/framework/domain/entity/test/EntityTestUnit.html#initializeReferenceEntity-java.lang.String-java.util.Map-[initializeReferenceEntity] should return an instance of the given entity type to use for a foreign key reference required for inserting the entity being tested.
* {url-javadoc}/is/codion/framework/domain/entity/test/EntityTestUnit.html#initializeTestEntity-java.lang.String-java.util.Map-[initializeTestEntity] should return a entity to use as basis for the unit test, that is, the entity that should be inserted, selected, updated and finally deleted.
* {url-javadoc}/is/codion/framework/domain/entity/test/EntityTestUnit.html#modifyEntity-is.codion.framework.domain.entity.Entity-java.util.Map-[modifyEntity] should simply leave the entity in a modified state so that it can be used for update test, since the database layer throws an exception if an unmodified entity is updated. If *modifyEntity* returns an unmodified entity, the update test is skipped.

To run the full CRUD test for a domain entity you need to call the *test(EntityIdentity entityId)* method with the id of the given entity as parameter. You can either create a single *testDomain()* method and call the *test* method in turn for each entityId or create a *entityName* method for each domain entity, as we do in the example below.

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/StoreTest.java[tags=storeTest]
----

=== Examples

* <<{dir-tutorials}/empdept.adoc#_domain_unit_test, EmpDept domain model test>>
* <<{dir-tutorials}/chinook.adoc#_domain_unit_test, Chinook domain model test>>
* <<{dir-tutorials}/petstore.adoc#_domain_unit_test, Petstore domain model test>>