[#_entityconnection]
= EntityConnection
:dir-tutorials: ../tutorials
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:url-javadoc: link:../api
:url-entity-connection: {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.html
:url-local-entity-connection: {url-javadoc}{framework-db-local}/is/codion/framework/db/local/LocalEntityConnection.html

The Codion database layer is extremely thin, it doesn't perform any joins and provides no access to DBMS specific funtionality except primary key generation via <<manual.adoc#_keygenerator, KeyGenerator>> strategies. The framework provides implementations for the most common strategies, sequences (with or without triggers) and auto increment columns.

The database layer is specified by the {url-entity-connection}[EntityConnection] class. It provides methods for selecting, inserting, updating and deleting entities, executing procedures and functions, filling reports as well as providing transaction control.

The <<{dir-tutorials}/chinook/chinook.adoc#_domain, Chinook domain model>> is used in the examples below.

NOTE: Static imports are used extensively in the examples, see <<#_full_example, full example code>>.

== Selecting

By default, when you select a row using {url-entity-connection}[EntityConnection] you receive an Entity instance along with a single level of foreign key references, that is a so-called fetch depth of one. This means that selecting a track you get all the entities referenced via foreign keys as well.

.The N+1 problem

This means that selecting tracks performs four queries (track + album, mediatype and genre), but that number of queries is the same whether you select one or a thousand tracks.

The fetch depth can be configured on a foreign key basis when defining entities. A fetch depth of zero means that no foreign key references are fetched, and a value larger than one means that not only is the foreign key reference fetched but also its foreign key references, until the defined depth has been reached. A negative fetch depth means no limit with the whole dependency graph fetched. This limiting of foreign key fetch depth can be turned off, meaning the full reference graph is always fetched, via the *codion.db.limitForeignKeyFetchDepth=false* system property or {url-javadoc}{framework-db-local}/is/codion/framework/db/local/LocalEntityConnection.html#LIMIT_FOREIGN_KEY_FETCH_DEPTH[LocalEntityConnection.LIMIT_FOREIGN_KEY_FETCH_DEPTH.set(false)], or on a connection instance via {url-javadoc}{framework-db-local}/is/codion/framework/db/local/LocalEntityConnection.html#setLimitForeignKeyFetchDepth{opar}boolean{cpar}[connection.setLimitForeignKeyFetchDepth(false)].

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/domain/impl/ChinookImpl.java[tags=fetchDepth0]
----

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/domain/impl/ChinookImpl.java[tags=fetchDepth2]
----

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=fetchDepthEntity]
----

The fetch depth can also be configured on a query basis, either for the whole query or one or more foreign keys.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=fetchDepthCondition]
----

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=fetchDepthConditionForeignKey]
----

=== Selecting entities

{url-entity-connection}#select{opar}is.codion.framework.db.condition.Condition{cpar}[select(Condition condition)]

{url-entity-connection}#select{opar}is.codion.framework.db.Select{cpar}[select(Select select)]

{url-entity-connection}#selectSingle{opar}is.codion.framework.db.condition.Condition{cpar}[selectSingle(Condition condition)]

{url-entity-connection}#selectSingle{opar}is.codion.framework.db.Select{cpar}[selectSingle(Select select)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=select]
----

{url-entity-connection}#select{opar}is.codion.framework.domain.entity.Key{cpar}[select(Key key)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=selectKey]
----

{url-entity-connection}#select{opar}java.util.Collection{cpar}[select(Collection<Key> keys)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=selectKeys]
----

=== Selecting values

For selecting the values of a single column.

{url-entity-connection}#select{opar}is.codion.framework.domain.entity.Column{comma}is.codion.framework.db.condition.Condition{cpar}[select(Column<T> column, Condition condition)]

{url-entity-connection}#select{opar}is.codion.framework.domain.entity.Column{comma}is.codion.framework.db.Select{cpar}[select(Column<T> column, Select condition)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=selectValues]
----

=== iterator

*LocalEntityConnection* provides a way to iterate over a result set, instead of loading it into memory.

{url-local-entity-connection}#iterator{opar}is.codion.framework.db.condition.Condition{cpar}[iterator(Condition condition)]

{url-local-entity-connection}#iterator{opar}is.codion.framework.db.Select{cpar}[iterator(Select select)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=iterator]
----

=== dependencies

For selecting entities that depend on a set of entities via foreign keys.

{url-entity-connection}#dependencies{opar}java.util.Collection{cpar}[dependencies(Collection<Entity> entities)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=dependencies]
----

=== count

For selecting the row count given a condition.

{url-entity-connection}#count{opar}is.codion.framework.db.condition.Condition{cpar}[count(Condition condition)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=count]
----

== Modifying

=== insert

For inserting rows.

** {url-entity-connection}#insert{opar}is.codion.framework.domain.entity.Entity{cpar}[insert(Entity entity)]

** {url-entity-connection}#insert{opar}java.util.List{cpar}[insert(List<Entity> entities)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=insert]
----

=== update

For updating one or more entity instances. These methods throw an exception if any of the entities is unmodified.

** {url-entity-connection}#update{opar}is.codion.framework.domain.entity.Entity{cpar}[update(Entity entity)]

** {url-entity-connection}#update{opar}java.util.List{cpar}[update(List<Entity> entities)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=update]
----

==== Optimistic locking

The framework performs optimistic locking during updates of entity instances using the methods above, by selecting the entities being updated *for update* (when supported by the underlying database) and comparing all original values to the current row values, throwing an exception if any value differs or the row is missing. Optimistic locking can be turned off system-wide using the *codion.db.useOptimisticLocking=false* system property or {url-javadoc}{framework-db-local}/is/codion/framework/db/local/LocalEntityConnection.html#USE_OPTIMISTIC_LOCKING[LocalEntityConnection.USE_OPTIMISTIC_LOCKING.set(false)], or on a connection instance via {url-javadoc}{framework-db-local}/is/codion/framework/db/local/LocalEntityConnection.html#setOptimisticLockingEnabled{opar}boolean{cpar}[connection.setOptimisticLockingEnabled(false)].

For updating by where condition.

** {url-entity-connection}#update{opar}is.codion.framework.db.Update{cpar}[update(Update update)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=update]
----

=== delete

For deleting existing rows.

** {url-entity-connection}#delete{opar}is.codion.framework.db.condition.Condition{cpar}[delete(Condition condition)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=deleteCondition]
----

** {url-entity-connection}#delete{opar}is.codion.framework.domain.entity.Key{cpar}[delete(Key key)]

** {url-entity-connection}#delete{opar}java.util.List{cpar}[delete(List<Key> keys)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=deleteKey]
----

== Procedures & Functions

=== Function

** {url-entity-connection}#execute{opar}is.codion.common.db.operation.FunctionType{cpar}[execute(FunctionType functionType)]
** {url-entity-connection}#execute{opar}is.codion.common.db.operation.FunctionType{comma}T{cpar}[execute(FunctionType functionType, T argument)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=function]
----

=== Procedure

** {url-entity-connection}#execute{opar}is.codion.common.db.operation.ProcedureType{cpar}[execute(ProcedureType procedureType)]
** {url-entity-connection}#execute{opar}is.codion.common.db.operation.ProcedureType{comma}T{cpar}[execute(ProcedureType procedureType, T argument)]

Executing procedures is the same as executing functions, except without a return value.

== Reporting

=== fillReport

** {url-entity-connection}#fillReport{opar}is.codion.common.db.report.ReportType{comma}P{cpar}[fillReport(ReportType reportType, P reportParameters)]

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=report]
----

[#_full_example]
== Full example

.Show code
[%collapsible]
====
[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[lines=4..-1]
----
====

== Transaction control

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/manual/EntityConnectionDemo.java[tags=transaction]
----

== LocalEntityConnection

A EntityConnection implementation based on a direct connection to the database, provides access to the underlying JDBC connection.

== RemoteEntityConnection

A EntityConnection implementation based on an RMI connection. Requires a server.

== HttpEntityConnection

A EntityConnection implementation based on HTTP. Requires a server.