= Domain Model
:dir-tutorials: ../tutorials
:dir-source: ../../../../../demos/manual/src/main/java
:dir-petstore-source: ../../../../../demos/petstore/src/main/java
:dir-world-source: ../../../../../demos/world/src/main/java
:dir-world-resources: ../../../../../demos/world/src/main/resources
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:url-javadoc: link:../api

A Codion domain model is based around the {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Entity.html[Entity] interface, which represents a row in a table, providing access to the column values via its *get()* and *put()* methods.

[plantuml, entity-diagram, svg, align=center]
-------------------------------------------

interface Entity {
    +<T> T get(Attribute<T> attribute)
    +<T> T put(Attribute<T> attribute, T value)
}
-------------------------------------------

== Domain core classes

*{url-javadoc}{framework-domain}/is/codion/framework/domain/Domain.html[Domain]*::
Specifies a domain model, containing entity definitions, procedures, functions and reports. A Codion domain model is implemented by extending the *{url-javadoc}{framework-domain}/is/codion/framework/domain/DefaultDomain.html[DefaultDomain]* class and populating it with entity definitions.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/DomainType.html[DomainType]*::
A unique identifier for a domain model and a factory for *EntityType* instances associated with that domain model.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityType.html[EntityType]*::
A unique identifier for an entity type (based on a table or query) and a factory for *Attribute* instances associated with that entity type.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Attribute.html[Attribute]*::
A typed identifier for a column (actual or pseudo), allowing for type safe access to the associated value. Attributes are usually wrapped in an interface, serving as a convenient namespace.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/ForeignKey.html[ForeignKey]*::
An attribute subclass representing a foreign key relationship.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.html[EntityDefinition]*::
Encapsulates the meta-data required for presenting and persisting an entity.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/property/Property.html[Property]*::
Each *Attribute* has an associated *Property* (or one of its subclasses) which encapsulates the meta-data required for presenting and persisting the associated value.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Entity.html[Entity]*::
Represents a row in a table (or query) and maps *Attributes* to their associated values while keeping track of values which have been modified since they were initially set.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Key.html[Key]*::
Represents a unique key for a given entity.

== Domain API
To define a domain model API we:

* Create a {url-javadoc}{framework-domain}/is/codion/framework/domain/DomainType.html[DomainType] constant representing the domain.
* Use the *DomainType* to create {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityType.html[EntityType] constants for each table, wrapped in a namespace interface.
* Use the *EntityTypes* to create {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Attribute.html[Attribute] constants for each column and a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/ForeignKey.html[ForeignKey] constant for each foreign key.

These constants represent the domain API and are used when referring to tables, columns or foreign keys.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/minimal/ManualDomainModel.java[tags=storeApi]
----
<1> The *DomainType* instance serves as a factory for *EntityTypes* associated with that domain.
<2> Each *EntityType* instance serves as a factory for *Attributes* and *ForeignKeys* associated with that entity.

Typically the underlying table name is used as the *EntityType* name, but you can use whatever identifying string you want and specify the table name via the *tableName()* builder method when defining the entity.

The underlying column name is typically used as the *Attribute* name, but as with the *EntityType* you can use whatever value you want and specify the column name via the *columnName()* method when defining the associated *Property*.

== Domain implementation
The domain model is implemented by extending the {url-javadoc}{framework-domain}/is/codion/framework/domain/DefaultDomain.html[DefaultDomain] class and populating it with *EntityDefinitions* based on the domain tables. An *EntityDefinition* is comprised of *Properties* based on the *Attributes* associated with the entity.

The factory methods for creating *EntityDefinitions* and *Properties* used below return builders which provide further configuration options (such as nullability and maximum length for properties and the caption and primary key generator for the entity definition). These factory methods are usually statically imported, but the class names are included here for clarity.

NOTE: If a caption is not specified for a property, it is marked as hidden and is not visible in table views.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/minimal/ManualDomainModel.java[tags=storeImpl]
----
<1> The *DomainType* constant is a required constructor parameter.

{url-javadoc}{framework-domain}/is/codion/framework/domain/Domain.html[Domain] is a https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html[Service Provider Interface (SPI)], and it is recommended to configure the domain implementation class for the https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html[Service Loader]. Without the Service Loader you are restricted to a local JDBC connection, since you must manually provide a domain instance when establishing a connection, instead of just referring to the *DomainType* constant.

_src/main/java/module-info.java_

[source]
----
provides is.codion.framework.domain.Domain
          with is.codion.framework.demos.store.domain.StoreImpl;
----

or if not using Java Modules (JPMS)

_src/main/resources/META-INF/services/is.codion.framework.domain.Domain_

[source]
----
is.codion.framework.demos.store.domain.StoreImpl
----

NOTE: The domain model implementation must be on the classpath when running with a local JDBC connection, but when running with a RMI or HTTP connection the domain model API is sufficient. If you forsee using RMI or HTTP connections it is recommended to split your domain model into separate API and implementation modules, to simplify client configurations (see https://github.com/bjorndarri/chinook[Chinook] and https://github.com/bjorndarri/world[World] demo applications, see https://github.com/bjorndarri/petclinic[Petclinic] for a simple single class domain model).

The domain model provides an {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Entities.html[Entities] instance via {url-javadoc}{framework-domain}/is/codion/framework/domain/Domain.html#entities{opar}{cpar}[entities()], which contains the entity definitions and serves as a factory for *Entity* and *Key* instances.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/minimal/ManualDomainModel.java[tags=domainUsage]
----

== Data type mapping

[cols="1,3"]
|===
|Java type|SQL type

|Short|java.sql.Types.SMALLINT
|Integer|java.sql.Types.INTEGER
|Double|java.sql.Types.DOUBLE
|Long|java.sql.Types.BIGINT
|BigDecimal|java.sql.Types.DECIMAL
|LocalDateTime|java.sql.Types.TIMESTAMP
|LocalDate|java.sql.Types.DATE
|LocalTime|java.sql.Types.TIME
|OffsetTime|java.sql.Types.TIME_WITH_TIMEZONE
|OffsetDateTime|java.sql.Types.TIMESTAMP_WITH_TIMEZONE
|java.util.Date|java.sql.Types.DATE
|java.sql.Time|java.sql.Types.TIME
|java.sql.Date|java.sql.Types.DATE
|java.sql.Timestamp|java.sql.Types.TIMESTAMP
|String|java.sql.Types.VARCHAR
|Boolean|java.sql.Types.BOOLEAN
|Character|java.sql.Types.CHAR
|byte[]|java.sql.Types.BLOB
|===

== Foreign keys

=== Examples

A simple foreign key based on a single column.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/api/World.java[tags=foreignKeyCapital]
----

Foreign key based on a composite key.

[source,java]
----
interface Parent {
  EntityType<Entity> TYPE = DOMAIN.entityType("parent");

  Attribute<Integer> ID_1 = TYPE.integerAttribute("id1");
  Attribute<Integer> ID_2 = TYPE.integerAttribute("id2");
}

interface Child {
  EntityType<Entity> TYPE = DOMAIN.entityType("child");

  Attribute<Integer> PARENT_ID_1 = TYPE.integerAttribute("parent_id1");
  Attribute<Integer> PARENT_ID_2 = TYPE.integerAttribute("parent_id2");

  ForeignKey PARENT_FK = TYPE.foreignKey("parent",
          PARENT_ID_1, Parent.ID_1,
          PARENT_ID_2, Parent.ID_2);
}
----

Domain constant definitions for the World demo application (simplified).

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/world/domain/World.java[tags=entityTypesAndAttributes]
----

== Properties

=== Property

Each column is represented by the {url-javadoc}{framework-domain}/is/codion/framework/domain/property/Property.html[Property] class or one of its subclasses, which encapsulate the metadata required for presenting and persisting the associated value. This class also provides factory methods for constructing Property instances and is usually statically imported, as will be assumed in the following examples. Each Property is based on an Attribute or ForeignKey.

A {url-javadoc}{framework-domain}/is/codion/framework/domain/property/Property.html[Property] can be transient or based on table columns.

=== Primary key

It is recommended that entities have a primary key defined, that is, one or more column properties representing a unique column combination.

The only requirement is that the primary key properties represent a unique column combination for the underlying table, it does not have to correspond to an actual table primary (or unique) key, although that is of course preferable.

If no primary key properties are specified, equals() will not work (since it is based on the primary key). You can still use the *Entity.columnValuesEqual()* method to check if all column based values are equal in two entities.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=primaryKey]
----

In case of composite primary keys you create a ColumnProperty and specify the primary key index.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=compositePrimaryKey]
----

=== ColumnProperty

{url-javadoc}{framework-domain}/is/codion/framework/domain/property/ColumnProperty.html[ColumnProperty] is used to represent properties that are based on table columns.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=columnProperty]
----

==== Subquery

A ColumnProperty can represent a subquery returning a single value.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=subqueryProperty]
----

=== BlobProperty

{url-javadoc}{framework-domain}/is/codion/framework/domain/property/BlobProperty.html[BlobProperty] is a specific ColumnProperty for the Types.BLOB type which provides lazy loading for BLOB values. Using a standard ColumnProperty with a byte array type works fine, but for lazy loading you have to use BlobProperty.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=blobProperty]
----

[#_foreignkeyproperty]
=== ForeignKeyProperty

{url-javadoc}{framework-domain}/is/codion/framework/domain/property/ForeignKeyProperty.html[ForeignKeyProperty] is a property used to represent a foreign key relation.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=foreignKeyPropertyCapital]
----

=== Boolean Properties

For databases supporting *Types.BOOLEAN* you simply use *Property.columnProperty*.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=booleanProperty]
----

For databases lacking native boolean support we use the *Property.booleanProperty* method, specifying the underlying type and the true/false values.

[source,java]
----
booleanProperty(Customer.IS_ACTIVE, "Is active", Integer.class, 1, 0)
----

[source,java]
----
booleanProperty(Customer.IS_ACTIVE, "Is active", String.class, "true", "false")
----

[source,java]
----
booleanProperty(Customer.IS_ACTIVE, "Is active", Character.class, 'T', 'F')
----

Note that boolean properties always use the boolean Java type, the framework handles translating to and from the actual column values.

[source,java]
----
entity.put(Customer.IS_ACTIVE, true);

Boolean isActive = entity.get(Customer.IS_ACTIVE);
----

=== ItemProperty

A property based on a list of valid items.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=items]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=item]
----

=== DenormalizedProperty

An entity can include a read-only property value from an entity referenced via foreign key, by defining a denormalized property.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=denormalizedProperty]
----

=== TransientProperty

{url-javadoc}{framework-domain}/is/codion/framework/domain/property/TransientProperty.html[TransientProperty] is used to represent a property which is not based on an underlying column, these properties all have a default value of null and can be set and retrieved just like normal properties.

=== DerivedProperty

{url-javadoc}{framework-domain}/is/codion/framework/domain/property/DerivedProperty.html[DerivedProperty] is used to represent a value which is derived from one or more properties in the same entity. The value of a derived property is provided via a {url-javadoc}{framework-domain}/is/codion/framework/domain/property/DerivedProperty.Provider.html[DerivedProperty.Provider] implementation as shown below.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=derivedProperty]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/api/World.java[tags=derivedPropertyProvider]
----

== Domain

Each entity is defined by creating a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.Builder.html[EntityDefinition.Builder] instance via {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.html#definition{opar}is.codion.framework.domain.property.Property.Builder\...{cpar}[EntityDefinition.definition()] (statically imported in the example below) and adding it to the domain model, via the {url-javadoc}{framework-domain}/is/codion/framework/domain/DefaultDomain.html#add{opar}is.codion.framework.domain.entity.EntityDefinition{cpar}[add(EntityDefinition)] or {url-javadoc}{framework-domain}/is/codion/framework/domain/DefaultDomain.html#add{opar}is.codion.framework.domain.entity.EntityDefinition.Builder{cpar}[add(EntityDefinition.Builder)] methods in the {url-javadoc}{framework-domain}/is/codion/framework/domain/DefaultDomain.html[DefaultDomain] class.
The framework assumes the *entityType* name is the underlying table name, but the *tableName* can be specified via {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.Builder.html#tableName{opar}java.lang.String{cpar}[EntityDefinition.Builder.tableName(String)] method.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=defineCity]
----

=== Examples
* <<{dir-tutorials}/world/world.adoc#_domain_model, World domain model>>
* <<{dir-tutorials}/empdept/empdept.adoc#_domain_model, EmpDept domain model>>
* <<{dir-tutorials}/chinook/chinook.adoc#_domain_model, Chinook domain model>>
* <<{dir-tutorials}/petstore/petstore.adoc#_domain_model, Petstore domain model>>

[#_keygenerator]
== KeyGenerator

The framework provides implementations for most commonly used primary key generation strategies, identity column, sequence (with or without trigger) and auto-increment columns. The {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/KeyGenerator.html[KeyGenerator] class serves as a factory for {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/KeyGenerator.html[KeyGenerator] implementations. Static imports are assumed in the below examples.

=== Identity

Based on identity columns, supported by most DBMSs.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/framework/demos/chinook/domain/impl/ChinookImpl.java[tags=identity]
----

=== Automatic

This assumes the underlying primary key column is either an auto-increment column or is populated from a sequence using a trigger during insert.
For auto-increment columns the **valueSource** parameter should be the table name and for a sequence/trigger it should be the sequence name.

[source,java]
----
//Auto increment column in the 'store.customer' table
.keyGenerator(automatic("store.customer"));

//Trigger and sequence named 'store.customer_seq'
.keyGenerator(automatic("store.customer_seq"));
----

=== Sequence

When sequences are used without triggers the framework can fetch the value from a sequence before insert.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=sequence]
----

=== Queried

The framework can select new primary key values from a query.

[source,java]
----
//Using a query returning the new value
.keyGenerator(queried(
    "select new_id " +
    "from store.id_values " +
    "where table_name = 'store.customer'"));
----

=== Increment

The framework can automatically increment the primary key value by selecting the maximum value and add one, this is very simplistic, not transaction safe and is not recommended for use anywhere but the simplest demos.

[source,java]
----
.keyGenerator(increment("scott.emp", "empno"))
----

=== Custom

You can provide a custom key generator strategy by implementing a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/KeyGenerator.html[KeyGenerator].

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/Store.java[tags=keyGenerator]
----

== StringFactory

The {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/StringFactory.html[StringFactory] class provides a builder for a *Function<Entity, String>* instance, which is then used to provide the *toString()* implementations for entities. This value is used wherever entities are displayed, for example in a ComboBox or as foreign key values in table views.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/Store.java[tags=address]
----

For more complex toString() implementations you can implement a custom *Function<Entity, String>*.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/Store.java[tags=customerStringFactory]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/Store.java[tags=toString]
----

== ColorProvider

{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/ColorProvider.html[ColorProvider] is used to provide colors for attributes, used as foreground or background color in table cells for example.

The framework supports String color definitions, in a format recognized by *java.awt.Color.decode()*, like the one below, in case you don't want a dependency on *java.awt.Color* in the domain model.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/api/World.java[tags=colorProvider]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=foreground]
----

== Validation

Custom validation of Entities is performed by implementing a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityValidator.html[EntityValidator].

The *DefaultEntityValidator* implementation provides basic range and null validation and can be extended to provide further validations. Note that validation is performed quite often, so it should not perform expensive operations. Validation requiring database access for example belongs in the application model or ui.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/api/World.java[tags=validator]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=validator]
----

== Examples

* <<{dir-tutorials}/empdept/empdept.adoc#_domain, EmpDept domain model>>
* <<{dir-tutorials}/chinook/chinook.adoc#_domain, Chinook domain model>>
* <<{dir-tutorials}/petstore/petstore.adoc#_domain, Petstore domain model>>

== Custom data types

When using a custom data type you must specify the *columnClass* of a ColumnProperty and
provide a {url-javadoc}{framework-domain}/is/codion/framework/domain/property/ColumnProperty.ValueConverter.html[ValueConverter] implementation.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/api/World.java[tags=customType]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/api/World.java[tags=customTypeClass]
----

NOTE: The custom type must be serializable for use in an application using the RMI connection.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=columnClass]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/WorldImpl.java[tags=converter]
----

When using the HTTP connection in an application using a custom data type, you must implement a {url-javadoc}{framework-json-domain}/is/codion/framework/json/domain/EntityObjectMapperFactory.html[EntityObjectMapperFactory], providing a {url-javadoc}{framework-json-domain}/is/codion/framework/json/domain/EntityObjectMapper.html[EntityObjectMapper] instance containing a serializer/deserializer for the custom types.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/framework/demos/world/domain/api/WorldObjectMapperFactory.java[tags=customSerializer]
----

This *EntityObjectMapperFactory* must be exposed to the ServiceLoader.

_src/main/java/module-info.java_

[source]
----
include::{dir-world-source}/module-info.java[tag=customSerializer]
----

See <<{dir-tutorials}/world/world.adoc#_domain, World domain model>>

== Entities in action

Using the Entity class is rather straight forward.

[source,java,indent=0]
----
include::{dir-petstore-source}/is/codion/framework/demos/petstore/manual/EntitiesInAction.java[tags=entitiesInAction]
----

== Unit Testing

=== Introduction

To unit test the CRUD operations on the domain model extend {url-javadoc}{framework-domain-test}/is/codion/framework/domain/entity/test/EntityTestUnit.html[EntityTestUnit].

The unit tests are run within a single transaction which is rolled back after the test finishes, so these tests are pretty much guaranteed to leave no junk data behind.

=== EntityTestUnit

The following methods all have default implementations which are based on randomly created values, based on the value constraints set in the domain model, override if the default ones are not working.

* {url-javadoc}{framework-domain-test}/is/codion/framework/domain/entity/test/EntityTestUnit.html#initializeForeignKeyEntity{opar}is.codion.framework.domain.entity.ForeignKey{comma}java.util.Map{cpar}[initializeForeignKeyEntity] should return an entity instance for the given foreign key to use for a foreign key reference required for inserting the entity being tested.
* {url-javadoc}{framework-domain-test}/is/codion/framework/domain/entity/test/EntityTestUnit.html#initializeTestEntity{opar}is.codion.framework.domain.entity.EntityType{comma}java.util.Map{cpar}[initializeTestEntity] should return an entity to use as basis for the unit test, that is, the entity that should be inserted, selected, updated and finally deleted.
* {url-javadoc}{framework-domain-test}/is/codion/framework/domain/entity/test/EntityTestUnit.html#modifyEntity{opar}is.codion.framework.domain.entity.Entity{comma}java.util.Map{cpar}[modifyEntity] should simply leave the entity in a modified state so that it can be used for update test, since the database layer throws an exception if an unmodified entity is updated. If *modifyEntity* returns an unmodified entity, the update test is skipped.

To run the full CRUD test for a domain entity you need to call the *test(EntityType entityType)* method with the entity type as parameter. You can either create a single *testDomain()* method and call the *test* method in turn for each entityType or create a *entityName* method for each domain entity, as we do in the example below.

[source,java]
----
include::{dir-source}/is/codion/framework/demos/manual/store/domain/StoreTest.java[tags=storeTest]
----

=== Examples

* <<{dir-tutorials}/empdept/empdept.adoc#_domain_unit_test, EmpDept domain model test>>
* <<{dir-tutorials}/chinook/chinook.adoc#_domain_unit_test, Chinook domain model test>>
* <<{dir-tutorials}/petstore/petstore.adoc#_domain_unit_test, Petstore domain model test>>