= EntityEditPanel
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

The {url-javadoc}/is/codion/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] contains the controls (text fields, combo boxes and such) for editing an entity instance.

When extending an EntityEditPanel you must implement the *initializeUI()* method, which initializes the edit panel UI. The EntityEditPanel class exposes methods for creating input components and binding them with the underlying {url-javadoc}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] instance.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/ui/CustomerEditPanel.java[tags=customerEditPanel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/ui/AddressEditPanel.java[tags=addressEditPanel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/ui/CustomerAddressEditPanel.java[tags=customerAddressEditPanel]
----

== Input controls

=== Boolean

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createBooleanComboBox-is.codion.framework.domain.entity.Attribute-[createBooleanComboBox(attribute)]

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createCheckBox-is.codion.framework.domain.entity.Attribute-[createCheckBox(attribute)]

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createNullableCheckBox-is.codion.framework.domain.entity.Attribute-[createNullableCheckBox(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=booleanValue]
----

=== Foreign key

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyComboBox-is.codion.framework.domain.entity.ForeignKey-[createForeignKeyComboBox(attribute)]

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyField-is.codion.framework.domain.entity.ForeignKey-[createForeignKeyField(attribute)]

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyLookupField-is.codion.framework.domain.entity.ForeignKey-[createForeignKeyLookupField(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=foreignKeyValue]
----

=== Temporal

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTemporalInputPanel-is.codion.framework.domain.entity.Attribute-[createTemporalInputPanel(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=temporalValue]
----

=== Numerical

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=numericalValue]
----

=== Text

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=textValue]
----

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextArea-is.codion.framework.domain.entity.Attribute-[createTextArea(attribute)]

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextField-is.codion.framework.domain.entity.Attribute-[createTextField(attribute)]

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextInputPanel-is.codion.framework.domain.entity.Attribute-[createTextInputPanel(attribute)]

=== Value list

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=valueList]
----

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createValueListComboBox-is.codion.framework.domain.entity.Attribute-[createValueListComboBox(attribute)]

== Panels & labels

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createLabel-is.codion.framework.domain.entity.Attribute-[createLabel(attribute)]

{url-javadoc}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createInputPanel-is.codion.framework.domain.entity.Attribute-[createInputPanel(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=panelLabel]
----

== Custom actions
The action mechanism used throughout the Codion framework is based on the {url-javadoc}/is/codion/swing/common/ui/control/Control.html[Control] class and its subclasses and the {url-javadoc}/is/codion/swing/common/ui/control/Controls.html[Controls] class which represents a collection of controls.