= Conditions
:dir-tutorials: ../tutorials
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:url-javadoc: link:../api

The <<{dir-tutorials}/chinook/chinook.adoc#_domain_model, Chinook domain model>> is used in the examples below.

== Condition

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/Condition.html[Condition]*::
Represents a query condition and contains factory methods for creating *Condition* instances.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/ColumnCondition.html[ColumnCondition]*::
Represents a column based Condition element.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/ForeignKeyCondition.html[ForeignKeyCondition]*::
Represents a foreign key based Condition element.

NOTE: {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Column.html[Column] and {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/ForeignKey.html[ForeignKey] implement {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/ColumnCondition.Factory.html[ColumnCondition.Factory] and {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/ForeignKeyCondition.Factory.html[ForeignKeyCondition.Factory] respectively, and can be used to create *Condition* instances.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=condition]
----

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=columnCondition]
----

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=foreignKeyCondition]
----

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/CustomCondition.html[CustomCondition]*::
Provides a way to specify a query condition which can not be created with the column or foreign key based APIs.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=custom]
----

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/Condition.Combination.html[Condition.Combination]*::
Extends *Condition* and represents a combination of *Condition* instances, which are combined using either *AND* or *OR*.
These can be nested and combined with other condition combinations.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=combination]
----

== Select

*{url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Select.html[Select]*::
Represents a where condition as well as extended configuration specifically for selecting, such as *orderBy*, *limit*, *offset* and *fetchDepth*. {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Select.html#where{opar}is.codion.framework.domain.entity.condition.Condition{cpar}[Select.where] returns a {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Select.Builder.html[Select.Builder] instance for further configuration.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=select]
----

== Update

*{url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Update.html[Update]*::
Represents a where condition as well as the columns values for updating one or more entities. {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Update.html#where{opar}is.codion.framework.domain.entity.condition.Condition{cpar}[Update.where] returns a {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Update.Builder.html[Update.Builder] instance for specifying the columns to update and their respective values.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=update]
----

== Count

*{url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Count.html[Count]*::
Represents a where condition specifically for counting records. {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Count.html#where{opar}is.codion.framework.domain.entity.condition.Condition{cpar}[Count.where] returns a {url-javadoc}{framework-db-core}/is/codion/framework/db/EntityConnection.Count.Builder.html[Count.Builder].

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/ConditionDemo.java[tags=count]
----