= EntityEditPanel
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

The {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] contains the controls (text fields, combo boxes and such) for editing an entity instance.

When extending an EntityEditPanel you must implement the *initializeUI()* method, which initializes the edit panel UI. The EntityEditPanel class exposes methods for creating input components and binding them with the underlying {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] instance.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/ui/CustomerEditPanel.java[tags=customerEditPanel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/ui/AddressEditPanel.java[tags=addressEditPanel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/store/ui/CustomerAddressEditPanel.java[tags=customerAddressEditPanel]
----

== Input controls

=== Boolean

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createBooleanComboBox{opar}is.codion.framework.domain.entity.Attribute{cpar}[createBooleanComboBox(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createCheckBox{opar}is.codion.framework.domain.entity.Attribute{cpar}[createCheckBox(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=booleanValue]
----

=== Foreign key

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyComboBox{opar}is.codion.framework.domain.entity.ForeignKey{cpar}[createForeignKeyComboBox(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeyField{opar}is.codion.framework.domain.entity.ForeignKey{cpar}[createForeignKeyField(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createForeignKeySearchField{opar}is.codion.framework.domain.entity.ForeignKey{cpar}[createForeignKeySearchField(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=foreignKeyValue]
----

=== Temporal

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTemporalInputPanel{opar}is.codion.framework.domain.entity.Attribute{cpar}[createTemporalInputPanel(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createLocalDateField{opar}is.codion.framework.domain.entity.Attribute{cpar}[createLocalDateField(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=temporalValue]
----

=== Numerical

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=numericalValue]
----

=== Text

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextField{opar}is.codion.framework.domain.entity.Attribute{cpar}[createTextField(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createFormattedTextField{opar}is.codion.framework.domain.entity.Attribute{cpar}[createFormattedTextField(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextArea{opar}is.codion.framework.domain.entity.Attribute{cpar}[createTextArea(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextInputPanel{opar}is.codion.framework.domain.entity.Attribute{cpar}[createTextInputPanel(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=textValue]
----

=== Selection

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createComboBox{opar}is.codion.framework.domain.entity.Attribute{comma}javax.swing.ComboBoxModel{cpar}[createComboBox(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=selectionValue]
----

=== Items

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createItemComboBox{opar}is.codion.framework.domain.entity.Attribute{cpar}[createItemComboBox(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=item]
----

== Panels & labels

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createLabel{opar}is.codion.framework.domain.entity.Attribute{cpar}[createLabel(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createInputPanel{opar}is.codion.framework.domain.entity.Attribute{cpar}[createInputPanel(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/framework/EntityEditPanels.java[tags=panelLabel]
----

== Custom actions
The action mechanism used throughout the Codion framework is based on the {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/control/Control.html[Control] class and its subclasses and the {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/control/Controls.html[Controls] class which represents a collection of controls.