[#_domain_model]
= Domain Model
:dir-tutorials: ../tutorials
:dir-source: ../../../../../demos/manual/src/main/java
:dir-test-source: ../../../../../demos/manual/src/test/java
:dir-petstore-source: ../../../../../demos/petstore/src/main/java
:dir-world-source: ../../../../../demos/world/src/main/java
:dir-world-resources: ../../../../../demos/world/src/main/resources
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:url-javadoc: link:../api

[#_domain_modelling]
== Domain modelling

* Declarative, not magical
* Visible and localized behavior
* Safe, testable, Java-native APIs
* Avoiding runtime introspection/config injection

Codion’s domain model layer is a declarative, type-safe representation of the underlying database schema, designed to provide expressive CRUD functionality without annotation overhead. At its heart is the {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Entity.html[Entity] interface — representing a single row of data and its modifiable state, providing access to attribute values via its *get()* and *set()* methods.

[#_core_framework_classes]
== Core classes

*{url-javadoc}{framework-domain}/is/codion/framework/domain/Domain.html[Domain]*::
Specifies a domain model, containing entity definitions, procedures, functions and reports.
A Codion domain model is implemented by extending the *{url-javadoc}{framework-domain}/is/codion/framework/domain/DomainModel.html[DomainModel]* class and populating it with entity definitions.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/DomainType.html[DomainType]*::
A unique identifier for a domain model and a factory for *EntityType* instances associated with that domain model.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityType.html[EntityType]*::
A unique identifier for an entity type and a factory for *Attribute* instances associated with that entity type.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Attribute.html[Attribute]*::
A typed identifier for a column, foreign key or transient attribute, usually a *Column* or *ForeignKey*, allowing for type safe access to the associated value.
Attributes are usually wrapped in an interface, serving as a convenient namespace.

[plantuml,attribute-diagram,svg,align=center]
-------------------------------------------
skinparam genericDisplay old

interface Attribute<T> {
    +String name()
}

interface Column<T> {}

interface ForeignKey {}

Attribute --> Column
Attribute --> ForeignKey
-------------------------------------------

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Column.html[Column]*::
An Attribute subclass representing a table column.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/ForeignKey.html[ForeignKey]*::
An attribute subclass representing a foreign key relationship.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.html[EntityDefinition]*::
Encapsulates the meta-data required for presenting and persisting an entity.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/AttributeDefinition.html[AttributeDefinition]*::
Each *Attribute* has an associated *AttributeDefinition* (or one of its subclasses) which encapsulates the meta-data required for presenting and persisting the associated value.

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Entity.html[Entity]*::
Represents a row in a table (or query) and maps *Attributes* to their associated values while keeping track of values which have been modified since they were initially set.

[plantuml,entity-diagram,svg,align=center]
-------------------------------------------

interface Entity {
    +Entity.Key primaryKey()
    +<T> T get(Attribute<T> attribute)
    +<T> T set(Attribute<T> attribute, T value)
    +boolean modified()
}
-------------------------------------------

*{url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Entity.Key.html[Entity.Key]*::
Represents a unique key for a given entity.

== Domain API

To define a domain model API we:

* Create a {url-javadoc}{framework-domain}/is/codion/framework/domain/DomainType.html[DomainType] constant representing the domain.
* Use the *DomainType* to create {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityType.html[EntityType] constants for each table, wrapped in a namespace interface.
* Use the *EntityTypes* to create {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Column.html[Column] constants for each column and a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/ForeignKey.html[ForeignKey] constant for each foreign key.

These constants represent the domain API and are used when referring to tables, columns or foreign keys.

NOTE: The use of https://en.wikipedia.org/wiki/Constant_interface[constant interfaces] is discouraged in modern Java practice because all implementing classes inherit the constants, potentially polluting their namespaces. If this is a concern, use a *public static final* constants class instead — at the cost of slightly more typing.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/minimal/ManualDomainModel.java[tags=storeApi]
----

<1> The *DomainType* instance serves as a factory for *EntityTypes* associated with that domain.
<2> Each *EntityType* instance serves as a factory for *Columns* and *ForeignKeys* associated with that entity.

Typically, the underlying table name is used as the *EntityType* name, but you can use whatever identifying string you want and specify the table name via the *tableName()* builder method when defining the entity.

The underlying column name is typically used as the *Column* name, but as with the *EntityType* you can use whatever value you want and specify the column name via the *columnName()* method when creating the associated *ColumnDefinition*.

== Domain implementation

The domain model is implemented by extending the {url-javadoc}{framework-domain}/is/codion/framework/domain/DomainModel.html[DomainModel] class and populating it with *EntityDefinitions* based on the domain tables.
An *EntityDefinition* consists of *AttributeDefinitions* based on the *Attributes* associated with the entity and the information required to persist and present the entity.

The *EntityType* and *Attribute* constants provide *define()* methods returning builders which allow for further configuration (such as nullability and maximum length for values and the caption and primary key generator for the entity definition).

TIP: Omitting a caption marks an attribute as hidden. Hidden attributes won’t appear in table views by default.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/minimal/ManualDomainModel.java[tags=storeImpl]
----

<1> The *DomainType* constant is a required constructor parameter.

{url-javadoc}{framework-domain}/is/codion/framework/domain/Domain.html[Domain] is a https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html[Service Provider Interface (SPI)], and it is recommended to configure the domain implementation class for the https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/ServiceLoader.html[Service Loader]. Without the Service Loader you are restricted to a local JDBC connection, since you must manually provide a domain instance when establishing a connection, instead of just referring to the *DomainType* constant.

_src/main/java/module-info.java_

[source]
----
provides is.codion.framework.domain.Domain
          with is.codion.demos.store.domain.StoreImpl;
----

or if not using Java Modules (JPMS)

_src/main/resources/META-INF/services/is.codion.framework.domain.Domain_

[source]
----
is.codion.demos.store.domain.StoreImpl
----

NOTE: The domain model implementation must be on the classpath when running with a local JDBC connection, but when running with an RMI or HTTP connection the domain model API is sufficient.
If you foresee using RMI or HTTP connections it is recommended to split your domain model into separate API and implementation modules, to simplify client configurations (see https://github.com/codion-is/chinook[Chinook] and https://github.com/codion-is/world[World] demo applications, see https://github.com/codion-is/petclinic[Petclinic] for a simple single class domain model).

The domain model provides an {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/Entities.html[Entities] instance via {url-javadoc}{framework-domain}/is/codion/framework/domain/Domain.html#entities{opar}{cpar}[entities()], which contains the entity definitions and serves as a factory for *Entity* and *Entity.Key* instances.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/minimal/ManualDomainModel.java[tags=domainUsage]
----

== Data type mapping

[cols="1,3"]
|===
|Java type|SQL type

|Short|java.sql.Types.SMALLINT
|Integer|java.sql.Types.INTEGER
|Double|java.sql.Types.DOUBLE
|Long|java.sql.Types.BIGINT
|BigDecimal|java.sql.Types.DECIMAL
|LocalDateTime|java.sql.Types.TIMESTAMP
|LocalDate|java.sql.Types.DATE
|LocalTime|java.sql.Types.TIME
|OffsetTime|java.sql.Types.TIME_WITH_TIMEZONE
|OffsetDateTime|java.sql.Types.TIMESTAMP_WITH_TIMEZONE
|java.util.Date|java.sql.Types.DATE
|java.sql.Time|java.sql.Types.TIME
|java.sql.Date|java.sql.Types.DATE
|java.sql.Timestamp|java.sql.Types.TIMESTAMP
|String|java.sql.Types.VARCHAR
|Boolean|java.sql.Types.BOOLEAN
|Character|java.sql.Types.CHAR
|byte[]|java.sql.Types.BLOB
|===

[#_foreign_keys]
== Foreign keys

=== Examples

A simple foreign key based on a single column.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/api/World.java[tags=foreignKeyCapital]
----

Foreign key based on a composite key.

[source,java]
----
interface Parent {
  EntityType<Entity> TYPE = DOMAIN.entityType("parent");

  Column<Integer> ID_1 = TYPE.integerColumn("id1");
  Column<Integer> ID_2 = TYPE.integerColumn("id2");
}

interface Child {
  EntityType<Entity> TYPE = DOMAIN.entityType("child");

  Column<Integer> PARENT_ID_1 = TYPE.integerColumn("parent_id1");
  Column<Integer> PARENT_ID_2 = TYPE.integerColumn("parent_id2");

  ForeignKey PARENT_FK = TYPE.foreignKey("parent",
          PARENT_ID_1, Parent.ID_1,
          PARENT_ID_2, Parent.ID_2);
}
----

Domain constant definitions for the World demo application (simplified).

[source,java]
----
include::{dir-source}/is/codion/manual/world/domain/World.java[tags=entityTypesAndAttributes]
----

[#_attributes]
== Attributes

For the framework to know how to present and persist values, *Attributes* need further configuration.
Each attribute is represented by the {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/AttributeDefinition.html[AttributeDefinition] class or one of its subclasses, which encapsulates the required metadata.

The *Attribute*, *Column* and *ForeignKey* classes provide methods for creating *AttributeDefinition.Builder* instances, which can be used to configure the attributes.

An *Attribute* can be configured three ways, as transient, derived or denormalized.

=== Transient

Transient attributes are nullable by default and behave like regular fields, but do not map to any underlying column. Transient attributes are always initialized with a null value. Changing the value of a transient attribute renders the Entity instance modified by default, but can be configured to not do so.

=== Denormalized

An entity can include a read-only attribute value from an entity referenced via foreign key, by defining a denormalized attribute.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=denormalizedAttribute]
----

=== Derived

A derived attribute is used to represent a value which is derived from one or more attributes in the same entity.
The value of a derived attribute is provided via a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/DerivedValue.html[DerivedValue] implementation as shown below.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=derivedAttribute]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/api/World.java[tags=derivedValue]
----

== Columns

=== Column

Column is used to represent attributes that are based on table columns.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=column]
----

==== Lazy loading

A column can be specified as being not selected, which means its value is not selected by default.
Note that entitities contain a null value by default for lazy loaded columns.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=lazy]
----

=== Primary key

It is recommended that entities have a primary key defined, that is, one or more columns representing a unique combination.

The primary key defined in the domain model does not have to correspond to an actual table primary (or unique) key, although that is of course preferable.

If no primary key columns are specified, *equals()* will not work (since it is based on the primary key).
You can still use the *Entity.equalValues()* method to check if all values are equal in two entities without primary keys.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=primaryKey]
----

In case of composite primary keys you simply specify the primary key index.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=compositePrimaryKey]
----

=== Subquery

A Column can represent a subquery returning a single value.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=subqueryColumn]
----

=== Boolean

For databases supporting *Types.BOOLEAN* you simply specify a column.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=booleanColumn]
----

For databases lacking native boolean support we can define a boolean column and provide a converter.

[source,java,indent=0]
----
include::{dir-petstore-source}/is/codion/demos/petstore/domain/Petstore.java[tags=booleanColumn]
----

[source,java,indent=0]
----
include::{dir-petstore-source}/is/codion/demos/petstore/domain/Petstore.java[tags=booleanConverter]
----

Note that boolean attributes always use the boolean Java type, the framework handles translating to and from the actual column values.

[source,java]
----
entity.set(Customer.ACTIVE, true);

Boolean isActive = entity.get(Customer.ACTIVE);
----

=== Item

A column based on a list of valid items.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=items]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=item]
----

=== Group by

Codion provides built-in support for grouped entities through column-level `groupBy()` and `aggregate()` configuration. This is the preferred approach for working with aggregated data, offering type-safe aggregate column handling and automatic HAVING clause generation in the model layer.

==== Defining grouped entities

A grouped entity is defined by marking columns as either group-by columns or aggregate columns:

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=groupBy]
----

Key points about grouped entities:

* **Group-by columns**: Marked with `.groupBy(true)` - these columns appear in the GROUP BY clause
* **Aggregate columns**: Marked with `.aggregate(true)` and must specify an `.expression()` containing the aggregate function (e.g., `sum(surfacearea)`, `min(lifeexpectancy)`)
* **All columns required**: Every column must be either a group-by column or an aggregate column - the framework validates this at entity definition time
* **Read-only**: Grouped entities are typically marked `.readOnly(true)` since aggregated data cannot be updated
* **Base table**: Use `.table()` to specify the underlying table (e.g., `.table("world.country")`) in case the `entityType` name is different.

==== Querying grouped entities

When using grouped entities, the framework handles aggregate columns differently than regular columns:

**In the connection layer (Select.Builder):**

Conditions on aggregate columns must be explicitly added to the HAVING clause:

[source,java]
----
// Regular column condition - goes in WHERE clause automatically
connection.select(Select.where(Continent.NAME.equalTo("Europe")).build());

// Aggregate column condition - must use having() explicitly
connection.select(Select.having(Continent.POPULATION.greaterThan(100_000_000L)).build());
----

**In the model layer ({url-javadoc}{framework-model}/is/codion/framework/model/EntityTableConditionModel.html[EntityTableConditionModel]):**

The framework model layer automatically handles aggregate columns - conditions on aggregate columns are automatically placed in the HAVING clause without explicit configuration:

[source,java]
----
SwingEntityTableModel continentModel = new SwingEntityTableModel(Continent.TYPE, connectionProvider);

// Condition on regular column (NAME) - automatically goes in WHERE
continentModel.queryModel().condition().get(Continent.NAME).set().equalTo("Asia");

// Condition on aggregate column (POPULATION) - automatically goes in HAVING
continentModel.queryModel().condition().get(Continent.POPULATION).set().greaterThan(1_000_000_000L);

// Both conditions work together correctly
continentModel.items().refresh();
----

This automatic HAVING clause handling makes grouped entities seamless to use in UI components.

==== When to use grouped entities vs. custom queries

**Prefer grouped entities when:**

* Working with straightforward aggregations on a single table
* Building interactive UIs where users filter aggregated data
* You want automatic HAVING clause handling in table models
* Type-safe access to aggregate columns is important

**Use custom queries ({url-javadoc}{framework-domain}/is/codion/framework/domain/entity/query/EntitySelectQuery.html[EntitySelectQuery]) when:**

* Aggregating across complex joins of multiple tables
* The query requires custom SQL logic beyond standard GROUP BY
* You need database-specific optimizations or hints

**Prefer database views when:**

* The aggregation is complex and performance-critical
* Multiple applications need the same aggregated data
* DBAs need to optimize with indexes or materialized views
* The aggregation logic is stable and rarely changes

=== Column templates

Column templates provide a way to define reusable column configurations that can be applied across multiple entities. This eliminates repetition and ensures consistency for common patterns like audit columns, required searchable fields, or domain-specific column types.

Templates are defined using the {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/ColumnTemplate.html[ColumnTemplate] functional interface, which extends `Function<Column<T>, ColumnDefinition.Builder<T, ?>>`.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/domain/ChinookImpl.java[tags=columnTemplates]
----

The templates above demonstrate common patterns:

* `REQUIRED_SEARCHABLE` - Combines nullable(false) with searchable(true) for required fields that should be used in search fields.
* `INSERT_TIME` and `INSERT_USER` - Audit columns that track when and by whom records were created, using shared resource bundle keys for consistent captions across entities

Templates are applied using the `column(ColumnTemplate<T>)` method:

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/domain/ChinookImpl.java[tags=columnTemplateUsage1]
----

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/domain/ChinookImpl.java[tags=columnTemplateUsage2]
----

Templates can be chained with additional configuration methods, allowing you to apply a base configuration and then customize specific aspects as needed.

Templates can be based on constants or static methods for more flexibility.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/domain/Examples.java[tags=columnTemplates]
----

This approach provides several benefits:

* **Parameterization** - Templates can accept configuration parameters at usage time
* **Reusability** - Common patterns can be shared across different domains with variations
* **Environment awareness** - Templates can adapt based on runtime configuration
* **Type safety** - The method signature ensures correct types for parameters
* **Documentation** - Method parameters make the configuration options explicit

==== Real-world example: Geospatial column templates

Column templates are particularly powerful when working with complex data types that require converters and custom formatting. Here's an example from production applications using PostGIS geometries:

[source,java]
----
public final class GeospatialTemplates {

    // Template for Point geometries with custom formatting
    public static final ColumnTemplate<Point> POINT = column ->
        column.define()
            .column()
            .converter(PGgeometry.class, new PGgeometryPointConverter(), new PGgeometryGetter())
            .format(new PointFormat());

    // Template for LineString geometries
    public static final ColumnTemplate<LineString> LINE = column ->
        column.define()
            .column()
            .converter(PGgeometry.class, new PGgeometryLineConverter(), new PGgeometryGetter());

    // Template for Polygon geometries
    public static final ColumnTemplate<Polygon> POLYGON = column ->
        column.define()
            .column()
            .converter(PGgeometry.class, new PGgeometryPolygonConverter(), new PGgeometryGetter());

    // Template for MultiPolygon geometries
    public static final ColumnTemplate<MultiPolygon> MULTI_POLYGON = column ->
        column.define()
            .column()
            .converter(PGgeometry.class, new PGgeometryMultiPolygonConverter(), new PGgeometryGetter());
}

// Usage in entity definitions:
EntityDefinition location() {
    return Location.TYPE.define(
        Location.ID.define()
            .primaryKey(),
        Location.NAME.define()
            .column()
            .nullable(false),
        Location.COORDINATES.define()
            .column(GeospatialTemplates.POINT),
        Location.BOUNDARY.define()
            .column(GeospatialTemplates.POLYGON),
        Location.ROUTE.define()
            .column(GeospatialTemplates.LINE))
    .build();
}
----

These templates demonstrate how column templates can:

* **Encapsulate complexity** - The converter, getter, and formatter classes can remain private implementation details
* **Ensure consistency** - All geometry columns of the same type use identical configuration
* **Reduce boilerplate** - Complex type configuration is defined once and reused everywhere
* **Improve maintainability** - Changes to geometry handling are centralized in the template definitions

== Domain

Each entity is defined by creating a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.Builder.html[EntityDefinition.Builder] instance via {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityType.html#define{opar}is.codion.framework.domain.entity.attribute.AttributeDefinition.Builder\...{cpar}[EntityType.define()] and adding the resulting definition to the domain model, via the {url-javadoc}{framework-domain}/is/codion/framework/domain/DomainModel.html#add{opar}is.codion.framework.domain.entity.EntityDefinition{cpar}[add(EntityDefinition)] method in the {url-javadoc}{framework-domain}/is/codion/framework/domain/DomainModel.html[DomainModel] class.
The framework assumes the *entityType* name is the underlying table name, but the *tableName* can be specified via {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.Builder.html#tableName{opar}java.lang.String{cpar}[EntityDefinition.Builder.tableName(String)] method.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=defineCity]
----

=== Examples

* <<{dir-tutorials}/world/world.adoc#_domain_model, World domain model>>
* <<{dir-tutorials}/employees/employees.adoc#_domain_model, Employees domain model>>
* <<{dir-tutorials}/chinook/chinook.adoc#_domain_model, Chinook domain model>>
* <<{dir-tutorials}/petstore/petstore.adoc#_domain_model, Petstore domain model>>

[#_generator]
== Generator

The framework provides implementations for most commonly used primary key generation strategies, identity column, sequence (with or without trigger) and auto-increment columns.
The {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Column.Generator.html[Generator] class serves as a factory for {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Column.Generator.html[Generator] implementations.
Static imports are assumed in the below examples.

=== Identity

Based on identity columns, supported by most DBMSs.

[source,java,indent=0]
----
include::{dir-chinook-source}/is/codion/demos/chinook/domain/ChinookImpl.java[tags=identity]
----

=== Automatic

This assumes the underlying column is either an auto-increment column or is populated from a sequence using a trigger during insert.

[source,java]
----
//Auto increment column in the 'store.customer' table
.generator(automatic("store.customer"));

//Trigger and a sequence named 'store.customer_seq'
.generator(automatic("store.customer_seq"));
----

=== Sequence

When sequences are used without triggers the framework can fetch the value from a sequence before insert.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=sequence]
----

=== Queried

The framework can select new primary key values from a query.

[source,java]
----
.generator(queried("""
        select next_id
        from store.id_values
        where table_name = 'store.customer'"""))
----

=== Custom

You can provide a custom key generator strategy by implementing a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Column.Generator.html[Generator].

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/domain/Store.java[tags=generator]
----

== EntityFormatter

The {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityFormatter.html[EntityFormatter] class provides a builder for a *Function<Entity, String>* instance, which is then used to provide the *toString()* implementations for entities.
This value is used wherever entities are displayed, for example in a ComboBox or as foreign key values in table views.

*Entity.toString()* values are cached by default and invalidated each time an attribute value changes. This caching can be turned off via {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityDefinition.Builder.html#cacheToString{opar}boolean{cpar}[EntityDefinition.Builder.cacheToString(boolean)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/domain/Store.java[tags=address]
----

For more complex toString() implementations you can implement a custom *Function<Entity, String>*.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/domain/Store.java[tags=customerFormatter]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/domain/Store.java[tags=customerFormatter]
----

== Validation

Custom validation of Entities is performed by implementing a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/EntityValidator.html[EntityValidator].

The *EntityValidator* interface provides range, string length and null validation and can be extended to provide further validations.

WARNING: EntityValidator logic runs frequently — avoid expensive operations like database queries. Use edit model listeners (such as `beforeInsert` or `beforeUpdate`) for validations that require cross-entity or remote checks.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/api/World.java[tags=validator]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=validator]
----

== Examples

* <<{dir-tutorials}/employees/employees.adoc#_domain, Employees domain model>>
* <<{dir-tutorials}/chinook/chinook.adoc#_domain, Chinook domain model>>
* <<{dir-tutorials}/petstore/petstore.adoc#_domain, Petstore domain model>>

== Custom data types

When using a custom data type you must specify the *columnClass* of a ColumnDefinition and provide a {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/attribute/Column.Converter.html[Converter] implementation.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/api/World.java[tags=customType]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/api/World.java[tags=customTypeClass]
----

NOTE: The custom type must be serializable for use in an application using the RMI connection.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=columnClass]
----

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/WorldImpl.java[tags=converter]
----

When using the HTTP connection in an application using a custom data type, you must implement a {url-javadoc}{framework-json-domain}/is/codion/framework/json/domain/EntityObjectMapperFactory.html[EntityObjectMapperFactory], providing a {url-javadoc}{framework-json-domain}/is/codion/framework/json/domain/EntityObjectMapper.html[EntityObjectMapper] instance containing a serializer/deserializer for the custom types.

[source,java,indent=0]
----
include::{dir-world-source}/is/codion/demos/world/domain/api/WorldObjectMapperFactory.java[tags=customSerializer]
----

This *EntityObjectMapperFactory* must be exposed to the ServiceLoader.

_src/main/java/module-info.java_

[source]
----
include::{dir-world-source}/module-info.java[tag=customSerializer]
----

See <<{dir-tutorials}/world/world.adoc#_domain, World domain model>>

== Custom select queries

When an entity's data cannot be adequately represented by a single table, you may need to customize the SELECT query used to populate entities. The {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/query/EntitySelectQuery.html[EntitySelectQuery] class provides this capability through its builder API.

IMPORTANT: Custom select queries should be used as an **escape hatch** when other approaches have been considered and rejected. In most cases, creating a database view is the preferred solution - views can be optimized by database administrators, tested independently, and changed without modifying application code. Use `EntitySelectQuery` when views are impractical due to deployment constraints (such as migration risks in production environments) or when the query logic needs to be version-controlled with the application code.

=== When to use custom select queries

Consider using `EntitySelectQuery` when:

* **Database views are impractical** - Deployment environments where schema migrations carry significant risk (offline systems, mission-critical applications)
* **Application-specific logic** - Query patterns that are tightly coupled to application features and likely to evolve with the code
* **Rapid iteration** - During development when query logic is still being refined and database schema changes would slow progress
* **Multi-table joins** - Denormalizing data from related tables without creating a view

Consider using **database views** instead when:

* **Stable, foundational queries** - Well-established query patterns that rarely change
* **Cross-application usage** - Queries needed by multiple applications or reporting tools
* **DBA optimization** - Complex queries requiring database-specific hints, indexes, or performance tuning
* **Production stability** - Mission-critical systems where application code changes are safer than schema migrations

=== Custom FROM clause

The most common use case is customizing the FROM clause to join additional tables, allowing you to include columns from related tables without using foreign key references.

[source,java]
----
include::{dir-source}/is/codion/manual/framework/domain/CustomSelectQueries.java[tags=fromClause]
----

NOTE: Always mark denormalized values as `readOnly(true)`.

In this example, the Track entity includes `album_title` and `artist_name` columns by joining the album and artist tables. The framework automatically generates the SELECT and WHERE clauses based on the column definitions.

NOTE: The {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/query/EntitySelectQuery.Builder.html#columns(java.lang.String)[columns()] method is rarely needed - the framework constructs the SELECT clause from column definitions using their `expression()` values, which typically works correctly. Only specify `columns()` when you need non-standard column expressions or aliases.

=== GROUP BY and aggregation

NOTE: For aggregated data on a single table, use Codion's built-in <<_group_by,grouped entity support>> with `.groupBy(true)` and `.aggregate(true)` at the column level. This provides type-safe aggregate column handling and automatic HAVING clause generation. Use `EntitySelectQuery` with `groupBy()` only when aggregating across complex joins of multiple tables.

The framework includes aggregate expressions from column definitions in the SELECT clause. Entities representing aggregated data should be marked as read-only.

=== Static WHERE clause

Use the `where()` method to apply a static filter that applies to all queries for this entity:

[source,java]
----
include::{dir-source}/is/codion/manual/framework/domain/CustomSelectQueries.java[tags=whereClause]
----

IMPORTANT: The WHERE clause specified in `EntitySelectQuery` is always included and automatically combined (using AND) with any dynamic conditions from the {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/condition/Condition.html[Condition] framework. This allows static filtering (like `active = 1`) to coexist with dynamic user-driven filters.

=== Best practices

When using custom select queries:

* **Mark entities as read-only** - Entities based on joins or aggregations typically cannot be updated: `.readOnly(true)`
* **Avoid specifying columns** - Let the framework generate the SELECT columns clause from column definitions unless you need special expressions
* **Watch out for ambiguous column names ** - Use `.expression()` when column names become ambiguous due to joins
* **Use table aliases carefully** - Ensure column expressions in attribute definitions match the aliases used in your FROM clause
* **Test thoroughly** - Custom queries bypass some framework validations, so verify behavior with actual data
* **Document the rationale** - Include comments explaining why a custom query is used instead of a view

This pattern is useful when you frequently need data from related tables and want to avoid the overhead of foreign key lookups, while maintaining the option to use a database view in the future if the query becomes performance-critical.

== Domain composition

Domain models can be composed of other domain models, allowing you to build modular, reusable domain definitions. This composition can be complete (including all entity definitions) or selective (cherry-picking specific entities or functionality).

=== Complete composition

The simplest form of composition is to include an entire domain model within another. This is done by passing a domain instance to the `add()` method in the constructor.

[source,java]
----
include::{dir-source}/is/codion/manual/framework/domain/Composition.java[tag=composition]
----

In this example:

* The `Products` domain defines a single `Product` entity
* The `Orders` domain includes the entire `Products` domain via `add(new Products())` and adds its own `Customer` and `Order` entities
* The `Store` domain includes the entire `Orders` domain (which transitively includes `Products`) and adds an `Employee` entity
* The resulting `Store` domain contains all entities from all three domains: `Product`, `Customer`, `Order`, and `Employee`
* Foreign key references can cross domain boundaries - `Order.PRODUCT_FK` references `Product.ID` from the composed `Products` domain

This hierarchical composition allows you to:

* Build complex domains from smaller, focused components
* Reuse domain definitions across different applications
* Maintain clear separation of concerns between different parts of your model
* Establish cross-domain relationships through foreign keys

=== Selective composition

For more fine-grained control, you can selectively include specific entities or functionality from other domains:

[source,java]
----
include::{dir-source}/is/codion/manual/framework/domain/Composition.java[tag=selectiveComposition]
----

Selective composition provides several specialized methods:

* `add(EntityDefinition)` - Adds a specific entity definition from another domain
* `addReports(Domain)` - Includes only the reports from another domain
* `addFunctions(Domain)` - Includes only the functions from another domain
* `addProcedures(Domain)` - Includes only the procedures from another domain

This approach is useful when:

* Building a subset of functionality for specific clients (e.g., a public website vs. internal admin application)
* Sharing database functions/procedures across different domain models
* Creating lightweight domain models that reference only the entities they actually use
* Avoiding circular dependencies between domain modules

NOTE: When selectively adding entity definitions, ensure that any foreign key references are satisfied - if an entity references another via foreign key, both entities must be included in the domain.

== Entities in action

Using the Entity class is rather straight forward.

[source,java,indent=0]
----
include::{dir-petstore-source}/is/codion/demos/petstore/manual/EntitiesInAction.java[tags=entitiesInAction]
----

[#_domain_unit_testing]
== Unit Testing

=== Introduction

To unit test the CRUD operations on the domain model extend {url-javadoc}{framework-domain-test}/is/codion/framework/domain/test/DomainTest.html[DomainTest].

The unit tests are run within a single transaction which is rolled back after the test finishes, so these tests are pretty much guaranteed to leave no junk data behind.

=== DomainTest

The DomainTest uses a default {url-javadoc}{framework-domain-test}/is/codion/framework/domain/test/DefaultEntityFactory.html[EntityFactory] implementation which provides test entities with randomly created values, based on the value constraints set in the domain model. Extend this class and pass to the super constructor, overriding the required methods.

* {url-javadoc}{framework-domain-test}/is/codion/framework/domain/test/DomainTest.EntityFactory.html#foreignKey{opar}is.codion.framework.domain.entity.attribute.ForeignKey{comma}java.util.Map{cpar}[foreignKey] should return an entity instance for the given foreign key to use for a foreign key reference required for inserting the entity being tested.
* {url-javadoc}{framework-domain-test}/is/codion/framework/domain/test/DomainTest.EntityFactory.html#entity{opar}is.codion.framework.domain.entity.EntityType{comma}java.util.Map{cpar}[entity] should return an entity to use as basis for the unit test, that is, the entity that should be inserted, selected, updated and finally deleted.
* {url-javadoc}{framework-domain-test}/is/codion/framework/domain/test/DomainTest.EntityFactory.html#modify{opar}is.codion.framework.domain.entity.Entity{comma}java.util.Map{cpar}[modify] should simply leave the entity in a modified state so that it can be used for update test, since the database layer throws an exception if an unmodified entity is updated.
If *modify* returns an unmodified entity, the update test is skipped.

To run the full CRUD test for a domain entity you need to call the *test(EntityType entityType)* method with the entity type as parameter.
You can either create a single *testDomain()* method and call the *test* method in turn for each entityType or create a *entityName* method for each domain entity, as we do in the example below.

[source,java]
----
include::{dir-test-source}/is/codion/manual/store/domain/StoreTest.java[tags=storeTest]
----

=== Examples

* <<{dir-tutorials}/employees/employees.adoc#_domain_unit_test, Employees domain model test>>
* <<{dir-tutorials}/chinook/chinook.adoc#_domain_unit_test, Chinook domain model test>>
* <<{dir-tutorials}/petstore/petstore.adoc#_domain_unit_test, Petstore domain model test>>