= EntityEditModel
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

[plantuml,entity-edit-model-diagram,svg,align=center]
-------------------------------------------
skinparam genericDisplay old

interface EntityEditModel {
    +<T> Value<T> value(Attribute<T> attribute)
    +Mutable<Entity> entity()
    +Entity insert()
    +Entity update()
    +Entity delete()
}
-------------------------------------------

The {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] interface defines the CRUD business logic used by the {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] class when entities are being edited.
The *EntityEditModel* works with a single entity instance, which can be retrieved and set via the {url-javadoc}{common-core}/is/codion/common/observer/Mutable.html[Mutable<Entity>] instance accessible via the {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html#entity{opar}{cpar}[entity()] method.
The *EntityEditModel* interface exposes a number of methods for manipulating as well as querying the values of the active entity.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/model/CustomerEditModel.java[tags=customerEditModel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/Misc.java[tags=editModel]
----