= EntityTablePanel
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

The {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityTablePanel.html[EntityTablePanel] provides a table view of entities.

[#_adding_a_print_action]
== Adding a print action

The most common place to add a custom control is the table popup menu, i.e. an action for printing reports or for acting on the selected rows.
For the simplest case, where a single print action is required, a custom control can be associated with the *PRINT* ControlKey, this control will appear in the Print submenu in the table popup menu as well as on the table toolbar.

For more complex cases, where multiple print controls are required, custom controls can be associated with the *PRINT_CONTROLS* ControlKey.

[source,java]
----
include::{dir-source}/is/codion/manual/store/ui/CustomerTablePanel.java[tags=customerTablePanel]
----

== Exporting Data

A configurable denormalized data export tool can be included in the EntityTablePanel **Copy** table popup submenu.

It can be enabled globally via the {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityTablePanel.Config.html#INCLUDE_EXPORT[EntityTablePanel.Config.INCLUDE_EXPORT] configuration value or for a single panel via the panel configuration.

The active export configuration is saved in user preferences on application exit.

== Query Inspector

A *Query Inspector* can be enabled globally via the {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityTablePanel.Config.html#INCLUDE_QUERY_INSPECTOR[EntityTablePanel.Config.INCLUDE_QUERY_INSPECTOR] configuration value or for a single panel via the panel configuration.

The *Query Inspector* displays the SELECT query, dynamically updated according to the underlying query conditions.

[source,java]
----
EntityTablePanel.Config.INCLUDE_QUERY_INSPECTOR.set(true);
----

The *Query Inspector* can be opened using the CTRL-ALT-Q keyboard shortcut, when the table panel is focused.