[#_entityeditpanel]
= EntityEditPanel
:dir-chinook-source: ../../../../../demos/chinook/src/main/java
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

The {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditPanel.html[EntityEditPanel] manages the input components (text fields, combo boxes and such) for editing an entity instance.

When extending an *EntityEditPanel* you must implement the *initializeUI()* method, which initializes the edit panel UI.
The *EntityEditPanel* class exposes methods for creating input components and linking them to the underlying {url-javadoc}{framework-model}/is/codion/framework/model/EntityEditModel.html[EntityEditModel] instance.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/ui/CustomerEditPanel.java[tags=customerEditPanel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/ui/AddressEditPanel.java[tags=addressEditPanel]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/ui/CustomerAddressEditPanel.java[tags=customerAddressEditPanel]
----

== Detailed example

Here's how a text field is created and added to the edit panel.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/ui/EditPanelDemo.java[tags=basic]
----

And here's the equivilent code, showing what's going on behind the scenes.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/store/ui/EditPanelDemo.java[tags=expanded]
----

== Input controls

=== Boolean

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createBooleanComboBox(is.codion.framework.domain.entity.attribute.Attribute)[createBooleanComboBox(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createCheckBox(is.codion.framework.domain.entity.attribute.Attribute)[createCheckBox(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=booleanValue]
----

=== Foreign key

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createComboBox(is.codion.framework.domain.entity.attribute.ForeignKey)[createComboBox(foreignKey)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createSearchField(is.codion.framework.domain.entity.attribute.ForeignKey)[createSearchField(foreignKey)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextField(is.codion.framework.domain.entity.attribute.ForeignKey)[createTextField(foreignKey)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createEntityLabel(is.codion.framework.domain.entity.attribute.ForeignKey)[createEntityLabel(foreignKey)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=foreignKeyValue]
----

=== Temporal

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTemporalFieldPanel(is.codion.framework.domain.entity.attribute.Attribute)[createTemporalFieldPanel(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createLocalDateField(is.codion.framework.domain.entity.attribute.Attribute)[createLocalDateField(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=temporalValue]
----

=== Numerical

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=numericalValue]
----

=== Text

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextField(is.codion.framework.domain.entity.attribute.Attribute)[createTextField(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createMaskedTextField(is.codion.framework.domain.entity.attribute.Attribute)[createMaskedTextField(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextArea(is.codion.framework.domain.entity.attribute.Attribute)[createTextArea(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createTextInputPanel(is.codion.framework.domain.entity.attribute.Attribute)[createTextInputPanel(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=textValue]
----

=== Selection

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createComboBox(is.codion.framework.domain.entity.attribute.Attribute,javax.swing.ComboBoxModel)[createComboBox(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=selectionValue]
----

=== Items

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createItemComboBox(is.codion.framework.domain.entity.attribute.Attribute)[createItemComboBox(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=item]
----

== Panels & labels

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createLabel(is.codion.framework.domain.entity.attribute.Attribute)[createLabel(attribute)]

{url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditComponentPanel.html#createInputPanel(is.codion.framework.domain.entity.attribute.Attribute)[createInputPanel(attribute)]

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/framework/EntityEditPanels.java[tags=panelLabel]
----

== Advanced Patterns

=== Configuration Options

EntityEditPanel supports configuration via a lambda in the constructor:

[source,java]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/FrameworkUIDemo.java[tags=editPanelConfiguration]
----

=== Focus Management

Configure the focus behaviour:

[source,java]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/FrameworkUIDemo.java[tags=editPanelFocusManagement]
----

=== Inline Edit Panels with ComboBoxPanel

Create combo boxes with inline add/edit capabilities:

[source,java]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/FrameworkUIDemo.java[tags=editPanelComboBoxPanel]
----

=== Custom Component Integration

Using custom components:

[source,java]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/FrameworkUIDemo.java[tags=editPanelCustomComponent]
----

=== Keyboard Shortcuts and Actions

Add custom keyboard shortcuts for enhanced productivity:

[source,java]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/FrameworkUIDemo.java[tags=editPanelKeyboardShortcuts]
----

=== Detail Panel Integration

EntityEditPanel can include detail panels for master-detail relationships:

[source,java]
----
include::{dir-chinook-source}/is/codion/demos/chinook/manual/FrameworkUIDemo.java[tags=editPanelDetailIntegration]
----

== Custom actions

The action mechanism used throughout the Codion framework is based on the {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/control/Control.html[Control] class and its subclasses and the {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/control/Controls.html[Controls] class which represents a collection of controls.

[#_edit_query_inspector]
== Query Inspector

A *Query Inspector* can be enabled globally via the {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditPanel.Config.html#INCLUDE_QUERY_INSPECTOR[EntityEditPanel.Config.INCLUDE_QUERY_INSPECTOR] configuration value or for a single panel via the panel configuration.

The *Query Inspector* displays INSERT and UPDATE queries, dynamically updated according to the current edit panel state.

[source,java]
----
EntityEditPanel.Config.INCLUDE_QUERY_INSPECTOR.set(true);
----

The Query Inspector can be opened using the CTRL-ALT-Q keyboard shortcut, when the edit panel is focused.