[#_entitypanel]
= EntityPanel
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

[plantuml, entity-panel-diagram, svg, align=center]
-------------------------------------------
class EntityPanel {
    +EntityEditPanel editPanel()
    +EntityTablePanel tablePanel()
    +Collection<EntityPanel> detailPanels()
}

EntityPanel --o EntityEditPanel
EntityPanel --o EntityTablePanel
EntityPanel --o EntityPanel
-------------------------------------------

The {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityPanel.html[EntityPanel] is the base UI class for working with entity instances. It usually consists of an {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityTablePanel.html[EntityTablePanel], an {url-javadoc}{swing-framework-ui}/is/codion/swing/framework/ui/EntityEditPanel.html[EntityEditPanel], and a set of detail panels representing the entities having a master/detail relationship with the underlying entity.

== Detail panels

Adding a detail panel is done with a single method call, but note that the underlying EntityModel must contain the correct detail model for the detail panel, in this case a *CustomerModel* instance, see link:#_detail_models[detail models]. See link:#_entityapplicationpanel[EntityApplicationPanel].