[#_input_components]
= Input Components
:dir-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

Binding model data to UI components is accomplished by linking a {url-javadoc}{common-reactive}/is/codion/common/reactive/value/Value.html[Value] instance to an instance of its subclass {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/value/ComponentValue.html[ComponentValue], which represents a value based on an input component.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=basics]
----

== Text

=== TextField

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=stringField]
----

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=characterField]
----

=== TextArea

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=textArea]
----

== Numbers

=== Integer

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=integerField]
----

=== Long

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=longField]
----

=== BigInteger

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=bigIntegerField]
----

=== Double

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=doubleField]
----

=== BigDecimal

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=bigDecimalField]
----

== Date & Time

=== LocalTime

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=localTime]
----

=== LocalDate

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=localDate]
----

=== LocalDateTime

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=localDateTime]
----

== Boolean

=== CheckBox

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=checkBox]
----

=== NullableCheckBox

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=nullableCheckBox]
----

=== ComboBox

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=booleanComboBox]
----

== Selection

=== ComboBox

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=selectionComboBox]
----

==== FilterComboBoxModel

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=filterComboBoxModel]
----

==== Completion

{url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/combobox/Completion.html[Completion] provides a way to enable completion for combo boxes.

The available completion modes are:

{url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/combobox/Completion.Mode.html[Completion.Mode#AUTOCOMPLETE]

{url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/combobox/Completion.Mode.html[Completion.Mode#MAXIMUM_MATCH]

Combo boxes created via {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/Components.html[Components] have completion enabled by default, with {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/combobox/Completion.Mode.html[MAXIMUM_MATCH] being the default completion mode.

The default completion mode is controlled via the {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/combobox/Completion.html#COMPLETION_MODE.html[Completion.COMPLETION_MODE] configuration value.

===== Normalization

Strings are normalized by default during completion, that is, accents are removed, i.e. *á*, *í* and *ú* become *a*, *i* and *u*. To enable accented character sensitivity, normalization can be turned off, either globally via the {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/combobox/Completion.html#NORMALIZE.html[Completion.NORMALIZE] configuration value or individually via the combo box builder.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=comboBoxCompletion]
----

== Custom

=== TextField

In the following example we link a value based on a Person class to a component value displaying text fields for a first and last name.

[source,java,indent=0]
----
include::{dir-source}/is/codion/manual/common/InputControls.java[tags=customTextFields]
----

== Examples

<<{basedir}/tutorials/input-components.adoc#_input_components, Input components>>