= Introduction
:docinfo: shared-head

== Features
* JMinor is a full stack framework, providing all the fundamental building blocks required for building a rich client CRUD application.
* JMinor is modular and minimalistic while being flexible and extensible.
* Few third-party dependencies.
* JMinor can be used as a library or a framework, whichever suits best.
* Includes a light-weight RMI/HTTP server to use when direct access to the database is not available.

== History
I started developing the framework way back in 2004, after I had given up trying to use a rich client framework recommended by a colleague. That framework was based on drag'n drop, wizard-driven development, which turned out to be absolutely horrifying for someone who really enjoys writing code. This was before the time of Spring, JOOQ, Hibernate and all these excellent frameworks, so I started from scratch, with the aim of using only link:++https://en.wikipedia.org/wiki/Java_Platform,_Standard_Edition++[Java Standard Edition] components, https://en.wikipedia.org/wiki/Java_Database_Connectivity[JDBC], https://en.wikipedia.org/wiki/Swing_(Java)[Swing] and https://en.wikipedia.org/wiki/Java_remote_method_invocation[RMI].