unique_constraint=This combination of values already exists
referential_integrity=The operation violates a foreign key constraint
parent_missing=A foreign key value has no matching primary key value
child_exists=This record is referenced by records in other tables, delete those first
null_value=Value missing
check_constraint=The value or values attempted to be entered in a field or fields violate a defined check constraint
value_too_large=The value entered is larger than the maximum defined for the column
missing_privileges=You are not authorized to perform this action
authentication=Invalid username or password
row_locked=This record is being modified by another user
timeout=The operation timed out
table_not_found=Table or view does not exist
view_has_errors=View has errors
