= Quickstart
:docinfo: shared-head
:dir-source: ../../../../demos/manual/src/main/java
:dir-source-sql: ../../../../demos/manual/src/main/sql

== Rich client
Codion is primarily a Swing based framework, the Swing client is mature and stable while the JavaFX client is quite rudimentary and still in the 'proof-of-concept' stage. The below artifacts pull in all required framework dependencies.

[cols="1,4"]
|===
|Client|Artifact

|Swing|dev.codion.{codion-jdk}:codion-swing-framework.ui:{codion-version}
|JavaFX|dev.codion.{codion-jdk}:codion-javafx-framework:{codion-version}
|===

== Database connectivity
A Codion client has three ways of connecting to a database, directly via a local JDBC connection or remotely via RMI or HTTP using the Codion remote server.

[cols="1,4"]
|===
|DB Connection|Artifact

|Local|dev.codion.{codion-jdk}:codion-framework-db-local:{codion-version}
|RMI|dev.codion.{codion-jdk}:codion-framework-db-rmi:{codion-version}
|HTTP|dev.codion.{codion-jdk}:codion-framework-db-http:{codion-version}
|===

== DBMS
When connecting to the database with a local JDBC connection the DBMS module for the underlying database must be on the classpath. Note that these artifacts do not depend on the JDBC drivers, so those must be added separately.

The most used and tested DBMS modules are:

1. Oracle
2. H2 Database
3. Postgresql

[cols="1,4"]
|===
|DBMS|Artifact

|Derby|dev.codion.{codion-jdk}:codion-dbms-derby:{codion-version}
|H2 Database|dev.codion.{codion-jdk}:codion-dbms-h2database:{codion-version}
|HSQL|dev.codion.{codion-jdk}:codion-dbms-hsql:{codion-version}
|MariaDB|dev.codion.{codion-jdk}:codion-dbms-mariadb:{codion-version}
|MySQL|dev.codion.{codion-jdk}:codion-dbms-mysql:{codion-version}
|Oracle|dev.codion.{codion-jdk}:codion-dbms-oracle:{codion-version}
|Postgresql|dev.codion.{codion-jdk}:codion-dbms-postgresql:{codion-version}
|SQLite|dev.codion.{codion-jdk}:codion-dbms-sqlite:{codion-version}
|SQL Server|dev.codion.{codion-jdk}:codion-dbms-sqlserver:{codion-version}
|===

== Logging
Codion uses SLF4J throughout so all you need to do is add a SLF4J bridge for your logging framework of choice to the classpath. If you use Logback or Log4J you can use one of the logging-proxy plugins below which will pull in the required dependencies and provide a main-menu action in the client for setting the logging level.

[cols="1,4"]
|===
|Logging|Artifact

|Logback|dev.codion.{codion-jdk}:codion-plugin-logback-proxy:{codion-version}
|Log4j|dev.codion.{codion-jdk}:codion-plugin-log4j-proxy:{codion-version}
|Java Util Logging|dev.codion.{codion-jdk}:codion-plugin-jul-proxy:{codion-version}
|===

== Gradle
[source,groovy,subs=attributes]
----
dependencies {
    //Swing client UI module
    implementation 'dev.codion.{codion-jdk}:codion-swing-framework-ui:{codion-version}'

    //JSON for persisting client preferences
    runtimeOnly 'dev.codion.{codion-jdk}:codion-plugin-json:{codion-version}'
    //Local JDBC connection module
    runtimeOnly 'dev.codion.{codion-jdk}:codion-framework-db-local:{codion-version}'
    //H2 DBMS module
    runtimeOnly 'dev.codion.{codion-jdk}:codion-dbms-h2database:{codion-version}'
    //H2 JDBC driver
    runtimeOnly 'com.h2database:h2:1.4.200'
    //Logging with Logback
    runtimeOnly 'dev.codion.{codion-jdk}:codion-plugin-logback-proxy:{codion-version}'

    //Domain model unit testing module
    testImplementation 'dev.codion.{codion-jdk}:codion-framework-domain-test:{codion-version}'
    //JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.0'
}
----

== Code examples

There are at minimum two steps involved in creating a Codion application:

  * Defining a domain model based on the underlying tables.
  * Creating edit panels for tables requiring CRUD functionality.

=== Domain

The Codion framework is based around the *Entity* class, a map-like structure, representing a row in a table. The domain is modelled much like an E/R diagram, with an *EntityDefinition* per table, a *Property* for each column and a *ForeignKeyProperty* for each foreign key relationship.

[cols="2,4"]
|===
|Module|Artifact
|dev.codion.framework.domain|dev.codion.{codion-jdk}:codion-framework-domain:{codion-version}
|===

==== Defining entities

The below examples are somewhat simplified, but functionally correct.

.View example schema SQL
[%collapsible]
====

NOTE: Not all columns are used in the example code below.

[source,sql,indent=0]
----
include::{dir-source-sql}/create_schema.sql[]
----
====

First we define a entity based on the table *store.customer*, using String constants to identify the entity type (the *entityId*) and its properties (*propertyIds*).

NOTE: In this example the constants contain the actual table and column names, but these can be specified via parameters if that is preferred (see manual).

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=customer]
----

Next we define a entity based on the table *store.address*.

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=address]
----

And finally we define a entity based on the _many-to-many_ relationship table *store.customer_address*.

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=customerAddress]
----

=== UI

The *EntityPanel* class provides a Swing UI for viewing and editing entities. It is composed of a *EntityEditPanel* and a *EntityTablePanel*. For each of these panel classes there is a corresponding model class; *SwingEntityModel*, which is composed of a *SwingEntityEditModel* and a *SwingEntityTableModel*. The only class you are required to extend is the *EntityEditPanel*, which provides the input controls for editing a entity. Below we demonstrate how to set up a simple _master/detail_ panel.

[cols="2,4"]
|===
|Module|Artifact
|dev.codion.swing.framework.ui|dev.codion.{codion-jdk}:codion-swing-framework-ui:{codion-version}
|===

==== Master

Here we extend a *EntityEditPanel* to provide the UI for editing a customer and use that edit panel class when we assemble the *EntityPanel*. We use a default *SwingEntityModel* implementation, which internally, creates a default *SwingEntityEditModel* and *SwingEntityTableModel*.

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=customerPanel]
----

==== Detail

Here we create a panel for viewing and editing customer addresses, much like the one above. We start by creating a default *SwingEntityModel* instance, which we add as a detail model on the customer model. Finally, we create a *EntityPanel* for the customer address and add that as a detail panel on the customer panel.

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=detailPanel]
----

=== Domain unit test

The *EntityTestUnit* class provides a way to unit test the domain model. The *test* method performs insert, update, select and delete on a randomly generated entity instance and verifies the results.

[cols="2,4"]
|===
|Module|Artifact
|dev.codion.framework.domain.test|dev.codion.{codion-jdk}:codion-framework-domain-test:{codion-version}
|===

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=domainModelTest]
----

=== Persistance

The *EntityConnection* interface provides select, insert, update, and delete methods. It has three available implementations, one of which is based on a local JDBC connection, used below.

[cols="2,4,2"]
|===
|Module|Artifact|Description
|dev.codion.framework.db.core|dev.codion.{codion-jdk}:codion-framework-db-core:{codion-version}|Database API
|dev.codion.framework.db.local|dev.codion.{codion-jdk}:codion-framework-db-local:{codion-version}|Local JDBC
|===

==== Selecting

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=select]
----

==== Persisting

[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tags=persist]
----

.Full code
[%collapsible]
====
[source,java,indent=0]
----
include::{dir-source}/dev/codion/framework/demos/manual/quickstart/Example.java[tag=**]
----
====