= Quickstart
:docinfo: shared-head
:toc: left
:dir-source: ../../../../demos/manual/src/main/java
:dir-source-sql: ../../../../demos/manual/src/main/sql

== Rich client
This artifact pulls in all required framework dependencies, except the ones related to database connectivity and logging, see below.

[cols="1,4"]
|===
|Client|Artifact

|Swing|is.codion:codion-swing-framework.ui:{codion-version}
|===

== Database connectivity
A Codion client has three ways of connecting to a database, directly via a local JDBC connection or remotely via RMI or HTTP using the Codion remote server.

[cols="1,4"]
|===
|DB Connection|Artifact

|Local|is.codion:codion-framework-db-local:{codion-version}
|RMI|is.codion:codion-framework-db-rmi:{codion-version}
|HTTP|is.codion:codion-framework-db-http:{codion-version}
|===

=== DBMS
When connecting to the database with a local JDBC connection the DBMS module for the underlying database must be on the classpath. Note that these artifacts do not depend on the JDBC drivers, so those must be added separately.

The most used and tested DBMS modules are:

1. Oracle
2. PostgreSQL
3. H2 Database

[cols="1,4"]
|===
|DBMS|Artifact

|Db2|is.codion:codion-dbms-db2database:{codion-version}
|Derby|is.codion:codion-dbms-derby:{codion-version}
|H2 Database|is.codion:codion-dbms-h2database:{codion-version}
|HSQL|is.codion:codion-dbms-hsql:{codion-version}
|MariaDB|is.codion:codion-dbms-mariadb:{codion-version}
|MySQL|is.codion:codion-dbms-mysql:{codion-version}
|Oracle|is.codion:codion-dbms-oracle:{codion-version}
|PostgreSQL|is.codion:codion-dbms-postgresql:{codion-version}
|SQLite|is.codion:codion-dbms-sqlite:{codion-version}
|SQL Server|is.codion:codion-dbms-sqlserver:{codion-version}
|===

== Logging
Codion uses SLF4J throughout so all you need to do is add a SLF4J bridge for your logging framework of choice to the classpath. If you use Logback, Log4J or Java Util Logging you can use one of the logging-proxy plugins below which will pull in the required dependencies and provide a main-menu action in the client for setting the logging level.

[cols="1,4"]
|===
|Logging|Artifact

|Logback|is.codion:codion-plugin-logback-proxy:{codion-version}
|Log4j|is.codion:codion-plugin-log4j-proxy:{codion-version}
|Java Util Logging|is.codion:codion-plugin-jul-proxy:{codion-version}
|===

== Gradle
A minimal Gradle dependencies configuration for a Swing based client application, using the H2 database.
[source,groovy,subs=attributes]
----
dependencies {
    implementation "is.codion:codion-swing-framework-ui:{codion-version}"

    runtimeOnly "is.codion:codion-framework-db-local:{codion-version}"
    runtimeOnly "is.codion:codion-dbms-h2database:{codion-version}"
    runtimeOnly "com.h2database:h2:2.2.220"
    runtimeOnly "is.codion:codion-plugin-logback-proxy:{codion-version}"

    testImplementation "is.codion:codion-framework-domain-test:{codion-version}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.9.3"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.9.3"
}
----

== Code examples

There are at minimum three steps involved in creating a Codion application:

  * Defining a domain model based on the underlying tables.
  * Creating edit panels for tables requiring CRUD functionality.
  * Assembling a client application from these building blocks.

===  Domain
[cols="2,4"]
|===
|Module|Artifact
|is.codion.framework.domain|is.codion:codion-framework-domain:{codion-version}
|===

==== Defining entities

The below examples are somewhat simplified, but functionally correct.

.View example schema SQL
[%collapsible]
====

NOTE: Not all columns are used in the example code below.

[source,sql,indent=0]
----
include::{dir-source-sql}/create_schema.sql[]
----
====

.View full domain source
[%collapsible]
====
[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=store]
----
====

To create a domain model we extend the *DefaultDomain* class and define a *DomainType* constant to identify the domain model.

In the constructor we call methods adding entity definitions to this domain model.

This class is continued below.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=storeDomain]
----

We create a namespace interface and define a *EntityType* constant based on the table and typed *Column* constants for each column, these constants specify the entity API, used when refererring to the entity type or its columns.

In the associated method we create *Property.Builder* instances based on each *Column*, providing further configuration options, such as specifying a caption and maximum length, using methods statically imported from the *Property* class. We supply these *Property.Builder* instances to the statically imported *EntityDefinition.definition()* method, which returns a *EntityDefinition.Builder* instance, providing further configuration options for the entity definition, such as the key generation strategy. Finally, we add the definition builder to the domain model.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=customer]
----

Next we define an entity based on the table *store.address*.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=address]
----

And finally we define an entity based on the _many-to-many_ relationship table *store.customer_address*.

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=customerAddress]
----

=== UI

The *EntityPanel* class provides a Swing UI for viewing and editing entities. It is composed of a *EntityEditPanel* and a *EntityTablePanel*. For each of these panel classes there is a corresponding model class; *SwingEntityModel*, which is composed of a *SwingEntityEditModel* and a *SwingEntityTableModel*. The only class you are required to extend is the *EntityEditPanel*, which provides the input controls for editing an entity. Below we demonstrate how to set up a simple _master/detail_ panel.

[cols="2,4"]
|===
|Module|Artifact
|is.codion.swing.framework.ui|is.codion:codion-swing-framework-ui:{codion-version}
|===

==== Master

Here we extend a *EntityEditPanel* to provide the UI for editing a customer and use that edit panel class when we assemble the *EntityPanel*. We use a default *SwingEntityModel* implementation, which internally, creates a default *SwingEntityEditModel* and *SwingEntityTableModel*.

[source,java,indent=0,options="nowrap"]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=customerPanel]
----

==== Detail

Here we create a panel for viewing and editing customer addresses, much like the one above. We start by creating a default *SwingEntityModel* instance, which we add as a detail model on the customer model. Finally, we create a *EntityPanel* for the customer address and add that as a detail panel on the customer panel.

[source,java,indent=0,options="nowrap"]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=detailPanel]
----

=== Domain unit test

The *EntityTestUnit* class provides a way to unit test the domain model. The *test* method performs insert, update, select and delete on a randomly generated entity instance and verifies the results.

[cols="2,4"]
|===
|Module|Artifact
|is.codion.framework.domain.test|is.codion:codion-framework-domain-test:{codion-version}
|===

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=domainModelTest]
----

=== Persistance

The *EntityConnection* interface provides select, insert, update, and delete methods. It has three available implementations, one of which is based on a local JDBC connection, used below.

[cols="2,4,2"]
|===
|Module|Artifact|Description
|is.codion.framework.db.core|is.codion:codion-framework-db-core:{codion-version}|Core database API
|is.codion.framework.db.local|is.codion:codion-framework-db-local:{codion-version}|Local JDBC implementation
|===

==== Selecting

[source,java,indent=0,options="nowrap"]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=select]
----

==== Persisting

[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tags=persist]
----

.Full code
[%collapsible]
====
[source,java,indent=0]
----
include::{dir-source}/is/codion/framework/demos/manual/quickstart/Example.java[tag=**]
----
====