title: JMinor Application Framework
email: bjorndarri@gmail.com
description: >-
  The JMinor Application Framework is a full-stack framework providing all the fundamental building blocks for creating Java rich client CRUD applications.
baseurl: ""
url: "http://jminor.org"
twitter_username: bjorndarri
github_username:  bjorndarri

# theme: minima
theme: minima
plugins:
  - jekyll-asciidoc

exclude:
  - vendor
  - .bundle
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

asciidoctor:
  base_dir: docs
  safe: unsafe
  attributes:
    - imagesdir=/images
    - jminor-version=0.12.3-SNAPSHOT
    - source-highlighter=rouge
    - url-javadoc=https://heima.hafro.is/~darri/jminor_wiki_data/project/docs/api

# this and the imagesdir attribute above
# are for the asciidoctor-diagram plugin
keep_files:
  - images