= Quickstart

== Rich client
JMinor is primarily a Swing based framework, the Swing client is mature and stable while the JavaFX client is quite rudimentary and still in the 'proof-of-concept' stage. This artifact pulls in all required framework dependencies.

[cols="1,4"]
|===
|Client|Artifact

|Swing|org.jminor.jdk8:jminor-swing-framework.ui:{jminor-version}
|JavaFX|org.jminor.jdk8:jminor-javafx-framework:{jminor-version}
|===

== Database connectivity
A JMinor client has three ways of connecting to a database, directly via a local JDBC connection or remotely via RMI or HTTP using the JMinor remote server.

[cols="1,4"]
|===
|DB Connection|Artifact

|Local|org.jminor.jdk8:jminor-framework-db-local:{jminor-version}
|RMI|org.jminor.jdk8:jminor-framework-db-remote:{jminor-version}
|HTTP|org.jminor.jdk8:jminor-framework-db-http:{jminor-version}
|===

== DBMS
When connecting to the database with a local JDBC connection the DBMS module for the underlying database must be on the classpath. Note that these artifacts do not depend on the JDBC drivers, so those must be added separately.

The most used and tested DBMS modules are:

1. Oracle
2. H2 Database
3. Postgresql

[cols="1,4"]
|===
|DBMS|Artifact

|Derby|org.jminor.jdk8:jminor-dbms-derby:{jminor-version}
|H2 Database|org.jminor.jdk8:jminor-dbms-h2database:{jminor-version}
|HSQL|org.jminor.jdk8:jminor-dbms-hsql:{jminor-version}
|MySQL|org.jminor.jdk8:jminor-dbms-mysql:{jminor-version}
|Oracle|org.jminor.jdk8:jminor-dbms-oracle:{jminor-version}
|Postgresql|org.jminor.jdk8:jminor-dbms-postgresql:{jminor-version}
|SQLite|org.jminor.jdk8:jminor-dbms-sqlite:{jminor-version}
|SQL Server|org.jminor.jdk8:jminor-dbms-sqlserver:{jminor-version}
|===

== Logging
JMinor uses SLF4J throughout so all you need to do is add a SLF4J bridge for your logging framework of choice to the classpath. If you use Logback or Log4J you can use one of the logging-proxy plugins below which will pull in the required dependencies and provide a main-menu action in the client for setting the logging level.

[cols="1,4"]
|===
|Logging|Artifact

|Logback|org.jminor.jdk8:jminor-plugin-logback-proxy:{jminor-version}
|Log4j|org.jminor.jdk8:jminor-plugin-log4j-proxy:{jminor-version}
|===

== Gradle
[source,groovy]
----
dependencies {
    //Swing client UI module
    implementation 'org.jminor.jdk8:jminor-swing-framework-ui:0.12.5-SNAPSHOT'

    //JSON for persisting client preferences
    runtime 'org.jminor.jdk8:jminor-plugin-json:0.12.5-SNAPSHOT'
    //Local JDBC connection module
    runtime 'org.jminor.jdk8:jminor-framework-db-local:0.12.5-SNAPSHOT'
    //H2 DBMS module
    runtime 'org.jminor.jdk8:jminor-dbms-h2database:0.12.5-SNAPSHOT'
    //H2 JDBC driver
    runtime 'com.h2database:h2:1.4.199'
    //Logging with Logback
    runtime 'org.jminor.jdk8:jminor-plugin-logback-proxy:0.12.5-SNAPSHOT'

    //Domain model unit testing module
    testImplementation 'org.jminor.jdk8:jminor-framework-domain-test:0.12.5-SNAPSHOT'
    //JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.5.1'
    testRuntime 'org.junit.jupiter:junit-jupiter-engine:5.5.1'
}
----