= Client
:dir-technical: ../technical

== Features

* Lightweight single threaded client with a simple synchronous event model
* Provides a practically mouse free user experience
* Graceful handling of network outages and server restarts
* Clear separation between model and UI
* Easy to use load testing harness provided for application models
* UI data bindings for most common components provided by the framework
* Implementing data bindings for new components is made simple with building blocks provided by the framework.
* The default UI layout is a simple and intuitive “waterfall” master-detail view
* Extensive searching and filtering capabilities
* Flexible keyboard-centric UI based on tab and split panes, detachable panels and toolbars
* Detailed logging of client actions

== Architecture
:dir-source: ../../demos/chinook/src/main/java

=== UI

[ditaa,ui-architecture,png]
....
+----------------------------------------------------------+
|EntityApplicationPanel                                    |
|+-------------------------------------------------------+ |
||EntityPanel (one or more)                              | |
||+----------------------------++----------------------+ | |
|||EntityEditPanel             ||EntityPanel           | | |
|||                            ||                      | | |
|||                            || (zero or more        | | |
||+----------------------------+|  detail panels)      | | |
||                              |                      | | |
||+----------------------------+|                      | | |
|||EntityTablePanel            ||                      | | |
|||+-------------------------+ ||                      | | |
||||EntityTableConditionPanel| ||                      | | |
||||                         | ||                      | | |
|||+-------------------------+ ||                      | | |
|||                            ||                      | | |
|||                            ||                      | | |
|||                            ||                      | | |
|||                            ||                      | | |
|||                            ||                      | | |
||+----------------------------++----------------------+ | |
|+-------------------------------------------------------+ |
+----------------------------------------------------------+
....

=== Model

[ditaa,model-architecture,png]
....
+----------------------------------------------------------+
|EntityApplicationModel                                    |
|+-------------------------------------------------------+ |
||EntityModel (one or more)                              | |
||+----------------------------++----------------------+ | |
|||EntityEditModel             ||EntityModel           | | |
|||                            ||                      | | |
|||                            || (zero or more        | | |
||+----------------------------+|  detail models)      | | |
||                              |                      | | |
||+----------------------------+|                      | | |
|||EntityTableModel            ||                      | | |
|||+-------------------------+ ||                      | | |
||||EntityTableConditionModel| ||                      | | |
||||                         | ||                      | | |
|||+-------------------------+ ||                      | | |
|||                            ||                      | | |
|||+-------------------------+ ||                      | | |
||||EntityTableSelectionModel| ||                      | | |
||||                         | ||                      | | |
|||+-------------------------+ ||                      | | |
||+----------------------------++----------------------+ | |
|+-------------------------------------------------------+ |
+----------------------------------------------------------+
....

=== Assembly

==== EntityModel

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/chinook/tutorial/ClientArchitecture.java[tags=entityModel]
----

==== EntityPanel

[source,java]
----
include::{dir-source}/org/jminor/framework/demos/chinook/tutorial/ClientArchitecture.java[tags=entityPanel]
----

=== Full Example

.Show code
[%collapsible]
====
[source,java]
----
include::{dir-source}/org/jminor/framework/demos/chinook/tutorial/ClientArchitecture.java[lines=4..-1]
----
====

== Configuration
:dir-source: ../../demos

=== Example configuration file

[source]
----
include::{dir-source}/chinook/src/main/config/h2db.config[]
----

== Usage

=== Keyboard shortcuts

==== Navigation

* kbd:[Ctrl + Alt + &#x2191;] Up
* kbd:[Ctrl + Alt + &#x2193;] Down
* kbd:[Ctrl + Alt + &#x2190;] Left
* kbd:[Ctrl + Alt + &#x2192;] Right

==== Resizing

* kbd:[Shift + Alt + &#x2190;] Left
* kbd:[Shift + Alt + &#x2192;] Right
* kbd:[Ctrl + Alt + &#x2191;/&#x2193;] Toggle edit panel

==== Transfer focus

* kbd:[Ctrl + E] Edit panel (initial focus component)
* kbd:[Ctrl + T] Table
* kbd:[Ctrl + I] Input field
* kbd:[Ctrl + S] Search field
* kbd:[Ctrl + F] Quick search

==== Edit panel

* kbd:[Alt + S] Save
* kbd:[Alt + A] Add (when available)
* kbd:[Alt + U] Update
* kbd:[Alt + D] Delete
* kbd:[Alt + R] Refresh

==== Table panel

* kbd:[Del] Delete selected
* kbd:[Shift + Alt + &#x2190;] Move column left
* kbd:[Shift + Alt + &#x2192;] Move column right
* kbd:[Alt + &#x2190;] Resize column left
* kbd:[Alt + &#x2192;] Resize column right