= Components
:url-javadoc: https://heima.hafro.is/~darri/jminor_site/docs/api

== EntityConnection
:url-entity-connection: {url-javadoc}/org/jminor/framework/db/EntityConnection.html

The {url-entity-connection}[EntityConnection] interface defines the database layer accessible to JMinor applications. It provides methods for selecting, inserting, updating and deleting entities, executing procedures and functions, filling reports as well as providing transaction control.

=== Selecting

* selectMany
** {url-entity-connection}#selectMany-org.jminor.framework.db.condition.EntitySelectCondition-[selectMany(EntitySelectCondition condition)]
** {url-entity-connection}##selectMany-java.util.List-[selectMany(List<Entity.Key> keys)]
** {url-entity-connection}#selectMany-java.lang.String-java.lang.String-java.lang.Object...-[selectMany(String entityId, String propertyId, Object... values)]
* selectSingle
** {url-entity-connection}#selectSingle-org.jminor.framework.domain.Entity.Key-[selectSingle(Entity.Key key)]
** {url-entity-connection}#selectSingle-org.jminor.framework.db.condition.EntitySelectCondition-[selectSingle(EntitySelectCondition condition)]
* selectValues
** {url-entity-connection}#selectValues-java.lang.String-org.jminor.framework.db.condition.EntityCondition-[selectValues(String propertyId, EntityCondition condition)]
* selectDependencies
** {url-entity-connection}#selectDependencies-java.util.Collection-[selectDependencies(Collection<Entity> entities)]
* selectRowCount
** {url-entity-connection}#selectRowCount-org.jminor.framework.db.condition.EntityCondition-[selectRowCount(EntityCondition condition)]

=== Modifying

* insert
** {url-entity-connection}#insert-java.util.List-[insert(List<Entity> entities)]
* update
** {url-entity-connection}#update-java.util.List-[update(List<Entity> entities)]
* delete
** {url-entity-connection}#delete-org.jminor.framework.db.condition.EntityCondition-[delete(EntityCondition condition)]
** {url-entity-connection}#delete-java.util.List-[delete(List<Entity.Key> keys)]

== LocalEntityConnection

A EntityConnection with a direct connection to the database, provides access to the underlying JDBC connection.

== RemoteEntityConnection

A EntityConnection connecting to the database via RMI.

== HttpEntityConnection

A EntityConnection connecting to the database via HTTP.