= Project
:dir-manual: ../manual

== Building

The JMinor framework is built with https://gradle.org[Gradle] and includes the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper], so assuming you have cloned the repository and worked your way into the project directory you can build the framework by running the following command.

NOTE: This may take a few minutes, depending on the machine.

[source,shell]
----
gradlew build
----

To install the JMinor framework into your local Maven repository run the following command.

[source,shell]
----
gradlew publishToMavenLocal
----

== Running the demos

NOTE: The demos use an embedded in-memory database, so changes to data do not persist.

=== Local database connection

You can start by running a client from one of the demo projects (empdept, chinook, petstore or world) with a local database connection.

[source,shell]
----
gradlew :jminor-demos-chinook:runClientLocal
----

=== Remote database connection

In order to run a client with a remote connection we must first start the remote server.

[source,shell]
----
gradlew :jminor-framework-server:runServer
----

To run a demo client with a remote connection use the following command.

[source,shell]
----
gradlew :jminor-demos-chinook:runClientRMI
----

You can run the <<server-monitor.adoc#, Server Monitor>> application to see how the server is behaving, with the following command.

[source,shell]
----
gradlew :jminor-swing-framework-server-monitor:runServerMonitor
----

NOTE: The client handles server restarts gracefully, you can try shutting down the server via the Server Monitor, play around in the client until you get a 'Connection refused' exception. After you restart the server the client simply reconnects and behaves as if nothing happened.

== Code quality

http://darri.myftp.org:9001/dashboard?id=org.jminor[Sonarqube]