= Project
:dir-manual: ../manual
:dir-root: ../../

== Building

The JMinor framework is built with https://gradle.org[Gradle] and includes the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper], so assuming you have cloned the repository and worked your way into the project directory you can build the framework by running the following command.

NOTE: This may take a few minutes, depending on the machine.

[source,shell]
----
gradlew build
----

To install the JMinor framework into your local Maven repository run the following command.

[source,shell]
----
gradlew publishToMavenLocal
----

== Framework modules

=== Common

==== jminor-common-core

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/common/core/build/reports/project/dependencies.txt[]
----
====

==== jminor-common-db

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/common/db/build/reports/project/dependencies.txt[]
----
====

==== jminor-common-model

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/common/model/build/reports/project/dependencies.txt[]
----
====

==== jminor-common-remote

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/common/remote/build/reports/project/dependencies.txt[]
----
====

==== jminor-common-remote-http

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/common/remote-http/build/reports/project/dependencies.txt[]
----
====

=== DBMS

==== jminor-dbms-derby

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/derby/build/reports/project/dependencies.txt[]
----
====

==== jminor-dbms-h2database

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/h2database/build/reports/project/dependencies.txt[]
----
====

==== jminor-dbms-hsqldb

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/hsqldb/build/reports/project/dependencies.txt[]
----
====

==== jminor-dbms-mysql

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/mysql/build/reports/project/dependencies.txt[]
----
====

==== jminor-dbms-oracle

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/oracle/build/reports/project/dependencies.txt[]
----
====

==== jminor-dbms-postgresql

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/postgresql/build/reports/project/dependencies.txt[]
----
====

==== jminor-dbms-sqlite

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/sqlite/build/reports/project/dependencies.txt[]
----
====

==== jminor-dbms-sqlserver

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/dbms/sqlserver/build/reports/project/dependencies.txt[]
----
====

=== Framework

==== jminor-framework-db-core

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/db-core/build/reports/project/dependencies.txt[]
----
====

==== jminor-framework-db-http

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/db-http/build/reports/project/dependencies.txt[]
----
====
==== jminor-framework-db-local

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/db-local/build/reports/project/dependencies.txt[]
----
====

==== jminor-framework-db-remote

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/db-remote/build/reports/project/dependencies.txt[]
----
====

==== jminor-framework-domain

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/domain/build/reports/project/dependencies.txt[]
----
====

==== jminor-framework-domain-test

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/domain-test/build/reports/project/dependencies.txt[]
----
====

==== jminor-framework-model

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/model/build/reports/project/dependencies.txt[]
----
====

==== jminor-framework-server

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/server/build/reports/project/dependencies.txt[]
----
====

==== jminor-framework-servlet

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/framework/servlet/build/reports/project/dependencies.txt[]
----
====

=== Swing

==== jminor-swing-common-model

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/common-model/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-common-ui

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/common-ui/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-common-tools

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/common-tools/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-common-tools-ui

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/common-tools-ui/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-framework-model

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/framework-model/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-framework-ui

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/framework-ui/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-framework-ui-test

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/framework-ui-test/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-framework-tools

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/framework-tools/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-framework-tools-ui

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/framework-tools-ui/build/reports/project/dependencies.txt[]
----
====

==== jminor-swing-framework-server-monitor

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/swing/framework-server-monitor/build/reports/project/dependencies.txt[]
----
====

=== JavaFX

==== jminor-javafx-framework

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/javafx/build/reports/project/dependencies.txt[]
----
====

=== Plugins

==== Logging

==== jminor-plugin-jul-proxy

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/jul-proxy/build/reports/project/dependencies.txt[]
----
====

==== jminor-plugin-log4j-proxy

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/log4j-proxy/build/reports/project/dependencies.txt[]
----
====

==== jminor-plugin-logback-proxy

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/logback-proxy/build/reports/project/dependencies.txt[]
----
====

==== Connection pools

==== jminor-plugin-hikari-pool

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/hikari-pool/build/reports/project/dependencies.txt[]
----
====

==== jminor-plugin-tomcat-pool

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/tomcat-pool/build/reports/project/dependencies.txt[]
----
====

==== Reporting

==== jminor-plugin-jasperreports

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/jasperreports/build/reports/project/dependencies.txt[]
----
====

==== jminor-plugin-nextreports

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/nextreports/build/reports/project/dependencies.txt[]
----
====

==== JSON

==== jminor-plugin-jackson-json

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/jackson-json/build/reports/project/dependencies.txt[]
----
====

==== jminor-plugin-json

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/json/build/reports/project/dependencies.txt[]
----
====

==== Other

==== jminor-plugin-credentials-server

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/credentials-server/build/reports/project/dependencies.txt[]
----
====

==== jminor-plugin-imagepanel

.Dependencies
[%collapsible]
====
[source,java]
----
include::{dir-root}/plugins/imagepanel/build/reports/project/dependencies.txt[]
----
====

== Running the demos

NOTE: The demos use an embedded in-memory database, so changes to data do not persist.

=== Local database connection

You can start by running a client from one of the demo projects (empdept, chinook, petstore or world) with a local database connection.

[source,shell]
----
gradlew :jminor-demos-chinook:runClientLocal
----

=== Remote database connection

In order to run a client with a remote connection we must first start the remote server.

[source,shell]
----
gradlew :jminor-framework-server:runServer
----

To run a demo client with a remote connection use the following command.

[source,shell]
----
gradlew :jminor-demos-chinook:runClientRMI
----

You can run the <<server-monitor.adoc#, Server Monitor>> application to see how the server is behaving, with the following command.

[source,shell]
----
gradlew :jminor-swing-framework-server-monitor:runServerMonitor
----

NOTE: The client handles server restarts gracefully, you can try shutting down the server via the Server Monitor, play around in the client until you get a 'Connection refused' exception. After you restart the server the client simply reconnects and behaves as if nothing happened.

== Code quality

http://darri.myftp.org:9001/dashboard?id=org.jminor[Sonarqube]