combine=Combine
select_artists_to_keep=Select the artist to keep
combining_artists=Combining artists
artists_combined=Artists combined!
associate=Associate
albums=albums(s)
with=with
delete_the_following=Delete the following
while_keeping=while keeping
confirm_artist_combination=Confirm artist combination