/*
 * This file is part of Codion.
 *
 * Codion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Codion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Codion.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2009 - 2026, Björn Darri Sigurðsson.
 */
package is.codion.dbms.sqlserver;

import is.codion.common.db.database.AbstractDatabase;

import java.sql.SQLException;

import static java.util.Objects.requireNonNull;

/**
 * A Database implementation based on the SQL Server (2000 or higher) database.
 */
final class SQLServerDatabase extends AbstractDatabase {

	private static final int AUTHENTICATION_ERROR = 18456;
	private static final int REFERENTIAL_INTEGRITY_ERROR = 547;
	private static final int UNIQUE_CONSTRAINT_ERROR1 = 2601;
	private static final int UNIQUE_CONSTRAINT_ERROR2 = 2627;

	private static final String UNORDERED = "ORDER BY (SELECT NULL) ";
	private static final String JDBC_URL_PREFIX = "jdbc:sqlserver://";
	/**
	 * The server accepts 2100 parameters per request, the driver using two of those for the statement itself
	 */
	private static final int MAXIMUM_STATEMENT_PARAMETERS = 2098;

	SQLServerDatabase(String url) {
		super(url);
	}

	@Override
	public String name() {
		String name = removeUrlPrefixOptionsAndParameters(url(), JDBC_URL_PREFIX);
		if (name.contains("\\")) {
			name = name.substring(name.lastIndexOf('\\') + 1);
			if (name.contains(":")) {
				name = name.substring(0, name.indexOf(':'));
			}
		}

		return name;
	}

	@Override
	public String sequenceQuery(String sequenceName) {
		return "SELECT NEXT VALUE FOR " + requireNonNull(sequenceName);
	}

	@Override
	public String selectForUpdateClause() {
		return "";
	}

	@Override
	public String limitOffsetClause(Integer limit, Integer offset, boolean ordered) {
		if (limit == null && offset == null) {
			return "";
		}
		// OFFSET and FETCH are a part of the ORDER BY clause, which is thereby required, as is the OFFSET when fetching
		String offsetFetchNext = createOffsetFetchNextClause(limit, offset == null ? Integer.valueOf(0) : offset);

		return ordered ? offsetFetchNext : UNORDERED + offsetFetchNext;
	}

	/**
	 * @return true
	 */
	@Override
	public boolean subqueryRequiresAlias() {
		return true;
	}

	@Override
	public int maximumParameters() {
		return MAXIMUM_STATEMENT_PARAMETERS;
	}

	@Override
	public String autoIncrementQuery(String idSource) {
		// @@IDENTITY returns the value generated by a trigger, if one inserts, and SCOPE_IDENTITY() returns null from a separate statement
		throw new UnsupportedOperationException("SQL Server provides no reliable way of querying for the last generated value, " +
						"use an identity based generator, relying on Statement.getGeneratedKeys(), instead of an automatic one");
	}

	@Override
	public boolean isAuthenticationException(SQLException exception) {
		return requireNonNull(exception).getErrorCode() == AUTHENTICATION_ERROR;
	}

	@Override
	public boolean isReferentialIntegrityException(SQLException exception) {
		return requireNonNull(exception).getErrorCode() == REFERENTIAL_INTEGRITY_ERROR;
	}

	@Override
	public boolean isUniqueConstraintException(SQLException exception) {
		return requireNonNull(exception).getErrorCode() == UNIQUE_CONSTRAINT_ERROR1 || exception.getErrorCode() == UNIQUE_CONSTRAINT_ERROR2;
	}
}
