-- Add preferences table for storing user-specific settings
CREATE TABLE IF NOT EXISTS CHINOOK.PREFERENCES (
    CUSTOMER_ID LONG NOT NULL,
    PREFERRED_GENRE_ID LONG,
    NEWSLETTER BOOLEAN,
    CONSTRAINT PK_PREFERENCES PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT FK_PREFERENCES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CHINOOK.CUSTOMER(ID),
    CONSTRAINT FK_PREFERENCES_GENRE FOREIGN KEY (PREFERRED_GENRE_ID) REFERENCES CHINOOK.GENRE(ID)
);

INSERT INTO CHINOOK.PREFERENCES (CUSTOMER_ID, PREFERRED_GENRE_ID)
VALUES(1, 2);

INSERT INTO CHINOOK.PREFERENCES (CUSTOMER_ID, PREFERRED_GENRE_ID, NEWSLETTER)
VALUES(2, 3, TRUE);

INSERT INTO CHINOOK.PREFERENCES (CUSTOMER_ID, PREFERRED_GENRE_ID)
VALUES(3, 4);

INSERT INTO CHINOOK.PREFERENCES (CUSTOMER_ID, PREFERRED_GENRE_ID, NEWSLETTER)
VALUES(4, 5, TRUE);

INSERT INTO CHINOOK.PREFERENCES (CUSTOMER_ID, PREFERRED_GENRE_ID, NEWSLETTER)
VALUES(5, 6, FALSE);

INSERT INTO CHINOOK.PREFERENCES (CUSTOMER_ID, PREFERRED_GENRE_ID)
VALUES(6, 7);

COMMIT;