= Code style and design
:dir-manual-source: ../../../../../demos/manual/src/main/java

== Factories and builders

Most concrete framework classes, which implement a public interface, are final, package private, and are instantiated with the help of static methods in the interface they implement.

=== Factories

Static factory methods are provided for classes with a simple initial state. These are usually named after the interface, which makes using static imports quite convenient.

[source,java]
----
include::{dir-manual-source}/is/codion/framework/demos/manual/design/DesignAndStyle.java[tags=factories,indent=0]
----

=== Builders

For classes with a more complex initial state, a `builder` method is provided in the interface.

[source,java]
----
include::{dir-manual-source}/is/codion/framework/demos/manual/design/DesignAndStyle.java[tags=builders,indent=0]
----

== Accessors

Immutable fields and attributes are accessed using methods named after the field, without a `get`/`is` prefix.

[source,java]
----
include::{dir-manual-source}/is/codion/framework/demos/manual/design/DesignAndStyle.java[tags=accessors,indent=0]
----

A `get`/`is` prefix implies that the field is mutable and that a corresponding setter method with a `set` prefix exists.

[source,java]
----
include::{dir-manual-source}/is/codion/framework/demos/manual/design/DesignAndStyle.java[tags=getters,indent=0]
----

== Exceptions

There are a few exceptions to these rules, such as a `get` prefix on an accessor for a functionally immutable field, but these exceptions are usually to keep the style of a class being extended, such as Swing components and should be few and far between.