= Modules
:url-javadoc: link:../api
:imagesdir: ../images

== Common

Common classes used throughout the framework.

[discrete]
=== codion-common-core

* {url-javadoc}{common-core}/is/codion/common/event/package-summary.html[is.codion.common.event]
* {url-javadoc}{common-core}/is/codion/common/state/package-summary.html[is.codion.common.state]
* {url-javadoc}{common-core}/is/codion/common/value/package-summary.html[is.codion.common.value]

.Dependency graph
[%collapsible]
====
image::modules/common/core/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-db

JDBC related classes.

* {url-javadoc}{common-db}/is/codion/common/db/connection/package-summary.html[is.codion.common.db.connection]
* {url-javadoc}{common-db}/is/codion/common/db/database/package-summary.html[is.codion.common.db.database]

.Dependency graph
[%collapsible]
====
image::modules/common/db/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-model

General model classes shared between Swing and JavaFX UI components.

* {url-javadoc}{common-model}/is/codion/common/model/table/package-summary.html[is.codion.common.model.table]

.Dependency graph
[%collapsible]
====
image::modules/common/model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-rmi

RMI related classes.

* {url-javadoc}{common-rmi}/is/codion/common/rmi/client/package-summary.html[is.codion.common.rmi.client]
* {url-javadoc}{common-rmi}/is/codion/common/rmi/server/package-summary.html[is.codion.common.rmi.server]

.Dependency graph
[%collapsible]
====
image::modules/common/rmi/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-http

HTTP related classes.

* {url-javadoc}{common-http}/is/codion/common/http/server/package-summary.html[is.codion.common.http.server]

.Dependency graph
[%collapsible]
====
image::modules/common/http/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== DBMS

Database specific implementation classes.

[discrete]
=== codion-dbms-db2database

.Dependency graph
[%collapsible]
====
image::modules/dbms/db2database/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-derby

.Dependency graph
[%collapsible]
====
image::modules/dbms/derby/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-h2database

.Dependency graph
[%collapsible]
====
image::modules/dbms/h2database/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-hsqldb

.Dependency graph
[%collapsible]
====
image::modules/dbms/hsqldb/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-mariadb

.Dependency graph
[%collapsible]
====
image::modules/dbms/mariadb/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-mysql

.Dependency graph
[%collapsible]
====
image::modules/dbms/mysql/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-oracle

.Dependency graph
[%collapsible]
====
image::modules/dbms/oracle/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-postgresql

.Dependency graph
[%collapsible]
====
image::modules/dbms/postgresql/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-sqlite

.Dependency graph
[%collapsible]
====
image::modules/dbms/sqlite/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-sqlserver

.Dependency graph
[%collapsible]
====
image::modules/dbms/sqlserver/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== Framework

The framework itself.

[discrete]
=== codion-framework-domain

Domain model related classes.

* {url-javadoc}{framework-domain}/is/codion/framework/domain/package-summary.html[is.codion.framework.domain]
* {url-javadoc}{framework-domain}/is/codion/framework/domain/entity/package-summary.html[is.codion.framework.domain.entity]
* {url-javadoc}{framework-domain}/is/codion/framework/domain/property/package-summary.html[is.codion.framework.domain.property]

.Dependency graph
[%collapsible]
====
image::modules/framework/domain/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-domain-test

Domain model unit test related classes.

* {url-javadoc}{framework-domain-test}/is/codion/framework/domain/entity/test/package-summary.html[is.codion.framework.domain.entity.test]

.Dependency graph
[%collapsible]
====
image::modules/framework/domain-test/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-core

Core database connection related classes.

* {url-javadoc}{framework-db-core}/is/codion/framework/db/package-summary.html[is.codion.framework.db]
* {url-javadoc}{framework-db-core}/is/codion/framework/db/condition/package-summary.html[is.codion.framework.db.condition]

.Dependency graph
[%collapsible]
====
image::modules/framework/db-core/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-local

Local JDBC connection related classes.

* {url-javadoc}{framework-db-local}/is/codion/framework/db/local/package-summary.html[is.codion.framework.db.local]

.Dependency graph
[%collapsible]
====
image::modules/framework/db-local/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-rmi

RMI connection related classes.

* {url-javadoc}{framework-db-rmi}/is/codion/framework/db/rmi/package-summary.html[is.codion.framework.db.rmi]

.Dependency graph
[%collapsible]
====
image::modules/framework/db-rmi/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-http

HTTP connection related classes.

* {url-javadoc}{framework-db-http}/is/codion/framework/db/http/package-summary.html[is.codion.framework.db.http]

.Dependency graph
[%collapsible]
====
image::modules/framework/db-http/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== codion-framework-json

[discrete]
==== codion-framework-json

.Dependency graph
[%collapsible]
====
image::modules/framework/json/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-model

General application model classes shared between Swing and JavaFX UI components.

* {url-javadoc}{framework-model}/is/codion/framework/model/package-summary.html[is.codion.framework.model]

.Dependency graph
[%collapsible]
====
image::modules/framework/model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-model-test

General application model unit test related classes.

* {url-javadoc}{framework-model-test}/is/codion/framework/model/test/package-summary.html[is.codion.framework.model.test]

.Dependency graph
[%collapsible]
====
image::modules/framework/model-test/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-server

Framework server classes.

* {url-javadoc}{framework-server}/is/codion/framework/server/package-summary.html[is.codion.framework.server]

.Dependency graph
[%collapsible]
====
image::modules/framework/server/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-servlet

HTTP servlet server classes.

* {url-javadoc}{framework-servlet}/is/codion/framework/servlet/package-summary.html[is.codion.framework.servlet]

.Dependency graph
[%collapsible]
====
image::modules/framework/servlet/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== Swing

Swing client implementation.

[discrete]
=== codion-swing-common-model

Common Swing model classes.

* {url-javadoc}{swing-common-model}/is/codion/swing/common/model/component/button/package-summary.html[is.codion.swing.common.model.component.button]
* {url-javadoc}{swing-common-model}/is/codion/swing/common/model/component/combobox/package-summary.html[is.codion.swing.common.model.component.combobox]
* {url-javadoc}{swing-common-model}/is/codion/swing/common/model/component/table/package-summary.html[is.codion.swing.common.model.component.table]
* {url-javadoc}{swing-common-model}/is/codion/swing/common/model/component/text/package-summary.html[is.codion.swing.common.model.component.text]
* {url-javadoc}{swing-common-model}/is/codion/swing/common/model/worker/package-summary.html[is.codion.swing.common.model.worker]

.Dependency graph
[%collapsible]
====
image::modules/swing/common-model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-common-ui

Common Swing UI classes.

* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/calendar/package-summary.html[is.codion.swing.common.ui.component.calendar]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/button/package-summary.html[is.codion.swing.common.ui.component.button]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/combobox/package-summary.html[is.codion.swing.common.ui.component.combobox]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/panel/package-summary.html[is.codion.swing.common.ui.component.panel]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/slider/package-summary.html[is.codion.swing.common.ui.component.slider]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/spinner/package-summary.html[is.codion.swing.common.ui.component.spinner]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/table/package-summary.html[is.codion.swing.common.ui.component.table]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/text/package-summary.html[is.codion.swing.common.ui.component.text]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/component/package-summary.html[is.codion.swing.common.ui.component]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/control/package-summary.html[is.codion.swing.common.ui.control]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/dialog/package-summary.html[is.codion.swing.common.ui.dialog]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/icon/package-summary.html[is.codion.swing.common.ui.icon]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/layout/package-summary.html[is.codion.swing.common.ui.layout]
* {url-javadoc}{swing-common-ui}/is/codion/swing/common/ui/package-summary.html[is.codion.swing.common.ui]

.Dependency graph
[%collapsible]
====
image::modules/swing/common-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-common-tools

.Dependency graph
[%collapsible]
====
image::modules/swing/common-tools/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-common-tools-ui

.Dependency graph
[%collapsible]
====
image::modules/swing/common-tools-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-model

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-ui

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-ui-test

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-ui-test/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-tools

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-tools/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-tools-ui

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-tools-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-server-monitor

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-server-monitor/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== JavaFX

JavaFX client implementation (still quite experimental).

[discrete]
=== codion-javafx-framework

.Dependency graph
[%collapsible]
====
image::modules/javafx/framework/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== Plugins

=== Logging

[discrete]
==== codion-plugin-jul-proxy

.Dependency graph
[%collapsible]
====
image::modules/plugins/jul-proxy/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-log4j-proxy

.Dependency graph
[%collapsible]
====
image::modules/plugins/log4j-proxy/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-logback-proxy

.Dependency graph
[%collapsible]
====
image::modules/plugins/logback-proxy/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== Connection pools

[discrete]
==== codion-plugin-hikari-pool

.Dependency graph
[%collapsible]
====
image::modules/plugins/hikari-pool/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-tomcat-pool

.Dependency graph
[%collapsible]
====
image::modules/plugins/tomcat-pool/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== Reporting

[discrete]
==== codion-plugin-jasperreports

.Dependency graph
[%collapsible]
====
image::modules/plugins/jasperreports/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== Other

[discrete]
==== codion-plugin-credentials-server

.Dependency graph
[%collapsible]
====
image::modules/plugins/credentials-server/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-imagepanel

.Dependency graph
[%collapsible]
====
image::modules/plugins/imagepanel/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====
