= Modules
:url-javadoc: link:../api
:imagesdir: ../images

== Common

Common classes used throughout the framework.

[discrete]
=== codion-common-core

{url-javadoc}/is/codion/common/event/package-summary.html[is.codion.common.event]
{url-javadoc}/is/codion/common/state/package-summary.html[is.codion.common.state]
{url-javadoc}/is/codion/common/value/package-summary.html[is.codion.common.value]

.Dependency graph
[%collapsible]
====
image::modules/common/core/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-db

.Dependency graph
[%collapsible]
====
image::modules/common/db/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-model

.Dependency graph
[%collapsible]
====
image::modules/common/model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-rmi

.Dependency graph
[%collapsible]
====
image::modules/common/rmi/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-common-http

.Dependency graph
[%collapsible]
====
image::modules/common/http/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== DBMS

Database specific implementation classes.

[discrete]
=== codion-dbms-derby

.Dependency graph
[%collapsible]
====
image::modules/dbms/derby/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-h2database

.Dependency graph
[%collapsible]
====
image::modules/dbms/h2database/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-hsqldb

.Dependency graph
[%collapsible]
====
image::modules/dbms/hsqldb/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-mariadb

.Dependency graph
[%collapsible]
====
image::modules/dbms/mariadb/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-mysql

.Dependency graph
[%collapsible]
====
image::modules/dbms/mysql/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-oracle

.Dependency graph
[%collapsible]
====
image::modules/dbms/oracle/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-postgresql

.Dependency graph
[%collapsible]
====
image::modules/dbms/postgresql/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-sqlite

.Dependency graph
[%collapsible]
====
image::modules/dbms/sqlite/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-dbms-sqlserver

.Dependency graph
[%collapsible]
====
image::modules/dbms/sqlserver/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== Framework

The framework itself.

[discrete]
=== codion-framework-domain

.Dependency graph
[%collapsible]
====
image::modules/framework/domain/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-domain-test

.Dependency graph
[%collapsible]
====
image::modules/framework/domain-test/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-core

.Dependency graph
[%collapsible]
====
image::modules/framework/db-core/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-local

.Dependency graph
[%collapsible]
====
image::modules/framework/db-local/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-rmi

.Dependency graph
[%collapsible]
====
image::modules/framework/db-rmi/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-db-http

.Dependency graph
[%collapsible]
====
image::modules/framework/db-http/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-model

.Dependency graph
[%collapsible]
====
image::modules/framework/model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-model-test

.Dependency graph
[%collapsible]
====
image::modules/framework/model-test/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-server

.Dependency graph
[%collapsible]
====
image::modules/framework/server/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-framework-servlet

.Dependency graph
[%collapsible]
====
image::modules/framework/servlet/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== Swing

Swing client implementation.

[discrete]
=== codion-swing-common-model

.Dependency graph
[%collapsible]
====
image::modules/swing/common-model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-common-ui

.Dependency graph
[%collapsible]
====
image::modules/swing/common-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-common-tools

.Dependency graph
[%collapsible]
====
image::modules/swing/common-tools/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-common-tools-ui

.Dependency graph
[%collapsible]
====
image::modules/swing/common-tools-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-model

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-model/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-ui

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-ui-test

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-ui-test/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-tools

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-tools/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-tools-ui

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-tools-ui/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
=== codion-swing-framework-server-monitor

.Dependency graph
[%collapsible]
====
image::modules/swing/framework-server-monitor/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== JavaFX

JavaFX client implementation (still quite experimental).

[discrete]
=== codion-javafx-framework

.Dependency graph
[%collapsible]
====
image::modules/javafx/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

== Plugins

=== Logging

[discrete]
==== codion-plugin-jul-proxy

.Dependency graph
[%collapsible]
====
image::modules/plugins/jul-proxy/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-log4j-proxy

.Dependency graph
[%collapsible]
====
image::modules/plugins/log4j-proxy/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-logback-proxy

.Dependency graph
[%collapsible]
====
image::modules/plugins/logback-proxy/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== Connection pools

[discrete]
==== codion-plugin-hikari-pool

.Dependency graph
[%collapsible]
====
image::modules/plugins/hikari-pool/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-tomcat-pool

.Dependency graph
[%collapsible]
====
image::modules/plugins/tomcat-pool/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== Reporting

[discrete]
==== codion-plugin-jasperreports

.Dependency graph
[%collapsible]
====
image::modules/plugins/jasperreports/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-nextreports

.Dependency graph
[%collapsible]
====
image::modules/plugins/nextreports/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== JSON

.Dependency graph
[%collapsible]
====
image::modules/plugins/jackson-json/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-json

.Dependency graph
[%collapsible]
====
image::modules/plugins/json/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

=== Other

[discrete]
==== codion-plugin-credentials-server

.Dependency graph
[%collapsible]
====
image::modules/plugins/credentials-server/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-ikonli-foundation

.Dependency graph
[%collapsible]
====
image::modules/plugins/ikonli-foundation/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====

[discrete]
==== codion-plugin-imagepanel

.Dependency graph
[%collapsible]
====
image::modules/plugins/imagepanel/build/reports/dependency-graph/dependency-graph.svg[opts=interactive]
====
