= Project

== Building

The Codion framework is built with https://gradle.org[Gradle] and includes the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper] with a https://docs.gradle.org/current/userguide/toolchains.html[toolchain] defined, so assuming you have cloned the repository and worked your way into the project directory you can build the framework by running the following command.

[source,shell]
----
gradlew build
----

NOTE: This may take a few minutes, depending on the machine.

To install the Codion framework into your local Maven repository run the following command.

[source,shell]
----
gradlew publishToMavenLocal
----

== Running the demos

NOTE: The demos use an embedded in-memory database, so changes to data do not persist.

=== Local database connection

You can start by running a client from one of the demo projects (employees, chinook, petstore or world) with a local database connection.

[source,shell]
----
gradlew demo-chinook:runClientLocal
----

=== Remote database connection

In order to run a client with a remote or http connection the remote server must be started first.

[source,shell]
----
gradlew codion-framework-server:run
----

To run a demo client with a remote connection use the following command.

[source,shell]
----
gradlew demo-chinook:runClientRMI
----

You can run the <<server-monitor.adoc#_server_monitor, Server Monitor>> application to see how the server is behaving, with the following command.

[source,shell]
----
gradlew codion-swing-framework-server-monitor:run
----

NOTE: The client handles server restarts gracefully, you can try shutting down the server via the Server Monitor, play around in the client until you get a 'Connection refused' exception.
After you restart the server the client simply reconnects and behaves as if nothing happened.

== Code style

After having wrestled with many code formatters and never being fully satisfied with the result, I've wound up relying on IntelliJ for code formatting.
The project has a defined code style which can be found in the `.idea/codeStyles` folder.

== Code quality

http://sonar.codion.is:9001/dashboard?id=is.codion[SonarQube]