= Project

== Branches

=== main

JDK 11 compatible, built with JDK 11, fully modular.

Maven/Gradle groupId *is.codion*.

== Building

The Codion framework is built with https://gradle.org[Gradle] and includes the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper] with a https://docs.gradle.org/current/userguide/toolchains.html[toolchain] defined, so assuming you have cloned the repository and worked your way into the project directory you can build the framework by running the following command.

[source,shell]
----
gradlew build
----

NOTE: This may take a few minutes, depending on the machine.

To install the Codion framework into your local Maven repository run the following command.

[source,shell]
----
gradlew publishToMavenLocal
----

== Running the demos

NOTE: The demos use an embedded in-memory database, so changes to data do not persist.

=== Local database connection

You can start by running a client from one of the demo projects (empdept, chinook, petstore or world) with a local database connection.

[source,shell]
----
gradlew codion-demos-chinook:runClientLocal
----

=== Remote database connection

In order to run a client with a remote connection we must first start the remote server.

[source,shell]
----
gradlew codion-framework-server:runServer
----

To run a demo client with a remote connection use the following command.

[source,shell]
----
gradlew codion-demos-chinook:runClientRMI
----

You can run the <<server-monitor.adoc#_server_monitor, Server Monitor>> application to see how the server is behaving, with the following command.

[source,shell]
----
gradlew codion-swing-framework-server-monitor:runServerMonitor
----

NOTE: The client handles server restarts gracefully, you can try shutting down the server via the Server Monitor, play around in the client until you get a 'Connection refused' exception. After you restart the server the client simply reconnects and behaves as if nothing happened.

== Code quality

http://sonar.codion.is:9001/dashboard?id=is.codion[SonarQube]