= Server
:dir-tutorials: ../tutorials
:dir-source: ../../../../../framework/server
:dir-manual-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

== Features

* Firewall friendly; uses one way communications without callbacks and can be configured to serve on a single fixed port
* Integrated web server for serving Web Start applications and files, based on Jetty
* All user authentication left to the database by default
* Comprehensive administration and monitoring facilities via the <<server-monitor.adoc#_server_monitor, ServerMonitor>>
* Featherweight server with moderate memory and CPU usage

== Security

=== Authentication

The Codion server does not perform any user authentication by default, it leaves that up the underlying database. An authentication layer can be added by implementing a {url-javadoc}{common-rmi}/is/codion/common/rmi/server/LoginProxy.html[LoginProxy] and setting the following system property.

[source]
----
codion.server.loginProxyClasses=com.app.server.AppLoginProxy # <1>
----
<1> A comma separated list of login proxies

==== Login proxy examples

<<{dir-tutorials}/chinook.adoc#_login_proxy, ChinookLoginProxy>>

=== SSL encryption

To enable SSL encryption between client and server, create a keystore and truststore pair and set the following system properties.

==== Server side

[source]
----
codion.server.connection.sslEnabled=true # <1>
javax.net.ssl.keyStore=keystore.jks
javax.net.ssl.keyStorePassword=password
----
<1> This property is 'true' by default, included here for completenes's sake

==== Client side

[source]
----
codion.client.trustStore=truststore.jks
codion.client.trustStore=password
----

=== Class loading

No dynamic class loading is performed.

=== Serialization whitelist

A {url-javadoc}{common-rmi}/is/codion/common/rmi/server/SerializationWhitelist.html[serialization whitelist] can be used by setting the following system property.

[source]
----
codion.server.serializationFilterWhitelist=config/whitelist.txt
----

A whitelist can be created during a server dry-run by adding the following system property. The whitelist containing all classes deserialized during the run is written to disk on server shutdown.

[source]
----
codion.server.serializationFilterDryRun=true
----

.Example whitelist
[%collapsible]
====
[source]
----
include::{dir-source}/src/main/config/serialization-whitelist.txt[]
----
====

[#_server_configuration]
== Configuration

=== Example configuration file

[source]
----
include::{dir-source}/src/main/config/h2_embedded.config[]
----

== Code examples

Absolute bare-bones examples of how to run the EntityServer and connect to it.

=== RMI
[source]
----
include::{dir-manual-source}/is/codion/framework/demos/manual/store/ClientServer.java[tags=runServer]
----

=== HTTP
[source]
----
include::{dir-manual-source}/is/codion/framework/demos/manual/store/ClientServer.java[tags=runServerWithHttp]
----