= Server
:dir-tutorials: ../tutorials
:dir-source: ../../../../../demos/server
:dir-manual-source: ../../../../../demos/manual/src/main/java
:url-javadoc: link:../api

The Codion server provides RMI and HTTP connection options to clients.

== Features

* Firewall friendly RMI; uses one way communication without callbacks, uses two ports, one for the RMI Registry and one for client connections
* Integrated web server for serving HTTP client connections, based on https://github.com/javalin/javalin[Javalin] and https://github.com/eclipse/jetty.project[Jetty]
* All user authentication left to the database by default
* Comprehensive administration and monitoring facilities via the <<server-monitor.adoc#_server_monitor, ServerMonitor>>
* Featherweight server with moderate memory and CPU usage

== Security

Here's a great overview of RMI security risks and mitigations.

https://blog.tneitzel.eu/posts/01-attacking-java-rmi-via-ssrf[Attacking Java RMI via SSRF]

=== Authentication

The Codion server does not perform any user authentication by default, it leaves that up the underlying database.
An authentication layer can be added by implementing an {url-javadoc}{common-rmi}/is/codion/common/rmi/server/Authenticator.html[Authenticator] and registering it with the ServiceLoader.

==== Authenticator examples

<<{dir-tutorials}/chinook/chinook.adoc#_chinookauthenticator, ChinookAuthenticator>>

=== RMI SSL encryption

To enable SSL encryption between client and server, create a keystore and truststore pair and set the following system properties.

==== Server side

[source]
----
codion.server.connection.sslEnabled=true # <1>
javax.net.ssl.keyStore=keystore.jks
javax.net.ssl.keyStorePassword=password
----

<1> This property is 'true' by default, included here for completeness's sake

==== Client side

[source]
----
codion.client.trustStore=truststore.jks
codion.client.trustStorePassword=password
----

=== Class loading

No dynamic class loading is required.

=== Serialization filtering

See https://docs.oracle.com/en/java/javase/23/core/java-serialization-filters.html[Java Serialization Filters] and https://openjdk.org/jeps/290[JEP 290: Filter Incoming Serialization Data].

The framework provides a way to configure a https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/ObjectInputFilter.html[ObjectInputFilter] for deserialization, by specifying a {url-javadoc}{common-rmi}/is/codion/common/rmi/server/ObjectInputFilterFactory.html[ObjectInputFilterFactory] implementation class with the following system property.

[source]
----
codion.server.objectInputFilterFactoryClassName=\
    my.serialization.filter.MyObjectInputFilterFactory
----

==== Pattern filter

To use the built-in pattern based serialization filter, set the following system property.

[source]
----
codion.server.objectInputFilterFactoryClassName=\
    is.codion.common.rmi.server.SerializationFilterFactory
----

To use serialization filter patterns specified in a string, set the following system property.

[source]
----
codion.server.codion.server.serialization.filter.pattern=pattern1;pattern2
----

This is equivalent to setting the following:

[source]
----
jdk.serialFilter=pattern1;pattern2
----

To use the serialization pattern filter based on patterns in a file, set the following system property.

The file may contain all the patterns in a single line, using the ; delimiter or one pattern per line, without a delimiter. Lines starting with '#' are skipped as comments.

[source]
----
codion.server.codion.server.serialization.filter.patternFile=config/patterns.txt
----

----
codion.server.serialization.filter.patternFile=classpath:patterns.txt
----

A list of deserialized classes can be created during a server dry-run by adding the following system property.
The file containing all classes deserialized during the run is written to disk on server shutdown.

[source]
----
codion.server.serialization.filter.dryRunFile=deserialized.txt
----

.Example whitelist
[%collapsible]
====
[source]
----
include::{dir-source}/src/main/config/serialization-whitelist.txt[]
----
====

==== Resource exhaustion limits

The pattern-based serialization filter supports https://openjdk.org/jeps/290[JEP 290]  resource limits to prevent resource exhaustion attacks during deserialization.
These limits are enforced **during** deserialization, before objects are fully materialized in memory.

The following system properties configure the resource limits (with their default values):

[source]
----
codion.server.serialization.filter.maxBytes=10485760    # Maximum stream size: 10 MB
codion.server.serialization.filter.maxArray=100000      # Maximum array length: 100,000 elements
codion.server.serialization.filter.maxDepth=100         # Maximum object graph depth: 100 levels
codion.server.serialization.filter.maxRefs=10000        # Maximum internal references: 10,000 refs
----

These limits are automatically prepended to the serialization filter patterns.
For example, with a pattern file containing class names, the effective filter becomes:

[source]
----
maxbytes=10485760;maxarray=100000;maxdepth=100;maxrefs=10000;java.lang.String;is.codion.**;!*
----

**Important**: These limits provide the primary defense against resource exhaustion attacks.
Application-level validation (such as User credential length limits) cannot prevent memory allocation during deserialization,
making these https://openjdk.org/jeps/290[JEP 290] limits essential for security.

[#_server_configuration]
== Configuration

=== Example configuration file

[source]
----
include::{dir-source}/src/main/config/h2_embedded.config[]
----

== Code examples

Absolute bare-bones examples of how to run the EntityServer and connect to it.

=== RMI

[source]
----
include::{dir-manual-source}/is/codion/manual/store/ClientServer.java[tags=runServer]
----

=== HTTP

[source]
----
include::{dir-manual-source}/is/codion/manual/store/ClientServer.java[tags=runServerWithHttp]
----